package winrt.windows.ui.xaml;

@:valueType
@:include("winrt/Windows.UI.Xaml.h", true)
@:native("winrt::Windows::UI::Xaml::IUIElement")
extern interface IUIElement extends winrt.windows.foundation.IInspectable
{
    overload function DesiredSize(): winrt.windows.foundation.Size;
    overload function AllowDrop(): Bool;
    overload function AllowDrop(value: Bool): Void;
    overload function Opacity(): cxx.num.Float64;
    overload function Opacity(value: cxx.num.Float64): Void;
    overload function Clip(): winrt.windows.ui.xaml.media.RectangleGeometry;
    overload function Clip(value: cxx.ConstRef<winrt.windows.ui.xaml.media.RectangleGeometry>): Void;
    overload function RenderTransform(): winrt.windows.ui.xaml.media.Transform;
    overload function RenderTransform(value: cxx.ConstRef<winrt.windows.ui.xaml.media.Transform>): Void;
    overload function Projection(): winrt.windows.ui.xaml.media.Projection;
    overload function Projection(value: cxx.ConstRef<winrt.windows.ui.xaml.media.Projection>): Void;
    overload function RenderTransformOrigin(): winrt.windows.foundation.Point;
    overload function RenderTransformOrigin(value: cxx.ConstRef<winrt.windows.foundation.Point>): Void;
    overload function IsHitTestVisible(): Bool;
    overload function IsHitTestVisible(value: Bool): Void;
    overload function Visibility(): winrt.windows.ui.xaml.Visibility;
    overload function Visibility(value: cxx.ConstRef<winrt.windows.ui.xaml.Visibility>): Void;
    overload function RenderSize(): winrt.windows.foundation.Size;
    overload function UseLayoutRounding(): Bool;
    overload function UseLayoutRounding(value: Bool): Void;
    overload function Transitions(): winrt.windows.ui.xaml.media.animation.TransitionCollection;
    overload function Transitions(value: cxx.ConstRef<winrt.windows.ui.xaml.media.animation.TransitionCollection>): Void;
    overload function CacheMode(): winrt.windows.ui.xaml.media.CacheMode;
    overload function CacheMode(value: cxx.ConstRef<winrt.windows.ui.xaml.media.CacheMode>): Void;
    overload function IsTapEnabled(): Bool;
    overload function IsTapEnabled(value: Bool): Void;
    overload function IsDoubleTapEnabled(): Bool;
    overload function IsDoubleTapEnabled(value: Bool): Void;
    overload function IsRightTapEnabled(): Bool;
    overload function IsRightTapEnabled(value: Bool): Void;
    overload function IsHoldingEnabled(): Bool;
    overload function IsHoldingEnabled(value: Bool): Void;
    overload function ManipulationMode(): winrt.windows.ui.xaml.input.ManipulationModes;
    overload function ManipulationMode(value: cxx.ConstRef<winrt.windows.ui.xaml.input.ManipulationModes>): Void;
    overload function PointerCaptures(): winrt.windows.foundation.collections.IVectorView<winrt.windows.ui.xaml.input.Pointer> /* GenericTypeInstSig */;
    overload function KeyUp(handler: cxx.ConstRef<winrt.windows.ui.xaml.input.KeyEventHandler>): winrt.EventToken;
    @:noExcept overload function KeyUp(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function KeyDown(handler: cxx.ConstRef<winrt.windows.ui.xaml.input.KeyEventHandler>): winrt.EventToken;
    @:noExcept overload function KeyDown(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function GotFocus(handler: cxx.ConstRef<winrt.windows.ui.xaml.RoutedEventHandler>): winrt.EventToken;
    @:noExcept overload function GotFocus(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function LostFocus(handler: cxx.ConstRef<winrt.windows.ui.xaml.RoutedEventHandler>): winrt.EventToken;
    @:noExcept overload function LostFocus(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function DragEnter(handler: cxx.ConstRef<winrt.windows.ui.xaml.DragEventHandler>): winrt.EventToken;
    @:noExcept overload function DragEnter(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function DragLeave(handler: cxx.ConstRef<winrt.windows.ui.xaml.DragEventHandler>): winrt.EventToken;
    @:noExcept overload function DragLeave(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function DragOver(handler: cxx.ConstRef<winrt.windows.ui.xaml.DragEventHandler>): winrt.EventToken;
    @:noExcept overload function DragOver(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function Drop(handler: cxx.ConstRef<winrt.windows.ui.xaml.DragEventHandler>): winrt.EventToken;
    @:noExcept overload function Drop(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function PointerPressed(handler: cxx.ConstRef<winrt.windows.ui.xaml.input.PointerEventHandler>): winrt.EventToken;
    @:noExcept overload function PointerPressed(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function PointerMoved(handler: cxx.ConstRef<winrt.windows.ui.xaml.input.PointerEventHandler>): winrt.EventToken;
    @:noExcept overload function PointerMoved(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function PointerReleased(handler: cxx.ConstRef<winrt.windows.ui.xaml.input.PointerEventHandler>): winrt.EventToken;
    @:noExcept overload function PointerReleased(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function PointerEntered(handler: cxx.ConstRef<winrt.windows.ui.xaml.input.PointerEventHandler>): winrt.EventToken;
    @:noExcept overload function PointerEntered(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function PointerExited(handler: cxx.ConstRef<winrt.windows.ui.xaml.input.PointerEventHandler>): winrt.EventToken;
    @:noExcept overload function PointerExited(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function PointerCaptureLost(handler: cxx.ConstRef<winrt.windows.ui.xaml.input.PointerEventHandler>): winrt.EventToken;
    @:noExcept overload function PointerCaptureLost(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function PointerCanceled(handler: cxx.ConstRef<winrt.windows.ui.xaml.input.PointerEventHandler>): winrt.EventToken;
    @:noExcept overload function PointerCanceled(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function PointerWheelChanged(handler: cxx.ConstRef<winrt.windows.ui.xaml.input.PointerEventHandler>): winrt.EventToken;
    @:noExcept overload function PointerWheelChanged(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function Tapped(handler: cxx.ConstRef<winrt.windows.ui.xaml.input.TappedEventHandler>): winrt.EventToken;
    @:noExcept overload function Tapped(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function DoubleTapped(handler: cxx.ConstRef<winrt.windows.ui.xaml.input.DoubleTappedEventHandler>): winrt.EventToken;
    @:noExcept overload function DoubleTapped(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function Holding(handler: cxx.ConstRef<winrt.windows.ui.xaml.input.HoldingEventHandler>): winrt.EventToken;
    @:noExcept overload function Holding(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function RightTapped(handler: cxx.ConstRef<winrt.windows.ui.xaml.input.RightTappedEventHandler>): winrt.EventToken;
    @:noExcept overload function RightTapped(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function ManipulationStarting(handler: cxx.ConstRef<winrt.windows.ui.xaml.input.ManipulationStartingEventHandler>): winrt.EventToken;
    @:noExcept overload function ManipulationStarting(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function ManipulationInertiaStarting(handler: cxx.ConstRef<winrt.windows.ui.xaml.input.ManipulationInertiaStartingEventHandler>): winrt.EventToken;
    @:noExcept overload function ManipulationInertiaStarting(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function ManipulationStarted(handler: cxx.ConstRef<winrt.windows.ui.xaml.input.ManipulationStartedEventHandler>): winrt.EventToken;
    @:noExcept overload function ManipulationStarted(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function ManipulationDelta(handler: cxx.ConstRef<winrt.windows.ui.xaml.input.ManipulationDeltaEventHandler>): winrt.EventToken;
    @:noExcept overload function ManipulationDelta(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function ManipulationCompleted(handler: cxx.ConstRef<winrt.windows.ui.xaml.input.ManipulationCompletedEventHandler>): winrt.EventToken;
    @:noExcept overload function ManipulationCompleted(token: cxx.ConstRef<winrt.EventToken>): Void;
    function Measure(availableSize: cxx.ConstRef<winrt.windows.foundation.Size>): Void;
    function Arrange(finalRect: cxx.ConstRef<winrt.windows.foundation.Rect>): Void;
    function CapturePointer(value: cxx.ConstRef<winrt.windows.ui.xaml.input.Pointer>): Bool;
    function ReleasePointerCapture(value: cxx.ConstRef<winrt.windows.ui.xaml.input.Pointer>): Void;
    function ReleasePointerCaptures(): Void;
    function AddHandler(routedEvent: cxx.ConstRef<winrt.windows.ui.xaml.RoutedEvent>, handler: cxx.ConstRef<winrt.windows.foundation.IInspectable>, handledEventsToo: Bool): Void;
    function RemoveHandler(routedEvent: cxx.ConstRef<winrt.windows.ui.xaml.RoutedEvent>, handler: cxx.ConstRef<winrt.windows.foundation.IInspectable>): Void;
    function TransformToVisual(visual: cxx.ConstRef<winrt.windows.ui.xaml.UIElement>): winrt.windows.ui.xaml.media.GeneralTransform;
    function InvalidateMeasure(): Void;
    function InvalidateArrange(): Void;
    function UpdateLayout(): Void;
}
