package winrt.microsoft.ui.text;

@:include("winrt/Microsoft.UI.Text.h", true)
@:native("winrt::Microsoft::UI::Text::TextScript")
extern enum abstract TextScript(Int32)
{
    @:native("winrt::Microsoft::UI::Text::TextScript::Undefined") final Undefined;
    @:native("winrt::Microsoft::UI::Text::TextScript::Ansi") final Ansi;
    @:native("winrt::Microsoft::UI::Text::TextScript::EastEurope") final EastEurope;
    @:native("winrt::Microsoft::UI::Text::TextScript::Cyrillic") final Cyrillic;
    @:native("winrt::Microsoft::UI::Text::TextScript::Greek") final Greek;
    @:native("winrt::Microsoft::UI::Text::TextScript::Turkish") final Turkish;
    @:native("winrt::Microsoft::UI::Text::TextScript::Hebrew") final Hebrew;
    @:native("winrt::Microsoft::UI::Text::TextScript::Arabic") final Arabic;
    @:native("winrt::Microsoft::UI::Text::TextScript::Baltic") final Baltic;
    @:native("winrt::Microsoft::UI::Text::TextScript::Vietnamese") final Vietnamese;
    @:native("winrt::Microsoft::UI::Text::TextScript::Default") final Default;
    @:native("winrt::Microsoft::UI::Text::TextScript::Symbol") final Symbol;
    @:native("winrt::Microsoft::UI::Text::TextScript::Thai") final Thai;
    @:native("winrt::Microsoft::UI::Text::TextScript::ShiftJis") final ShiftJis;
    @:native("winrt::Microsoft::UI::Text::TextScript::GB2312") final GB2312;
    @:native("winrt::Microsoft::UI::Text::TextScript::Hangul") final Hangul;
    @:native("winrt::Microsoft::UI::Text::TextScript::Big5") final Big5;
    @:native("winrt::Microsoft::UI::Text::TextScript::PC437") final PC437;
    @:native("winrt::Microsoft::UI::Text::TextScript::Oem") final Oem;
    @:native("winrt::Microsoft::UI::Text::TextScript::Mac") final Mac;
    @:native("winrt::Microsoft::UI::Text::TextScript::Armenian") final Armenian;
    @:native("winrt::Microsoft::UI::Text::TextScript::Syriac") final Syriac;
    @:native("winrt::Microsoft::UI::Text::TextScript::Thaana") final Thaana;
    @:native("winrt::Microsoft::UI::Text::TextScript::Devanagari") final Devanagari;
    @:native("winrt::Microsoft::UI::Text::TextScript::Bengali") final Bengali;
    @:native("winrt::Microsoft::UI::Text::TextScript::Gurmukhi") final Gurmukhi;
    @:native("winrt::Microsoft::UI::Text::TextScript::Gujarati") final Gujarati;
    @:native("winrt::Microsoft::UI::Text::TextScript::Oriya") final Oriya;
    @:native("winrt::Microsoft::UI::Text::TextScript::Tamil") final Tamil;
    @:native("winrt::Microsoft::UI::Text::TextScript::Telugu") final Telugu;
    @:native("winrt::Microsoft::UI::Text::TextScript::Kannada") final Kannada;
    @:native("winrt::Microsoft::UI::Text::TextScript::Malayalam") final Malayalam;
    @:native("winrt::Microsoft::UI::Text::TextScript::Sinhala") final Sinhala;
    @:native("winrt::Microsoft::UI::Text::TextScript::Lao") final Lao;
    @:native("winrt::Microsoft::UI::Text::TextScript::Tibetan") final Tibetan;
    @:native("winrt::Microsoft::UI::Text::TextScript::Myanmar") final Myanmar;
    @:native("winrt::Microsoft::UI::Text::TextScript::Georgian") final Georgian;
    @:native("winrt::Microsoft::UI::Text::TextScript::Jamo") final Jamo;
    @:native("winrt::Microsoft::UI::Text::TextScript::Ethiopic") final Ethiopic;
    @:native("winrt::Microsoft::UI::Text::TextScript::Cherokee") final Cherokee;
    @:native("winrt::Microsoft::UI::Text::TextScript::Aboriginal") final Aboriginal;
    @:native("winrt::Microsoft::UI::Text::TextScript::Ogham") final Ogham;
    @:native("winrt::Microsoft::UI::Text::TextScript::Runic") final Runic;
    @:native("winrt::Microsoft::UI::Text::TextScript::Khmer") final Khmer;
    @:native("winrt::Microsoft::UI::Text::TextScript::Mongolian") final Mongolian;
    @:native("winrt::Microsoft::UI::Text::TextScript::Braille") final Braille;
    @:native("winrt::Microsoft::UI::Text::TextScript::Yi") final Yi;
    @:native("winrt::Microsoft::UI::Text::TextScript::Limbu") final Limbu;
    @:native("winrt::Microsoft::UI::Text::TextScript::TaiLe") final TaiLe;
    @:native("winrt::Microsoft::UI::Text::TextScript::NewTaiLue") final NewTaiLue;
    @:native("winrt::Microsoft::UI::Text::TextScript::SylotiNagri") final SylotiNagri;
    @:native("winrt::Microsoft::UI::Text::TextScript::Kharoshthi") final Kharoshthi;
    @:native("winrt::Microsoft::UI::Text::TextScript::Kayahli") final Kayahli;
    @:native("winrt::Microsoft::UI::Text::TextScript::UnicodeSymbol") final UnicodeSymbol;
    @:native("winrt::Microsoft::UI::Text::TextScript::Emoji") final Emoji;
    @:native("winrt::Microsoft::UI::Text::TextScript::Glagolitic") final Glagolitic;
    @:native("winrt::Microsoft::UI::Text::TextScript::Lisu") final Lisu;
    @:native("winrt::Microsoft::UI::Text::TextScript::Vai") final Vai;
    @:native("winrt::Microsoft::UI::Text::TextScript::NKo") final NKo;
    @:native("winrt::Microsoft::UI::Text::TextScript::Osmanya") final Osmanya;
    @:native("winrt::Microsoft::UI::Text::TextScript::PhagsPa") final PhagsPa;
    @:native("winrt::Microsoft::UI::Text::TextScript::Gothic") final Gothic;
    @:native("winrt::Microsoft::UI::Text::TextScript::Deseret") final Deseret;
    @:native("winrt::Microsoft::UI::Text::TextScript::Tifinagh") final Tifinagh;
}
