package winrt.windows.applicationmodel.store.preview.installcontrol;

@:valueType
@:unreflective
@:structAccess
@:semantics(variable)
@:include("winrt/Windows.ApplicationModel.Store.Preview.InstallControl.h", true)
@:native("winrt::Windows::ApplicationModel::Store::Preview::InstallControl::AppInstallManager")
extern class AppInstallManager
    implements winrt.windows.applicationmodel.store.preview.installcontrol.IAppInstallManager
    implements winrt.windows.applicationmodel.store.preview.installcontrol.IAppInstallManager2
    implements winrt.windows.applicationmodel.store.preview.installcontrol.IAppInstallManager3
    implements winrt.windows.applicationmodel.store.preview.installcontrol.IAppInstallManager4
    implements winrt.windows.applicationmodel.store.preview.installcontrol.IAppInstallManager5
    implements winrt.windows.applicationmodel.store.preview.installcontrol.IAppInstallManager6
    implements winrt.windows.applicationmodel.store.preview.installcontrol.IAppInstallManager7
{
    function new();
    overload function AppInstallItems(): winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */;
    overload function Cancel(productId: ConstRef<winrt.HString>): Void;
    overload function Pause(productId: ConstRef<winrt.HString>): Void;
    overload function Restart(productId: ConstRef<winrt.HString>): Void;
    overload function ItemCompleted(handler: ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallManager, winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallManagerItemEventArgs> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function ItemCompleted(token: ConstRef<winrt.EventToken>): Void;
    overload function ItemStatusChanged(handler: ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallManager, winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallManagerItemEventArgs> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function ItemStatusChanged(token: ConstRef<winrt.EventToken>): Void;
    overload function AutoUpdateSetting(): winrt.windows.applicationmodel.store.preview.installcontrol.AutoUpdateSetting;
    overload function AutoUpdateSetting(value: ConstRef<winrt.windows.applicationmodel.store.preview.installcontrol.AutoUpdateSetting>): Void;
    overload function AcquisitionIdentity(): winrt.HString;
    overload function AcquisitionIdentity(value: ConstRef<winrt.HString>): Void;
    function GetIsApplicableAsync(productId: ConstRef<winrt.HString>, skuId: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<Bool> /* GenericTypeInstSig */;
    overload function StartAppInstallAsync(productId: ConstRef<winrt.HString>, skuId: ConstRef<winrt.HString>, repair: Bool, forceUseOfNonRemovableStorage: Bool): winrt.windows.foundation.IAsyncOperation<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */;
    overload function UpdateAppByPackageFamilyNameAsync(packageFamilyName: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */;
    overload function SearchForUpdatesAsync(productId: ConstRef<winrt.HString>, skuId: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */;
    overload function SearchForAllUpdatesAsync(): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    function IsStoreBlockedByPolicyAsync(storeClientName: ConstRef<winrt.HString>, storeClientPublisher: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<Bool> /* GenericTypeInstSig */;
    overload function GetIsAppAllowedToInstallAsync(productId: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<Bool> /* GenericTypeInstSig */;
    overload function StartAppInstallAsync(productId: ConstRef<winrt.HString>, skuId: ConstRef<winrt.HString>, repair: Bool, forceUseOfNonRemovableStorage: Bool, catalogId: ConstRef<winrt.HString>, bundleId: ConstRef<winrt.HString>, correlationVector: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */;
    overload function UpdateAppByPackageFamilyNameAsync(packageFamilyName: ConstRef<winrt.HString>, correlationVector: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */;
    overload function SearchForUpdatesAsync(productId: ConstRef<winrt.HString>, skuId: ConstRef<winrt.HString>, catalogId: ConstRef<winrt.HString>, correlationVector: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */;
    overload function SearchForAllUpdatesAsync(correlationVector: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    overload function GetIsAppAllowedToInstallAsync(productId: ConstRef<winrt.HString>, skuId: ConstRef<winrt.HString>, catalogId: ConstRef<winrt.HString>, correlationVector: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<Bool> /* GenericTypeInstSig */;
    overload function Cancel(productId: ConstRef<winrt.HString>, correlationVector: ConstRef<winrt.HString>): Void;
    overload function Pause(productId: ConstRef<winrt.HString>, correlationVector: ConstRef<winrt.HString>): Void;
    overload function Restart(productId: ConstRef<winrt.HString>, correlationVector: ConstRef<winrt.HString>): Void;
    overload function StartProductInstallAsync(productId: ConstRef<winrt.HString>, catalogId: ConstRef<winrt.HString>, flightId: ConstRef<winrt.HString>, clientId: ConstRef<winrt.HString>, repair: Bool, forceUseOfNonRemovableStorage: Bool, correlationVector: ConstRef<winrt.HString>, targetVolume: ConstRef<winrt.windows.management.deployment.PackageVolume>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    overload function StartProductInstallForUserAsync(user: ConstRef<winrt.windows.system.User>, productId: ConstRef<winrt.HString>, catalogId: ConstRef<winrt.HString>, flightId: ConstRef<winrt.HString>, clientId: ConstRef<winrt.HString>, repair: Bool, forceUseOfNonRemovableStorage: Bool, correlationVector: ConstRef<winrt.HString>, targetVolume: ConstRef<winrt.windows.management.deployment.PackageVolume>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    function UpdateAppByPackageFamilyNameForUserAsync(user: ConstRef<winrt.windows.system.User>, packageFamilyName: ConstRef<winrt.HString>, correlationVector: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */;
    overload function SearchForUpdatesForUserAsync(user: ConstRef<winrt.windows.system.User>, productId: ConstRef<winrt.HString>, skuId: ConstRef<winrt.HString>, catalogId: ConstRef<winrt.HString>, correlationVector: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */;
    overload function SearchForAllUpdatesForUserAsync(user: ConstRef<winrt.windows.system.User>, correlationVector: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    function GetIsAppAllowedToInstallForUserAsync(user: ConstRef<winrt.windows.system.User>, productId: ConstRef<winrt.HString>, skuId: ConstRef<winrt.HString>, catalogId: ConstRef<winrt.HString>, correlationVector: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<Bool> /* GenericTypeInstSig */;
    function GetIsApplicableForUserAsync(user: ConstRef<winrt.windows.system.User>, productId: ConstRef<winrt.HString>, skuId: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<Bool> /* GenericTypeInstSig */;
    function MoveToFrontOfDownloadQueue(productId: ConstRef<winrt.HString>, correlationVector: ConstRef<winrt.HString>): Void;
    function GetFreeUserEntitlementAsync(storeId: ConstRef<winrt.HString>, campaignId: ConstRef<winrt.HString>, correlationVector: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.applicationmodel.store.preview.installcontrol.GetEntitlementResult> /* GenericTypeInstSig */;
    function GetFreeUserEntitlementForUserAsync(user: ConstRef<winrt.windows.system.User>, storeId: ConstRef<winrt.HString>, campaignId: ConstRef<winrt.HString>, correlationVector: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.applicationmodel.store.preview.installcontrol.GetEntitlementResult> /* GenericTypeInstSig */;
    function GetFreeDeviceEntitlementAsync(storeId: ConstRef<winrt.HString>, campaignId: ConstRef<winrt.HString>, correlationVector: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.applicationmodel.store.preview.installcontrol.GetEntitlementResult> /* GenericTypeInstSig */;
    overload function AppInstallItemsWithGroupSupport(): winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */;
    overload function SearchForAllUpdatesAsync(correlationVector: ConstRef<winrt.HString>, clientId: ConstRef<winrt.HString>, updateOptions: ConstRef<winrt.windows.applicationmodel.store.preview.installcontrol.AppUpdateOptions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    overload function SearchForAllUpdatesForUserAsync(user: ConstRef<winrt.windows.system.User>, correlationVector: ConstRef<winrt.HString>, clientId: ConstRef<winrt.HString>, updateOptions: ConstRef<winrt.windows.applicationmodel.store.preview.installcontrol.AppUpdateOptions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    overload function SearchForUpdatesAsync(productId: ConstRef<winrt.HString>, skuId: ConstRef<winrt.HString>, correlationVector: ConstRef<winrt.HString>, clientId: ConstRef<winrt.HString>, updateOptions: ConstRef<winrt.windows.applicationmodel.store.preview.installcontrol.AppUpdateOptions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */;
    overload function SearchForUpdatesForUserAsync(user: ConstRef<winrt.windows.system.User>, productId: ConstRef<winrt.HString>, skuId: ConstRef<winrt.HString>, correlationVector: ConstRef<winrt.HString>, clientId: ConstRef<winrt.HString>, updateOptions: ConstRef<winrt.windows.applicationmodel.store.preview.installcontrol.AppUpdateOptions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */;
    overload function StartProductInstallAsync(productId: ConstRef<winrt.HString>, flightId: ConstRef<winrt.HString>, clientId: ConstRef<winrt.HString>, correlationVector: ConstRef<winrt.HString>, installOptions: ConstRef<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallOptions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    overload function StartProductInstallForUserAsync(user: ConstRef<winrt.windows.system.User>, productId: ConstRef<winrt.HString>, flightId: ConstRef<winrt.HString>, clientId: ConstRef<winrt.HString>, correlationVector: ConstRef<winrt.HString>, installOptions: ConstRef<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallOptions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    function GetIsPackageIdentityAllowedToInstallAsync(correlationVector: ConstRef<winrt.HString>, packageIdentityName: ConstRef<winrt.HString>, publisherCertificateName: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<Bool> /* GenericTypeInstSig */;
    function GetIsPackageIdentityAllowedToInstallForUserAsync(user: ConstRef<winrt.windows.system.User>, correlationVector: ConstRef<winrt.HString>, packageIdentityName: ConstRef<winrt.HString>, publisherCertificateName: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<Bool> /* GenericTypeInstSig */;
    overload function CanInstallForAllUsers(): Bool;
}
