package winrt.windows.applicationmodel.store.preview.installcontrol;

@:valueType
@:include("winrt/Windows.ApplicationModel.Store.Preview.InstallControl.h", true)
@:native("winrt::Windows::ApplicationModel::Store::Preview::InstallControl::AppInstallManager")
extern class AppInstallManager
    implements winrt.windows.applicationmodel.store.preview.installcontrol.IAppInstallManager
    implements winrt.windows.applicationmodel.store.preview.installcontrol.IAppInstallManager2
    implements winrt.windows.applicationmodel.store.preview.installcontrol.IAppInstallManager3
    implements winrt.windows.applicationmodel.store.preview.installcontrol.IAppInstallManager4
    implements winrt.windows.applicationmodel.store.preview.installcontrol.IAppInstallManager5
    implements winrt.windows.applicationmodel.store.preview.installcontrol.IAppInstallManager6
    implements winrt.windows.applicationmodel.store.preview.installcontrol.IAppInstallManager7
{
    function new();
    overload function AppInstallItems(): winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */;
    overload function Cancel(productId: cxx.ConstRef<winrt.HString>): Void;
    overload function Pause(productId: cxx.ConstRef<winrt.HString>): Void;
    overload function Restart(productId: cxx.ConstRef<winrt.HString>): Void;
    overload function ItemCompleted(handler: cxx.ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallManager, winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallManagerItemEventArgs> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function ItemCompleted(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function ItemStatusChanged(handler: cxx.ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallManager, winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallManagerItemEventArgs> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function ItemStatusChanged(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function AutoUpdateSetting(): winrt.windows.applicationmodel.store.preview.installcontrol.AutoUpdateSetting;
    overload function AutoUpdateSetting(value: cxx.ConstRef<winrt.windows.applicationmodel.store.preview.installcontrol.AutoUpdateSetting>): Void;
    overload function AcquisitionIdentity(): winrt.HString;
    overload function AcquisitionIdentity(value: cxx.ConstRef<winrt.HString>): Void;
    function GetIsApplicableAsync(productId: cxx.ConstRef<winrt.HString>, skuId: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<Bool> /* GenericTypeInstSig */;
    overload function StartAppInstallAsync(productId: cxx.ConstRef<winrt.HString>, skuId: cxx.ConstRef<winrt.HString>, repair: Bool, forceUseOfNonRemovableStorage: Bool): winrt.windows.foundation.IAsyncOperation<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */;
    overload function UpdateAppByPackageFamilyNameAsync(packageFamilyName: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */;
    overload function SearchForUpdatesAsync(productId: cxx.ConstRef<winrt.HString>, skuId: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */;
    overload function SearchForAllUpdatesAsync(): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    function IsStoreBlockedByPolicyAsync(storeClientName: cxx.ConstRef<winrt.HString>, storeClientPublisher: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<Bool> /* GenericTypeInstSig */;
    overload function GetIsAppAllowedToInstallAsync(productId: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<Bool> /* GenericTypeInstSig */;
    overload function StartAppInstallAsync(productId: cxx.ConstRef<winrt.HString>, skuId: cxx.ConstRef<winrt.HString>, repair: Bool, forceUseOfNonRemovableStorage: Bool, catalogId: cxx.ConstRef<winrt.HString>, bundleId: cxx.ConstRef<winrt.HString>, correlationVector: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */;
    overload function UpdateAppByPackageFamilyNameAsync(packageFamilyName: cxx.ConstRef<winrt.HString>, correlationVector: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */;
    overload function SearchForUpdatesAsync(productId: cxx.ConstRef<winrt.HString>, skuId: cxx.ConstRef<winrt.HString>, catalogId: cxx.ConstRef<winrt.HString>, correlationVector: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */;
    overload function SearchForAllUpdatesAsync(correlationVector: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    overload function GetIsAppAllowedToInstallAsync(productId: cxx.ConstRef<winrt.HString>, skuId: cxx.ConstRef<winrt.HString>, catalogId: cxx.ConstRef<winrt.HString>, correlationVector: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<Bool> /* GenericTypeInstSig */;
    overload function Cancel(productId: cxx.ConstRef<winrt.HString>, correlationVector: cxx.ConstRef<winrt.HString>): Void;
    overload function Pause(productId: cxx.ConstRef<winrt.HString>, correlationVector: cxx.ConstRef<winrt.HString>): Void;
    overload function Restart(productId: cxx.ConstRef<winrt.HString>, correlationVector: cxx.ConstRef<winrt.HString>): Void;
    overload function StartProductInstallAsync(productId: cxx.ConstRef<winrt.HString>, catalogId: cxx.ConstRef<winrt.HString>, flightId: cxx.ConstRef<winrt.HString>, clientId: cxx.ConstRef<winrt.HString>, repair: Bool, forceUseOfNonRemovableStorage: Bool, correlationVector: cxx.ConstRef<winrt.HString>, targetVolume: cxx.ConstRef<winrt.windows.management.deployment.PackageVolume>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    overload function StartProductInstallForUserAsync(user: cxx.ConstRef<winrt.windows.system.User>, productId: cxx.ConstRef<winrt.HString>, catalogId: cxx.ConstRef<winrt.HString>, flightId: cxx.ConstRef<winrt.HString>, clientId: cxx.ConstRef<winrt.HString>, repair: Bool, forceUseOfNonRemovableStorage: Bool, correlationVector: cxx.ConstRef<winrt.HString>, targetVolume: cxx.ConstRef<winrt.windows.management.deployment.PackageVolume>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    function UpdateAppByPackageFamilyNameForUserAsync(user: cxx.ConstRef<winrt.windows.system.User>, packageFamilyName: cxx.ConstRef<winrt.HString>, correlationVector: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */;
    overload function SearchForUpdatesForUserAsync(user: cxx.ConstRef<winrt.windows.system.User>, productId: cxx.ConstRef<winrt.HString>, skuId: cxx.ConstRef<winrt.HString>, catalogId: cxx.ConstRef<winrt.HString>, correlationVector: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */;
    overload function SearchForAllUpdatesForUserAsync(user: cxx.ConstRef<winrt.windows.system.User>, correlationVector: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    function GetIsAppAllowedToInstallForUserAsync(user: cxx.ConstRef<winrt.windows.system.User>, productId: cxx.ConstRef<winrt.HString>, skuId: cxx.ConstRef<winrt.HString>, catalogId: cxx.ConstRef<winrt.HString>, correlationVector: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<Bool> /* GenericTypeInstSig */;
    function GetIsApplicableForUserAsync(user: cxx.ConstRef<winrt.windows.system.User>, productId: cxx.ConstRef<winrt.HString>, skuId: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<Bool> /* GenericTypeInstSig */;
    function MoveToFrontOfDownloadQueue(productId: cxx.ConstRef<winrt.HString>, correlationVector: cxx.ConstRef<winrt.HString>): Void;
    function GetFreeUserEntitlementAsync(storeId: cxx.ConstRef<winrt.HString>, campaignId: cxx.ConstRef<winrt.HString>, correlationVector: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.applicationmodel.store.preview.installcontrol.GetEntitlementResult> /* GenericTypeInstSig */;
    function GetFreeUserEntitlementForUserAsync(user: cxx.ConstRef<winrt.windows.system.User>, storeId: cxx.ConstRef<winrt.HString>, campaignId: cxx.ConstRef<winrt.HString>, correlationVector: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.applicationmodel.store.preview.installcontrol.GetEntitlementResult> /* GenericTypeInstSig */;
    function GetFreeDeviceEntitlementAsync(storeId: cxx.ConstRef<winrt.HString>, campaignId: cxx.ConstRef<winrt.HString>, correlationVector: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.applicationmodel.store.preview.installcontrol.GetEntitlementResult> /* GenericTypeInstSig */;
    overload function AppInstallItemsWithGroupSupport(): winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */;
    overload function SearchForAllUpdatesAsync(correlationVector: cxx.ConstRef<winrt.HString>, clientId: cxx.ConstRef<winrt.HString>, updateOptions: cxx.ConstRef<winrt.windows.applicationmodel.store.preview.installcontrol.AppUpdateOptions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    overload function SearchForAllUpdatesForUserAsync(user: cxx.ConstRef<winrt.windows.system.User>, correlationVector: cxx.ConstRef<winrt.HString>, clientId: cxx.ConstRef<winrt.HString>, updateOptions: cxx.ConstRef<winrt.windows.applicationmodel.store.preview.installcontrol.AppUpdateOptions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    overload function SearchForUpdatesAsync(productId: cxx.ConstRef<winrt.HString>, skuId: cxx.ConstRef<winrt.HString>, correlationVector: cxx.ConstRef<winrt.HString>, clientId: cxx.ConstRef<winrt.HString>, updateOptions: cxx.ConstRef<winrt.windows.applicationmodel.store.preview.installcontrol.AppUpdateOptions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */;
    overload function SearchForUpdatesForUserAsync(user: cxx.ConstRef<winrt.windows.system.User>, productId: cxx.ConstRef<winrt.HString>, skuId: cxx.ConstRef<winrt.HString>, correlationVector: cxx.ConstRef<winrt.HString>, clientId: cxx.ConstRef<winrt.HString>, updateOptions: cxx.ConstRef<winrt.windows.applicationmodel.store.preview.installcontrol.AppUpdateOptions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */;
    overload function StartProductInstallAsync(productId: cxx.ConstRef<winrt.HString>, flightId: cxx.ConstRef<winrt.HString>, clientId: cxx.ConstRef<winrt.HString>, correlationVector: cxx.ConstRef<winrt.HString>, installOptions: cxx.ConstRef<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallOptions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    overload function StartProductInstallForUserAsync(user: cxx.ConstRef<winrt.windows.system.User>, productId: cxx.ConstRef<winrt.HString>, flightId: cxx.ConstRef<winrt.HString>, clientId: cxx.ConstRef<winrt.HString>, correlationVector: cxx.ConstRef<winrt.HString>, installOptions: cxx.ConstRef<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallOptions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    function GetIsPackageIdentityAllowedToInstallAsync(correlationVector: cxx.ConstRef<winrt.HString>, packageIdentityName: cxx.ConstRef<winrt.HString>, publisherCertificateName: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<Bool> /* GenericTypeInstSig */;
    function GetIsPackageIdentityAllowedToInstallForUserAsync(user: cxx.ConstRef<winrt.windows.system.User>, correlationVector: cxx.ConstRef<winrt.HString>, packageIdentityName: cxx.ConstRef<winrt.HString>, publisherCertificateName: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<Bool> /* GenericTypeInstSig */;
    overload function CanInstallForAllUsers(): Bool;
}
