package winrt.windows.applicationmodel.store.preview.installcontrol;

@:valueType
@:unreflective
@:structAccess
@:semantics(variable)
@:include("winrt/Windows.ApplicationModel.Store.Preview.InstallControl.h", true)
@:native("winrt::Windows::ApplicationModel::Store::Preview::InstallControl::IAppInstallManager6")
extern interface IAppInstallManager6 extends winrt.windows.foundation.IInspectable
{
    function SearchForAllUpdatesAsync(correlationVector: ConstRef<winrt.HString>, clientId: ConstRef<winrt.HString>, updateOptions: ConstRef<winrt.windows.applicationmodel.store.preview.installcontrol.AppUpdateOptions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    function SearchForAllUpdatesForUserAsync(user: ConstRef<winrt.windows.system.User>, correlationVector: ConstRef<winrt.HString>, clientId: ConstRef<winrt.HString>, updateOptions: ConstRef<winrt.windows.applicationmodel.store.preview.installcontrol.AppUpdateOptions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    function SearchForUpdatesAsync(productId: ConstRef<winrt.HString>, skuId: ConstRef<winrt.HString>, correlationVector: ConstRef<winrt.HString>, clientId: ConstRef<winrt.HString>, updateOptions: ConstRef<winrt.windows.applicationmodel.store.preview.installcontrol.AppUpdateOptions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */;
    function SearchForUpdatesForUserAsync(user: ConstRef<winrt.windows.system.User>, productId: ConstRef<winrt.HString>, skuId: ConstRef<winrt.HString>, correlationVector: ConstRef<winrt.HString>, clientId: ConstRef<winrt.HString>, updateOptions: ConstRef<winrt.windows.applicationmodel.store.preview.installcontrol.AppUpdateOptions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */;
    function StartProductInstallAsync(productId: ConstRef<winrt.HString>, flightId: ConstRef<winrt.HString>, clientId: ConstRef<winrt.HString>, correlationVector: ConstRef<winrt.HString>, installOptions: ConstRef<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallOptions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    function StartProductInstallForUserAsync(user: ConstRef<winrt.windows.system.User>, productId: ConstRef<winrt.HString>, flightId: ConstRef<winrt.HString>, clientId: ConstRef<winrt.HString>, correlationVector: ConstRef<winrt.HString>, installOptions: ConstRef<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallOptions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    function GetIsPackageIdentityAllowedToInstallAsync(correlationVector: ConstRef<winrt.HString>, packageIdentityName: ConstRef<winrt.HString>, publisherCertificateName: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<Bool> /* GenericTypeInstSig */;
    function GetIsPackageIdentityAllowedToInstallForUserAsync(user: ConstRef<winrt.windows.system.User>, correlationVector: ConstRef<winrt.HString>, packageIdentityName: ConstRef<winrt.HString>, publisherCertificateName: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<Bool> /* GenericTypeInstSig */;
}
