package winrt.windows.applicationmodel.store.preview.installcontrol;

@:valueType
@:include("winrt/Windows.ApplicationModel.Store.Preview.InstallControl.h", true)
@:native("winrt::Windows::ApplicationModel::Store::Preview::InstallControl::IAppInstallManager3")
extern interface IAppInstallManager3 extends winrt.windows.foundation.IInspectable
{
    function StartProductInstallAsync(productId: cxx.ConstRef<winrt.HString>, catalogId: cxx.ConstRef<winrt.HString>, flightId: cxx.ConstRef<winrt.HString>, clientId: cxx.ConstRef<winrt.HString>, repair: Bool, forceUseOfNonRemovableStorage: Bool, correlationVector: cxx.ConstRef<winrt.HString>, targetVolume: cxx.ConstRef<winrt.windows.management.deployment.PackageVolume>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    function StartProductInstallForUserAsync(user: cxx.ConstRef<winrt.windows.system.User>, productId: cxx.ConstRef<winrt.HString>, catalogId: cxx.ConstRef<winrt.HString>, flightId: cxx.ConstRef<winrt.HString>, clientId: cxx.ConstRef<winrt.HString>, repair: Bool, forceUseOfNonRemovableStorage: Bool, correlationVector: cxx.ConstRef<winrt.HString>, targetVolume: cxx.ConstRef<winrt.windows.management.deployment.PackageVolume>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    function UpdateAppByPackageFamilyNameForUserAsync(user: cxx.ConstRef<winrt.windows.system.User>, packageFamilyName: cxx.ConstRef<winrt.HString>, correlationVector: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */;
    function SearchForUpdatesForUserAsync(user: cxx.ConstRef<winrt.windows.system.User>, productId: cxx.ConstRef<winrt.HString>, skuId: cxx.ConstRef<winrt.HString>, catalogId: cxx.ConstRef<winrt.HString>, correlationVector: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */;
    function SearchForAllUpdatesForUserAsync(user: cxx.ConstRef<winrt.windows.system.User>, correlationVector: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.store.preview.installcontrol.AppInstallItem> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    function GetIsAppAllowedToInstallForUserAsync(user: cxx.ConstRef<winrt.windows.system.User>, productId: cxx.ConstRef<winrt.HString>, skuId: cxx.ConstRef<winrt.HString>, catalogId: cxx.ConstRef<winrt.HString>, correlationVector: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<Bool> /* GenericTypeInstSig */;
    function GetIsApplicableForUserAsync(user: cxx.ConstRef<winrt.windows.system.User>, productId: cxx.ConstRef<winrt.HString>, skuId: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<Bool> /* GenericTypeInstSig */;
    function MoveToFrontOfDownloadQueue(productId: cxx.ConstRef<winrt.HString>, correlationVector: cxx.ConstRef<winrt.HString>): Void;
}
