package winrt.windows.ui.xaml.controls;

@:valueType
@:unreflective
@:structAccess
@:semantics(variable)
@:include("winrt/Windows.UI.Xaml.Controls.h", true)
@:native("winrt::Windows::UI::Xaml::Controls::CalendarView")
extern class CalendarView
    extends winrt.windows.ui.xaml.controls.Control
    implements winrt.windows.ui.xaml.controls.ICalendarView
    implements winrt.windows.ui.xaml.controls.ICalendarView2
{
    function new();
    overload function CalendarIdentifier(): winrt.HString;
    overload function CalendarIdentifier(value: ConstRef<winrt.HString>): Void;
    overload function DayOfWeekFormat(): winrt.HString;
    overload function DayOfWeekFormat(value: ConstRef<winrt.HString>): Void;
    overload function IsGroupLabelVisible(): Bool;
    overload function IsGroupLabelVisible(value: Bool): Void;
    overload function DisplayMode(): winrt.windows.ui.xaml.controls.CalendarViewDisplayMode;
    overload function DisplayMode(value: ConstRef<winrt.windows.ui.xaml.controls.CalendarViewDisplayMode>): Void;
    overload function FirstDayOfWeek(): winrt.windows.globalization.DayOfWeek;
    overload function FirstDayOfWeek(value: ConstRef<winrt.windows.globalization.DayOfWeek>): Void;
    overload function IsOutOfScopeEnabled(): Bool;
    overload function IsOutOfScopeEnabled(value: Bool): Void;
    overload function IsTodayHighlighted(): Bool;
    overload function IsTodayHighlighted(value: Bool): Void;
    overload function MaxDate(): winrt.windows.foundation.DateTime;
    overload function MaxDate(value: ConstRef<winrt.windows.foundation.DateTime>): Void;
    overload function MinDate(): winrt.windows.foundation.DateTime;
    overload function MinDate(value: ConstRef<winrt.windows.foundation.DateTime>): Void;
    overload function NumberOfWeeksInView(): Int32;
    overload function NumberOfWeeksInView(value: Int32): Void;
    overload function SelectedDates(): winrt.windows.foundation.collections.IVector<winrt.windows.foundation.DateTime> /* GenericTypeInstSig */;
    overload function SelectionMode(): winrt.windows.ui.xaml.controls.CalendarViewSelectionMode;
    overload function SelectionMode(value: ConstRef<winrt.windows.ui.xaml.controls.CalendarViewSelectionMode>): Void;
    overload function TemplateSettings(): winrt.windows.ui.xaml.controls.primitives.CalendarViewTemplateSettings;
    overload function FocusBorderBrush(): winrt.windows.ui.xaml.media.Brush;
    overload function FocusBorderBrush(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function SelectedHoverBorderBrush(): winrt.windows.ui.xaml.media.Brush;
    overload function SelectedHoverBorderBrush(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function SelectedPressedBorderBrush(): winrt.windows.ui.xaml.media.Brush;
    overload function SelectedPressedBorderBrush(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function SelectedBorderBrush(): winrt.windows.ui.xaml.media.Brush;
    overload function SelectedBorderBrush(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function HoverBorderBrush(): winrt.windows.ui.xaml.media.Brush;
    overload function HoverBorderBrush(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function PressedBorderBrush(): winrt.windows.ui.xaml.media.Brush;
    overload function PressedBorderBrush(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function CalendarItemBorderBrush(): winrt.windows.ui.xaml.media.Brush;
    overload function CalendarItemBorderBrush(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function OutOfScopeBackground(): winrt.windows.ui.xaml.media.Brush;
    overload function OutOfScopeBackground(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function CalendarItemBackground(): winrt.windows.ui.xaml.media.Brush;
    overload function CalendarItemBackground(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function PressedForeground(): winrt.windows.ui.xaml.media.Brush;
    overload function PressedForeground(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function TodayForeground(): winrt.windows.ui.xaml.media.Brush;
    overload function TodayForeground(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function BlackoutForeground(): winrt.windows.ui.xaml.media.Brush;
    overload function BlackoutForeground(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function SelectedForeground(): winrt.windows.ui.xaml.media.Brush;
    overload function SelectedForeground(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function OutOfScopeForeground(): winrt.windows.ui.xaml.media.Brush;
    overload function OutOfScopeForeground(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function CalendarItemForeground(): winrt.windows.ui.xaml.media.Brush;
    overload function CalendarItemForeground(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function DayItemFontFamily(): winrt.windows.ui.xaml.media.FontFamily;
    overload function DayItemFontFamily(value: ConstRef<winrt.windows.ui.xaml.media.FontFamily>): Void;
    overload function DayItemFontSize(): Float64;
    overload function DayItemFontSize(value: Float64): Void;
    overload function DayItemFontStyle(): winrt.windows.ui.text.FontStyle;
    overload function DayItemFontStyle(value: ConstRef<winrt.windows.ui.text.FontStyle>): Void;
    overload function DayItemFontWeight(): winrt.windows.ui.text.FontWeight;
    overload function DayItemFontWeight(value: ConstRef<winrt.windows.ui.text.FontWeight>): Void;
    overload function TodayFontWeight(): winrt.windows.ui.text.FontWeight;
    overload function TodayFontWeight(value: ConstRef<winrt.windows.ui.text.FontWeight>): Void;
    overload function FirstOfMonthLabelFontFamily(): winrt.windows.ui.xaml.media.FontFamily;
    overload function FirstOfMonthLabelFontFamily(value: ConstRef<winrt.windows.ui.xaml.media.FontFamily>): Void;
    overload function FirstOfMonthLabelFontSize(): Float64;
    overload function FirstOfMonthLabelFontSize(value: Float64): Void;
    overload function FirstOfMonthLabelFontStyle(): winrt.windows.ui.text.FontStyle;
    overload function FirstOfMonthLabelFontStyle(value: ConstRef<winrt.windows.ui.text.FontStyle>): Void;
    overload function FirstOfMonthLabelFontWeight(): winrt.windows.ui.text.FontWeight;
    overload function FirstOfMonthLabelFontWeight(value: ConstRef<winrt.windows.ui.text.FontWeight>): Void;
    overload function MonthYearItemFontFamily(): winrt.windows.ui.xaml.media.FontFamily;
    overload function MonthYearItemFontFamily(value: ConstRef<winrt.windows.ui.xaml.media.FontFamily>): Void;
    overload function MonthYearItemFontSize(): Float64;
    overload function MonthYearItemFontSize(value: Float64): Void;
    overload function MonthYearItemFontStyle(): winrt.windows.ui.text.FontStyle;
    overload function MonthYearItemFontStyle(value: ConstRef<winrt.windows.ui.text.FontStyle>): Void;
    overload function MonthYearItemFontWeight(): winrt.windows.ui.text.FontWeight;
    overload function MonthYearItemFontWeight(value: ConstRef<winrt.windows.ui.text.FontWeight>): Void;
    overload function FirstOfYearDecadeLabelFontFamily(): winrt.windows.ui.xaml.media.FontFamily;
    overload function FirstOfYearDecadeLabelFontFamily(value: ConstRef<winrt.windows.ui.xaml.media.FontFamily>): Void;
    overload function FirstOfYearDecadeLabelFontSize(): Float64;
    overload function FirstOfYearDecadeLabelFontSize(value: Float64): Void;
    overload function FirstOfYearDecadeLabelFontStyle(): winrt.windows.ui.text.FontStyle;
    overload function FirstOfYearDecadeLabelFontStyle(value: ConstRef<winrt.windows.ui.text.FontStyle>): Void;
    overload function FirstOfYearDecadeLabelFontWeight(): winrt.windows.ui.text.FontWeight;
    overload function FirstOfYearDecadeLabelFontWeight(value: ConstRef<winrt.windows.ui.text.FontWeight>): Void;
    overload function HorizontalDayItemAlignment(): winrt.windows.ui.xaml.HorizontalAlignment;
    overload function HorizontalDayItemAlignment(value: ConstRef<winrt.windows.ui.xaml.HorizontalAlignment>): Void;
    overload function VerticalDayItemAlignment(): winrt.windows.ui.xaml.VerticalAlignment;
    overload function VerticalDayItemAlignment(value: ConstRef<winrt.windows.ui.xaml.VerticalAlignment>): Void;
    overload function HorizontalFirstOfMonthLabelAlignment(): winrt.windows.ui.xaml.HorizontalAlignment;
    overload function HorizontalFirstOfMonthLabelAlignment(value: ConstRef<winrt.windows.ui.xaml.HorizontalAlignment>): Void;
    overload function VerticalFirstOfMonthLabelAlignment(): winrt.windows.ui.xaml.VerticalAlignment;
    overload function VerticalFirstOfMonthLabelAlignment(value: ConstRef<winrt.windows.ui.xaml.VerticalAlignment>): Void;
    overload function CalendarItemBorderThickness(): winrt.windows.ui.xaml.Thickness;
    overload function CalendarItemBorderThickness(value: ConstRef<winrt.windows.ui.xaml.Thickness>): Void;
    overload function CalendarViewDayItemStyle(): winrt.windows.ui.xaml.Style;
    overload function CalendarViewDayItemStyle(value: ConstRef<winrt.windows.ui.xaml.Style>): Void;
    overload function CalendarViewDayItemChanging(handler: ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.windows.ui.xaml.controls.CalendarView, winrt.windows.ui.xaml.controls.CalendarViewDayItemChangingEventArgs> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function CalendarViewDayItemChanging(token: ConstRef<winrt.EventToken>): Void;
    overload function SelectedDatesChanged(handler: ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.windows.ui.xaml.controls.CalendarView, winrt.windows.ui.xaml.controls.CalendarViewSelectedDatesChangedEventArgs> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function SelectedDatesChanged(token: ConstRef<winrt.EventToken>): Void;
    function SetDisplayDate(date: ConstRef<winrt.windows.foundation.DateTime>): Void;
    function SetYearDecadeDisplayDimensions(columns: Int32, rows: Int32): Void;
    overload function SelectedDisabledBorderBrush(): winrt.windows.ui.xaml.media.Brush;
    overload function SelectedDisabledBorderBrush(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function TodaySelectedInnerBorderBrush(): winrt.windows.ui.xaml.media.Brush;
    overload function TodaySelectedInnerBorderBrush(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function BlackoutStrikethroughBrush(): winrt.windows.ui.xaml.media.Brush;
    overload function BlackoutStrikethroughBrush(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function BlackoutBackground(): winrt.windows.ui.xaml.media.Brush;
    overload function BlackoutBackground(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function CalendarItemHoverBackground(): winrt.windows.ui.xaml.media.Brush;
    overload function CalendarItemHoverBackground(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function CalendarItemPressedBackground(): winrt.windows.ui.xaml.media.Brush;
    overload function CalendarItemPressedBackground(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function CalendarItemDisabledBackground(): winrt.windows.ui.xaml.media.Brush;
    overload function CalendarItemDisabledBackground(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function TodayBackground(): winrt.windows.ui.xaml.media.Brush;
    overload function TodayBackground(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function TodayBlackoutBackground(): winrt.windows.ui.xaml.media.Brush;
    overload function TodayBlackoutBackground(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function TodayHoverBackground(): winrt.windows.ui.xaml.media.Brush;
    overload function TodayHoverBackground(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function TodayPressedBackground(): winrt.windows.ui.xaml.media.Brush;
    overload function TodayPressedBackground(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function TodayDisabledBackground(): winrt.windows.ui.xaml.media.Brush;
    overload function TodayDisabledBackground(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function TodayBlackoutForeground(): winrt.windows.ui.xaml.media.Brush;
    overload function TodayBlackoutForeground(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function SelectedHoverForeground(): winrt.windows.ui.xaml.media.Brush;
    overload function SelectedHoverForeground(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function SelectedPressedForeground(): winrt.windows.ui.xaml.media.Brush;
    overload function SelectedPressedForeground(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function SelectedDisabledForeground(): winrt.windows.ui.xaml.media.Brush;
    overload function SelectedDisabledForeground(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function OutOfScopeHoverForeground(): winrt.windows.ui.xaml.media.Brush;
    overload function OutOfScopeHoverForeground(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function OutOfScopePressedForeground(): winrt.windows.ui.xaml.media.Brush;
    overload function OutOfScopePressedForeground(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function DisabledForeground(): winrt.windows.ui.xaml.media.Brush;
    overload function DisabledForeground(value: ConstRef<winrt.windows.ui.xaml.media.Brush>): Void;
    overload function DayItemMargin(): winrt.windows.ui.xaml.Thickness;
    overload function DayItemMargin(value: ConstRef<winrt.windows.ui.xaml.Thickness>): Void;
    overload function MonthYearItemMargin(): winrt.windows.ui.xaml.Thickness;
    overload function MonthYearItemMargin(value: ConstRef<winrt.windows.ui.xaml.Thickness>): Void;
    overload function FirstOfMonthLabelMargin(): winrt.windows.ui.xaml.Thickness;
    overload function FirstOfMonthLabelMargin(value: ConstRef<winrt.windows.ui.xaml.Thickness>): Void;
    overload function FirstOfYearDecadeLabelMargin(): winrt.windows.ui.xaml.Thickness;
    overload function FirstOfYearDecadeLabelMargin(value: ConstRef<winrt.windows.ui.xaml.Thickness>): Void;
    overload function CalendarItemCornerRadius(): winrt.windows.ui.xaml.CornerRadius;
    overload function CalendarItemCornerRadius(value: ConstRef<winrt.windows.ui.xaml.CornerRadius>): Void;
    overload function SelectedDisabledBorderBrushProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function TodaySelectedInnerBorderBrushProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function BlackoutStrikethroughBrushProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function BlackoutBackgroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function CalendarItemHoverBackgroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function CalendarItemPressedBackgroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function CalendarItemDisabledBackgroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function TodayBackgroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function TodayBlackoutBackgroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function TodayHoverBackgroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function TodayPressedBackgroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function TodayDisabledBackgroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function TodayBlackoutForegroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function SelectedHoverForegroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function SelectedPressedForegroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function SelectedDisabledForegroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function OutOfScopeHoverForegroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function OutOfScopePressedForegroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function DisabledForegroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function DayItemMarginProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function MonthYearItemMarginProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function FirstOfMonthLabelMarginProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function FirstOfYearDecadeLabelMarginProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function CalendarItemCornerRadiusProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function CalendarIdentifierProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function DayOfWeekFormatProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function IsGroupLabelVisibleProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function DisplayModeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function FirstDayOfWeekProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function IsOutOfScopeEnabledProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function IsTodayHighlightedProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function MaxDateProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function MinDateProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function NumberOfWeeksInViewProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function SelectedDatesProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function SelectionModeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function TemplateSettingsProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function FocusBorderBrushProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function SelectedHoverBorderBrushProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function SelectedPressedBorderBrushProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function SelectedBorderBrushProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function HoverBorderBrushProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function PressedBorderBrushProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function CalendarItemBorderBrushProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function OutOfScopeBackgroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function CalendarItemBackgroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function PressedForegroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function TodayForegroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function BlackoutForegroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function SelectedForegroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function OutOfScopeForegroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function CalendarItemForegroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function DayItemFontFamilyProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function DayItemFontSizeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function DayItemFontStyleProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function DayItemFontWeightProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function TodayFontWeightProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function FirstOfMonthLabelFontFamilyProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function FirstOfMonthLabelFontSizeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function FirstOfMonthLabelFontStyleProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function FirstOfMonthLabelFontWeightProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function MonthYearItemFontFamilyProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function MonthYearItemFontSizeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function MonthYearItemFontStyleProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function MonthYearItemFontWeightProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function FirstOfYearDecadeLabelFontFamilyProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function FirstOfYearDecadeLabelFontSizeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function FirstOfYearDecadeLabelFontStyleProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function FirstOfYearDecadeLabelFontWeightProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function HorizontalDayItemAlignmentProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function VerticalDayItemAlignmentProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function HorizontalFirstOfMonthLabelAlignmentProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function VerticalFirstOfMonthLabelAlignmentProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function CalendarItemBorderThicknessProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function CalendarViewDayItemStyleProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function CalendarIdentifierProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function DayOfWeekFormatProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function IsGroupLabelVisibleProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function DisplayModeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function FirstDayOfWeekProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function IsOutOfScopeEnabledProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function IsTodayHighlightedProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function MaxDateProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function MinDateProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function NumberOfWeeksInViewProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function SelectedDatesProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function SelectionModeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function TemplateSettingsProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function FocusBorderBrushProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function SelectedHoverBorderBrushProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function SelectedPressedBorderBrushProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function SelectedBorderBrushProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function HoverBorderBrushProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function PressedBorderBrushProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function CalendarItemBorderBrushProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function OutOfScopeBackgroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function CalendarItemBackgroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function PressedForegroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function TodayForegroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function BlackoutForegroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function SelectedForegroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function OutOfScopeForegroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function CalendarItemForegroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function DayItemFontFamilyProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function DayItemFontSizeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function DayItemFontStyleProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function DayItemFontWeightProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function TodayFontWeightProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function FirstOfMonthLabelFontFamilyProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function FirstOfMonthLabelFontSizeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function FirstOfMonthLabelFontStyleProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function FirstOfMonthLabelFontWeightProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function MonthYearItemFontFamilyProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function MonthYearItemFontSizeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function MonthYearItemFontStyleProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function MonthYearItemFontWeightProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function FirstOfYearDecadeLabelFontFamilyProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function FirstOfYearDecadeLabelFontSizeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function FirstOfYearDecadeLabelFontStyleProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function FirstOfYearDecadeLabelFontWeightProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function HorizontalDayItemAlignmentProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function VerticalDayItemAlignmentProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function HorizontalFirstOfMonthLabelAlignmentProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function VerticalFirstOfMonthLabelAlignmentProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function CalendarItemBorderThicknessProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function CalendarViewDayItemStyleProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function SelectedDisabledBorderBrushProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function TodaySelectedInnerBorderBrushProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function BlackoutStrikethroughBrushProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function BlackoutBackgroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function CalendarItemHoverBackgroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function CalendarItemPressedBackgroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function CalendarItemDisabledBackgroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function TodayBackgroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function TodayBlackoutBackgroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function TodayHoverBackgroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function TodayPressedBackgroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function TodayDisabledBackgroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function TodayBlackoutForegroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function SelectedHoverForegroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function SelectedPressedForegroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function SelectedDisabledForegroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function OutOfScopeHoverForegroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function OutOfScopePressedForegroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function DisabledForegroundProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function DayItemMarginProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function MonthYearItemMarginProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function FirstOfMonthLabelMarginProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function FirstOfYearDecadeLabelMarginProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function CalendarItemCornerRadiusProperty(): winrt.windows.ui.xaml.DependencyProperty;
}
