package winrt.windows.ui.xaml.controls;

@:valueType
@:include("winrt/Windows.UI.Xaml.Controls.h", true)
@:native("winrt::Windows::UI::Xaml::Controls::MediaElement")
extern class MediaElement
    extends winrt.windows.ui.xaml.FrameworkElement
    implements winrt.windows.ui.xaml.controls.IMediaElement
    implements winrt.windows.ui.xaml.controls.IMediaElement2
    implements winrt.windows.ui.xaml.controls.IMediaElement3
{
    function new();
    overload function PosterSource(): winrt.windows.ui.xaml.media.ImageSource;
    overload function PosterSource(value: cxx.ConstRef<winrt.windows.ui.xaml.media.ImageSource>): Void;
    overload function Source(): winrt.windows.foundation.Uri;
    overload function Source(value: cxx.ConstRef<winrt.windows.foundation.Uri>): Void;
    overload function IsMuted(): Bool;
    overload function IsMuted(value: Bool): Void;
    overload function IsAudioOnly(): Bool;
    overload function AutoPlay(): Bool;
    overload function AutoPlay(value: Bool): Void;
    overload function Volume(): cxx.num.Float64;
    overload function Volume(value: cxx.num.Float64): Void;
    overload function Balance(): cxx.num.Float64;
    overload function Balance(value: cxx.num.Float64): Void;
    overload function NaturalVideoHeight(): cxx.num.Int32;
    overload function NaturalVideoWidth(): cxx.num.Int32;
    overload function NaturalDuration(): winrt.windows.ui.xaml.Duration;
    overload function Position(): winrt.windows.foundation.TimeSpan;
    overload function Position(value: cxx.ConstRef<winrt.windows.foundation.TimeSpan>): Void;
    overload function DownloadProgress(): cxx.num.Float64;
    overload function BufferingProgress(): cxx.num.Float64;
    overload function DownloadProgressOffset(): cxx.num.Float64;
    overload function CurrentState(): winrt.windows.ui.xaml.media.MediaElementState;
    overload function Markers(): winrt.windows.ui.xaml.media.TimelineMarkerCollection;
    overload function CanSeek(): Bool;
    overload function CanPause(): Bool;
    overload function AudioStreamCount(): cxx.num.Int32;
    overload function AudioStreamIndex(): winrt.windows.foundation.IReference<cxx.num.Int32> /* GenericTypeInstSig */;
    overload function AudioStreamIndex(value: cxx.ConstRef<winrt.windows.foundation.IReference<cxx.num.Int32> /* temp_GenericTypeInstSig */>): Void;
    overload function PlaybackRate(): cxx.num.Float64;
    overload function PlaybackRate(value: cxx.num.Float64): Void;
    overload function IsLooping(): Bool;
    overload function IsLooping(value: Bool): Void;
    overload function PlayToSource(): winrt.windows.media.playto.PlayToSource;
    overload function DefaultPlaybackRate(): cxx.num.Float64;
    overload function DefaultPlaybackRate(value: cxx.num.Float64): Void;
    overload function AspectRatioWidth(): cxx.num.Int32;
    overload function AspectRatioHeight(): cxx.num.Int32;
    overload function RealTimePlayback(): Bool;
    overload function RealTimePlayback(value: Bool): Void;
    overload function AudioCategory(): winrt.windows.ui.xaml.media.AudioCategory;
    overload function AudioCategory(value: cxx.ConstRef<winrt.windows.ui.xaml.media.AudioCategory>): Void;
    overload function AudioDeviceType(): winrt.windows.ui.xaml.media.AudioDeviceType;
    overload function AudioDeviceType(value: cxx.ConstRef<winrt.windows.ui.xaml.media.AudioDeviceType>): Void;
    overload function ProtectionManager(): winrt.windows.media.protection.MediaProtectionManager;
    overload function ProtectionManager(value: cxx.ConstRef<winrt.windows.media.protection.MediaProtectionManager>): Void;
    overload function Stereo3DVideoPackingMode(): winrt.windows.ui.xaml.media.Stereo3DVideoPackingMode;
    overload function Stereo3DVideoPackingMode(value: cxx.ConstRef<winrt.windows.ui.xaml.media.Stereo3DVideoPackingMode>): Void;
    overload function Stereo3DVideoRenderMode(): winrt.windows.ui.xaml.media.Stereo3DVideoRenderMode;
    overload function Stereo3DVideoRenderMode(value: cxx.ConstRef<winrt.windows.ui.xaml.media.Stereo3DVideoRenderMode>): Void;
    overload function IsStereo3DVideo(): Bool;
    overload function MediaOpened(handler: cxx.ConstRef<winrt.windows.ui.xaml.RoutedEventHandler>): winrt.EventToken;
    @:noExcept overload function MediaOpened(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function MediaEnded(handler: cxx.ConstRef<winrt.windows.ui.xaml.RoutedEventHandler>): winrt.EventToken;
    @:noExcept overload function MediaEnded(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function MediaFailed(handler: cxx.ConstRef<winrt.windows.ui.xaml.ExceptionRoutedEventHandler>): winrt.EventToken;
    @:noExcept overload function MediaFailed(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function DownloadProgressChanged(handler: cxx.ConstRef<winrt.windows.ui.xaml.RoutedEventHandler>): winrt.EventToken;
    @:noExcept overload function DownloadProgressChanged(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function BufferingProgressChanged(handler: cxx.ConstRef<winrt.windows.ui.xaml.RoutedEventHandler>): winrt.EventToken;
    @:noExcept overload function BufferingProgressChanged(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function CurrentStateChanged(handler: cxx.ConstRef<winrt.windows.ui.xaml.RoutedEventHandler>): winrt.EventToken;
    @:noExcept overload function CurrentStateChanged(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function MarkerReached(handler: cxx.ConstRef<winrt.windows.ui.xaml.media.TimelineMarkerRoutedEventHandler>): winrt.EventToken;
    @:noExcept overload function MarkerReached(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function RateChanged(handler: cxx.ConstRef<winrt.windows.ui.xaml.media.RateChangedRoutedEventHandler>): winrt.EventToken;
    @:noExcept overload function RateChanged(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function VolumeChanged(handler: cxx.ConstRef<winrt.windows.ui.xaml.RoutedEventHandler>): winrt.EventToken;
    @:noExcept overload function VolumeChanged(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function SeekCompleted(handler: cxx.ConstRef<winrt.windows.ui.xaml.RoutedEventHandler>): winrt.EventToken;
    @:noExcept overload function SeekCompleted(token: cxx.ConstRef<winrt.EventToken>): Void;
    function Stop(): Void;
    function Play(): Void;
    function Pause(): Void;
    function CanPlayType(type: cxx.ConstRef<winrt.HString>): winrt.windows.ui.xaml.media.MediaCanPlayResponse;
    function SetSource(stream: cxx.ConstRef<winrt.windows.storage.streams.IRandomAccessStream>, mimeType: cxx.ConstRef<winrt.HString>): Void;
    function GetAudioStreamLanguage(index: cxx.ConstRef<winrt.windows.foundation.IReference<cxx.num.Int32> /* temp_GenericTypeInstSig */>): winrt.HString;
    function AddAudioEffect(effectID: cxx.ConstRef<winrt.HString>, effectOptional: Bool, effectConfiguration: cxx.ConstRef<winrt.windows.foundation.collections.IPropertySet>): Void;
    function AddVideoEffect(effectID: cxx.ConstRef<winrt.HString>, effectOptional: Bool, effectConfiguration: cxx.ConstRef<winrt.windows.foundation.collections.IPropertySet>): Void;
    function RemoveAllEffects(): Void;
    overload function ActualStereo3DVideoPackingMode(): winrt.windows.ui.xaml.media.Stereo3DVideoPackingMode;
    overload function AreTransportControlsEnabled(): Bool;
    overload function AreTransportControlsEnabled(value: Bool): Void;
    overload function Stretch(): winrt.windows.ui.xaml.media.Stretch;
    overload function Stretch(value: cxx.ConstRef<winrt.windows.ui.xaml.media.Stretch>): Void;
    overload function IsFullWindow(): Bool;
    overload function IsFullWindow(value: Bool): Void;
    function SetMediaStreamSource(source: cxx.ConstRef<winrt.windows.media.core.IMediaSource>): Void;
    overload function PlayToPreferredSourceUri(): winrt.windows.foundation.Uri;
    overload function PlayToPreferredSourceUri(value: cxx.ConstRef<winrt.windows.foundation.Uri>): Void;
    overload function TransportControls(): winrt.windows.ui.xaml.controls.MediaTransportControls;
    overload function TransportControls(value: cxx.ConstRef<winrt.windows.ui.xaml.controls.MediaTransportControls>): Void;
    overload function PartialMediaFailureDetected(handler: cxx.ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.windows.ui.xaml.controls.MediaElement, winrt.windows.ui.xaml.media.PartialMediaFailureDetectedEventArgs> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function PartialMediaFailureDetected(token: cxx.ConstRef<winrt.EventToken>): Void;
    function SetPlaybackSource(source: cxx.ConstRef<winrt.windows.media.playback.IMediaPlaybackSource>): Void;
    function GetAsCastingSource(): winrt.windows.media.casting.CastingSource;
    overload function AreTransportControlsEnabledProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function StretchProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function IsFullWindowProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function PlayToPreferredSourceUriProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function PosterSourceProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function SourceProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function IsMutedProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function IsAudioOnlyProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function AutoPlayProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function VolumeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function BalanceProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function NaturalVideoHeightProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function NaturalVideoWidthProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function NaturalDurationProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function PositionProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function DownloadProgressProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function BufferingProgressProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function DownloadProgressOffsetProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function CurrentStateProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function CanSeekProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function CanPauseProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function AudioStreamCountProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function AudioStreamIndexProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function PlaybackRateProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function IsLoopingProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function PlayToSourceProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function DefaultPlaybackRateProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function AspectRatioWidthProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function AspectRatioHeightProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function RealTimePlaybackProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function AudioCategoryProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function AudioDeviceTypeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function ProtectionManagerProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function Stereo3DVideoPackingModeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function Stereo3DVideoRenderModeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function IsStereo3DVideoProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function ActualStereo3DVideoPackingModeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function PosterSourceProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function SourceProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function IsMutedProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function IsAudioOnlyProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function AutoPlayProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function VolumeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function BalanceProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function NaturalVideoHeightProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function NaturalVideoWidthProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function NaturalDurationProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function PositionProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function DownloadProgressProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function BufferingProgressProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function DownloadProgressOffsetProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function CurrentStateProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function CanSeekProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function CanPauseProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function AudioStreamCountProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function AudioStreamIndexProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function PlaybackRateProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function IsLoopingProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function PlayToSourceProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function DefaultPlaybackRateProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function AspectRatioWidthProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function AspectRatioHeightProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function RealTimePlaybackProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function AudioCategoryProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function AudioDeviceTypeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function ProtectionManagerProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function Stereo3DVideoPackingModeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function Stereo3DVideoRenderModeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function IsStereo3DVideoProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function ActualStereo3DVideoPackingModeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function AreTransportControlsEnabledProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function StretchProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function IsFullWindowProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function PlayToPreferredSourceUriProperty(): winrt.windows.ui.xaml.DependencyProperty;
}
