package winrt.windows.ui.xaml.controls;

@:valueType
@:include("winrt/Windows.UI.Xaml.Controls.h", true)
@:native("winrt::Windows::UI::Xaml::Controls::NavigationView")
extern class NavigationView
    extends winrt.windows.ui.xaml.controls.ContentControl
    implements winrt.windows.ui.xaml.controls.INavigationView
    implements winrt.windows.ui.xaml.controls.INavigationView2
    implements winrt.windows.ui.xaml.controls.INavigationView3
{
    @:native("winrt::Windows::UI::Xaml::Controls::NavigationView")
    static overload function make(): winrt.windows.ui.xaml.controls.NavigationView;
    overload function IsPaneOpen(): Bool;
    overload function IsPaneOpen(value: Bool): Void;
    overload function CompactModeThresholdWidth(): cxx.num.Float64;
    overload function CompactModeThresholdWidth(value: cxx.num.Float64): Void;
    overload function ExpandedModeThresholdWidth(): cxx.num.Float64;
    overload function ExpandedModeThresholdWidth(value: cxx.num.Float64): Void;
    overload function PaneFooter(): winrt.windows.ui.xaml.UIElement;
    overload function PaneFooter(value: cxx.ConstRef<winrt.windows.ui.xaml.UIElement>): Void;
    overload function Header(): winrt.windows.foundation.IInspectable;
    overload function Header(value: cxx.ConstRef<winrt.windows.foundation.IInspectable>): Void;
    overload function HeaderTemplate(): winrt.windows.ui.xaml.DataTemplate;
    overload function HeaderTemplate(value: cxx.ConstRef<winrt.windows.ui.xaml.DataTemplate>): Void;
    overload function DisplayMode(): winrt.windows.ui.xaml.controls.NavigationViewDisplayMode;
    overload function IsSettingsVisible(): Bool;
    overload function IsSettingsVisible(value: Bool): Void;
    overload function IsPaneToggleButtonVisible(): Bool;
    overload function IsPaneToggleButtonVisible(value: Bool): Void;
    overload function AlwaysShowHeader(): Bool;
    overload function AlwaysShowHeader(value: Bool): Void;
    overload function CompactPaneLength(): cxx.num.Float64;
    overload function CompactPaneLength(value: cxx.num.Float64): Void;
    overload function OpenPaneLength(): cxx.num.Float64;
    overload function OpenPaneLength(value: cxx.num.Float64): Void;
    overload function PaneToggleButtonStyle(): winrt.windows.ui.xaml.Style;
    overload function PaneToggleButtonStyle(value: cxx.ConstRef<winrt.windows.ui.xaml.Style>): Void;
    overload function SelectedItem(): winrt.windows.foundation.IInspectable;
    overload function SelectedItem(value: cxx.ConstRef<winrt.windows.foundation.IInspectable>): Void;
    overload function MenuItems(): winrt.windows.foundation.collections.IVector<winrt.windows.foundation.IInspectable> /* GenericTypeInstSig */;
    overload function MenuItemsSource(): winrt.windows.foundation.IInspectable;
    overload function MenuItemsSource(value: cxx.ConstRef<winrt.windows.foundation.IInspectable>): Void;
    overload function SettingsItem(): winrt.windows.foundation.IInspectable;
    overload function AutoSuggestBox(): winrt.windows.ui.xaml.controls.AutoSuggestBox;
    overload function AutoSuggestBox(value: cxx.ConstRef<winrt.windows.ui.xaml.controls.AutoSuggestBox>): Void;
    overload function MenuItemTemplate(): winrt.windows.ui.xaml.DataTemplate;
    overload function MenuItemTemplate(value: cxx.ConstRef<winrt.windows.ui.xaml.DataTemplate>): Void;
    overload function MenuItemTemplateSelector(): winrt.windows.ui.xaml.controls.DataTemplateSelector;
    overload function MenuItemTemplateSelector(value: cxx.ConstRef<winrt.windows.ui.xaml.controls.DataTemplateSelector>): Void;
    overload function MenuItemContainerStyle(): winrt.windows.ui.xaml.Style;
    overload function MenuItemContainerStyle(value: cxx.ConstRef<winrt.windows.ui.xaml.Style>): Void;
    overload function MenuItemContainerStyleSelector(): winrt.windows.ui.xaml.controls.StyleSelector;
    overload function MenuItemContainerStyleSelector(value: cxx.ConstRef<winrt.windows.ui.xaml.controls.StyleSelector>): Void;
    function MenuItemFromContainer(container: cxx.ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.windows.foundation.IInspectable;
    function ContainerFromMenuItem(item: cxx.ConstRef<winrt.windows.foundation.IInspectable>): winrt.windows.ui.xaml.DependencyObject;
    overload function SelectionChanged(handler: cxx.ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.windows.ui.xaml.controls.NavigationView, winrt.windows.ui.xaml.controls.NavigationViewSelectionChangedEventArgs> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function SelectionChanged(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function ItemInvoked(handler: cxx.ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.windows.ui.xaml.controls.NavigationView, winrt.windows.ui.xaml.controls.NavigationViewItemInvokedEventArgs> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function ItemInvoked(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function DisplayModeChanged(handler: cxx.ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.windows.ui.xaml.controls.NavigationView, winrt.windows.ui.xaml.controls.NavigationViewDisplayModeChangedEventArgs> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function DisplayModeChanged(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function IsBackButtonVisible(): winrt.windows.ui.xaml.controls.NavigationViewBackButtonVisible;
    overload function IsBackButtonVisible(value: cxx.ConstRef<winrt.windows.ui.xaml.controls.NavigationViewBackButtonVisible>): Void;
    overload function IsBackEnabled(): Bool;
    overload function IsBackEnabled(value: Bool): Void;
    overload function PaneTitle(): winrt.HString;
    overload function PaneTitle(value: cxx.ConstRef<winrt.HString>): Void;
    overload function BackRequested(handler: cxx.ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.windows.ui.xaml.controls.NavigationView, winrt.windows.ui.xaml.controls.NavigationViewBackRequestedEventArgs> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function BackRequested(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function PaneClosed(handler: cxx.ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.windows.ui.xaml.controls.NavigationView, winrt.windows.foundation.IInspectable> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function PaneClosed(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function PaneClosing(handler: cxx.ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.windows.ui.xaml.controls.NavigationView, winrt.windows.ui.xaml.controls.NavigationViewPaneClosingEventArgs> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function PaneClosing(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function PaneOpened(handler: cxx.ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.windows.ui.xaml.controls.NavigationView, winrt.windows.foundation.IInspectable> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function PaneOpened(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function PaneOpening(handler: cxx.ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.windows.ui.xaml.controls.NavigationView, winrt.windows.foundation.IInspectable> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function PaneOpening(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function PaneDisplayMode(): winrt.windows.ui.xaml.controls.NavigationViewPaneDisplayMode;
    overload function PaneDisplayMode(value: cxx.ConstRef<winrt.windows.ui.xaml.controls.NavigationViewPaneDisplayMode>): Void;
    overload function PaneHeader(): winrt.windows.ui.xaml.UIElement;
    overload function PaneHeader(value: cxx.ConstRef<winrt.windows.ui.xaml.UIElement>): Void;
    overload function PaneCustomContent(): winrt.windows.ui.xaml.UIElement;
    overload function PaneCustomContent(value: cxx.ConstRef<winrt.windows.ui.xaml.UIElement>): Void;
    overload function ContentOverlay(): winrt.windows.ui.xaml.UIElement;
    overload function ContentOverlay(value: cxx.ConstRef<winrt.windows.ui.xaml.UIElement>): Void;
    overload function IsPaneVisible(): Bool;
    overload function IsPaneVisible(value: Bool): Void;
    overload function SelectionFollowsFocus(): winrt.windows.ui.xaml.controls.NavigationViewSelectionFollowsFocus;
    overload function SelectionFollowsFocus(value: cxx.ConstRef<winrt.windows.ui.xaml.controls.NavigationViewSelectionFollowsFocus>): Void;
    overload function TemplateSettings(): winrt.windows.ui.xaml.controls.NavigationViewTemplateSettings;
    overload function ShoulderNavigationEnabled(): winrt.windows.ui.xaml.controls.NavigationViewShoulderNavigationEnabled;
    overload function ShoulderNavigationEnabled(value: cxx.ConstRef<winrt.windows.ui.xaml.controls.NavigationViewShoulderNavigationEnabled>): Void;
    overload function OverflowLabelMode(): winrt.windows.ui.xaml.controls.NavigationViewOverflowLabelMode;
    overload function OverflowLabelMode(value: cxx.ConstRef<winrt.windows.ui.xaml.controls.NavigationViewOverflowLabelMode>): Void;
    overload function PaneDisplayModeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function PaneHeaderProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function PaneCustomContentProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function ContentOverlayProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function IsPaneVisibleProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function SelectionFollowsFocusProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function TemplateSettingsProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function ShoulderNavigationEnabledProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function OverflowLabelModeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function IsBackButtonVisibleProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function IsBackEnabledProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function PaneTitleProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function IsPaneOpenProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function CompactModeThresholdWidthProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function ExpandedModeThresholdWidthProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function PaneFooterProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function HeaderProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function HeaderTemplateProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function DisplayModeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function IsSettingsVisibleProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function IsPaneToggleButtonVisibleProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function AlwaysShowHeaderProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function CompactPaneLengthProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function OpenPaneLengthProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function PaneToggleButtonStyleProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function MenuItemsProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function MenuItemsSourceProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function SelectedItemProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function SettingsItemProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function AutoSuggestBoxProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function MenuItemTemplateProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function MenuItemTemplateSelectorProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function MenuItemContainerStyleProperty(): winrt.windows.ui.xaml.DependencyProperty;
    overload function MenuItemContainerStyleSelectorProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function IsPaneOpenProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function CompactModeThresholdWidthProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function ExpandedModeThresholdWidthProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function PaneFooterProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function HeaderProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function HeaderTemplateProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function DisplayModeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function IsSettingsVisibleProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function IsPaneToggleButtonVisibleProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function AlwaysShowHeaderProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function CompactPaneLengthProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function OpenPaneLengthProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function PaneToggleButtonStyleProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function MenuItemsProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function MenuItemsSourceProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function SelectedItemProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function SettingsItemProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function AutoSuggestBoxProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function MenuItemTemplateProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function MenuItemTemplateSelectorProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function MenuItemContainerStyleProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function MenuItemContainerStyleSelectorProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function IsBackButtonVisibleProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function IsBackEnabledProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function PaneTitleProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function PaneDisplayModeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function PaneHeaderProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function PaneCustomContentProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function ContentOverlayProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function IsPaneVisibleProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function SelectionFollowsFocusProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function TemplateSettingsProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function ShoulderNavigationEnabledProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static overload function OverflowLabelModeProperty(): winrt.windows.ui.xaml.DependencyProperty;
}
