package winrt.windows.security.authentication.identity.core;

@:valueType
@:include("winrt/Windows.Security.Authentication.Identity.Core.h", true)
@:native("winrt::Windows::Security::Authentication::Identity::Core::MicrosoftAccountMultiFactorAuthenticationManager")
extern class MicrosoftAccountMultiFactorAuthenticationManager
    implements winrt.windows.security.authentication.identity.core.IMicrosoftAccountMultiFactorAuthenticationManager
{
    function GetOneTimePassCodeAsync(userAccountId: cxx.ConstRef<winrt.HString>, codeLength: cxx.num.UInt32): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.authentication.identity.core.MicrosoftAccountMultiFactorOneTimeCodedInfo> /* GenericTypeInstSig */;
    function AddDeviceAsync(userAccountId: cxx.ConstRef<winrt.HString>, authenticationToken: cxx.ConstRef<winrt.HString>, wnsChannelId: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.authentication.identity.core.MicrosoftAccountMultiFactorServiceResponse> /* GenericTypeInstSig */;
    function RemoveDeviceAsync(userAccountId: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.authentication.identity.core.MicrosoftAccountMultiFactorServiceResponse> /* GenericTypeInstSig */;
    function UpdateWnsChannelAsync(userAccountId: cxx.ConstRef<winrt.HString>, channelUri: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.authentication.identity.core.MicrosoftAccountMultiFactorServiceResponse> /* GenericTypeInstSig */;
    function GetSessionsAsync(userAccountIdList: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.authentication.identity.core.MicrosoftAccountMultiFactorGetSessionsResult> /* GenericTypeInstSig */;
    function GetSessionsAndUnregisteredAccountsAsync(userAccountIdList: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.authentication.identity.core.MicrosoftAccountMultiFactorUnregisteredAccountsAndSessionInfo> /* GenericTypeInstSig */;
    overload function ApproveSessionAsync(sessionAuthentictionStatus: cxx.ConstRef<winrt.windows.security.authentication.identity.core.MicrosoftAccountMultiFactorSessionAuthenticationStatus>, authenticationSessionInfo: cxx.ConstRef<winrt.windows.security.authentication.identity.core.MicrosoftAccountMultiFactorSessionInfo>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.authentication.identity.core.MicrosoftAccountMultiFactorServiceResponse> /* GenericTypeInstSig */;
    overload function ApproveSessionAsync(sessionAuthentictionStatus: cxx.ConstRef<winrt.windows.security.authentication.identity.core.MicrosoftAccountMultiFactorSessionAuthenticationStatus>, userAccountId: cxx.ConstRef<winrt.HString>, sessionId: cxx.ConstRef<winrt.HString>, sessionAuthenticationType: cxx.ConstRef<winrt.windows.security.authentication.identity.core.MicrosoftAccountMultiFactorAuthenticationType>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.authentication.identity.core.MicrosoftAccountMultiFactorServiceResponse> /* GenericTypeInstSig */;
    overload function DenySessionAsync(authenticationSessionInfo: cxx.ConstRef<winrt.windows.security.authentication.identity.core.MicrosoftAccountMultiFactorSessionInfo>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.authentication.identity.core.MicrosoftAccountMultiFactorServiceResponse> /* GenericTypeInstSig */;
    overload function DenySessionAsync(userAccountId: cxx.ConstRef<winrt.HString>, sessionId: cxx.ConstRef<winrt.HString>, sessionAuthenticationType: cxx.ConstRef<winrt.windows.security.authentication.identity.core.MicrosoftAccountMultiFactorAuthenticationType>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.authentication.identity.core.MicrosoftAccountMultiFactorServiceResponse> /* GenericTypeInstSig */;
    overload function Current(): winrt.windows.security.authentication.identity.core.MicrosoftAccountMultiFactorAuthenticationManager;
    static overload function Current(): winrt.windows.security.authentication.identity.core.MicrosoftAccountMultiFactorAuthenticationManager;
}
