package winrt.microsoft.ui.xaml.controls.primitives;

@:valueType
@:unreflective
@:structAccess
@:semantics(variable)
@:include("winrt/Microsoft.UI.Xaml.Controls.Primitives.h", true)
@:native("winrt::Microsoft::UI::Xaml::Controls::Primitives::ListViewItemPresenter")
extern class ListViewItemPresenter
    extends winrt.microsoft.ui.xaml.controls.ContentPresenter
    implements winrt.microsoft.ui.xaml.controls.primitives.IListViewItemPresenter
{
    function new();
    overload function SelectionCheckMarkVisualEnabled(): Bool;
    overload function SelectionCheckMarkVisualEnabled(value: Bool): Void;
    overload function CheckHintBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function CheckHintBrush(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function CheckSelectingBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function CheckSelectingBrush(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function CheckBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function CheckBrush(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function DragBackground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function DragBackground(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function DragForeground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function DragForeground(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function FocusBorderBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function FocusBorderBrush(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function PlaceholderBackground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function PlaceholderBackground(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function PointerOverBackground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function PointerOverBackground(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function SelectedBackground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function SelectedBackground(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function SelectedForeground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function SelectedForeground(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function SelectedPointerOverBackground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function SelectedPointerOverBackground(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function SelectedPointerOverBorderBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function SelectedPointerOverBorderBrush(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function SelectedBorderThickness(): winrt.microsoft.ui.xaml.Thickness;
    overload function SelectedBorderThickness(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.Thickness>): Void;
    overload function DisabledOpacity(): #if reflaxe.cpp cxx.num. #else cpp. #end Float64;
    overload function DisabledOpacity(value: #if reflaxe.cpp cxx.num. #else cpp. #end Float64): Void;
    overload function DragOpacity(): #if reflaxe.cpp cxx.num. #else cpp. #end Float64;
    overload function DragOpacity(value: #if reflaxe.cpp cxx.num. #else cpp. #end Float64): Void;
    overload function ReorderHintOffset(): #if reflaxe.cpp cxx.num. #else cpp. #end Float64;
    overload function ReorderHintOffset(value: #if reflaxe.cpp cxx.num. #else cpp. #end Float64): Void;
    overload function ListViewItemPresenterHorizontalContentAlignment(): winrt.microsoft.ui.xaml.HorizontalAlignment;
    overload function ListViewItemPresenterHorizontalContentAlignment(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.HorizontalAlignment>): Void;
    overload function ListViewItemPresenterVerticalContentAlignment(): winrt.microsoft.ui.xaml.VerticalAlignment;
    overload function ListViewItemPresenterVerticalContentAlignment(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.VerticalAlignment>): Void;
    overload function ListViewItemPresenterPadding(): winrt.microsoft.ui.xaml.Thickness;
    overload function ListViewItemPresenterPadding(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.Thickness>): Void;
    overload function PointerOverBackgroundMargin(): winrt.microsoft.ui.xaml.Thickness;
    overload function PointerOverBackgroundMargin(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.Thickness>): Void;
    overload function ContentMargin(): winrt.microsoft.ui.xaml.Thickness;
    overload function ContentMargin(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.Thickness>): Void;
    overload function SelectedPressedBackground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function SelectedPressedBackground(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function PressedBackground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function PressedBackground(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function CheckBoxBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function CheckBoxBrush(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function FocusSecondaryBorderBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function FocusSecondaryBorderBrush(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function CheckMode(): winrt.microsoft.ui.xaml.controls.primitives.ListViewItemPresenterCheckMode;
    overload function CheckMode(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.controls.primitives.ListViewItemPresenterCheckMode>): Void;
    overload function PointerOverForeground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function PointerOverForeground(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function RevealBackground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function RevealBackground(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function RevealBorderBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function RevealBorderBrush(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function RevealBorderThickness(): winrt.microsoft.ui.xaml.Thickness;
    overload function RevealBorderThickness(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.Thickness>): Void;
    overload function RevealBackgroundShowsAboveContent(): Bool;
    overload function RevealBackgroundShowsAboveContent(value: Bool): Void;
    overload function SelectedDisabledBackground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function SelectedDisabledBackground(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function CheckPressedBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function CheckPressedBrush(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function CheckDisabledBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function CheckDisabledBrush(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function CheckBoxPointerOverBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function CheckBoxPointerOverBrush(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function CheckBoxPressedBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function CheckBoxPressedBrush(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function CheckBoxDisabledBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function CheckBoxDisabledBrush(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function CheckBoxSelectedBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function CheckBoxSelectedBrush(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function CheckBoxSelectedPointerOverBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function CheckBoxSelectedPointerOverBrush(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function CheckBoxSelectedPressedBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function CheckBoxSelectedPressedBrush(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function CheckBoxSelectedDisabledBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function CheckBoxSelectedDisabledBrush(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function CheckBoxBorderBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function CheckBoxBorderBrush(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function CheckBoxPointerOverBorderBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function CheckBoxPointerOverBorderBrush(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function CheckBoxPressedBorderBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function CheckBoxPressedBorderBrush(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function CheckBoxDisabledBorderBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function CheckBoxDisabledBorderBrush(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function CheckBoxCornerRadius(): winrt.microsoft.ui.xaml.CornerRadius;
    overload function CheckBoxCornerRadius(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.CornerRadius>): Void;
    overload function SelectionIndicatorCornerRadius(): winrt.microsoft.ui.xaml.CornerRadius;
    overload function SelectionIndicatorCornerRadius(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.CornerRadius>): Void;
    overload function SelectionIndicatorVisualEnabled(): Bool;
    overload function SelectionIndicatorVisualEnabled(value: Bool): Void;
    overload function SelectionIndicatorMode(): winrt.microsoft.ui.xaml.controls.primitives.ListViewItemPresenterSelectionIndicatorMode;
    overload function SelectionIndicatorMode(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.controls.primitives.ListViewItemPresenterSelectionIndicatorMode>): Void;
    overload function SelectionIndicatorBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function SelectionIndicatorBrush(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function SelectionIndicatorPointerOverBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function SelectionIndicatorPointerOverBrush(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function SelectionIndicatorPressedBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function SelectionIndicatorPressedBrush(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function SelectionIndicatorDisabledBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function SelectionIndicatorDisabledBrush(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function SelectedBorderBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function SelectedBorderBrush(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function SelectedPressedBorderBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function SelectedPressedBorderBrush(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function SelectedDisabledBorderBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function SelectedDisabledBorderBrush(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function SelectedInnerBorderBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function SelectedInnerBorderBrush(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function PointerOverBorderBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function PointerOverBorderBrush(value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function SelectionCheckMarkVisualEnabledProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function CheckHintBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function CheckSelectingBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function CheckBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function DragBackgroundProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function DragForegroundProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function FocusBorderBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function PlaceholderBackgroundProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function PointerOverBackgroundProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function SelectedBackgroundProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function SelectedForegroundProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function SelectedPointerOverBackgroundProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function SelectedPointerOverBorderBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function SelectedBorderThicknessProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function DisabledOpacityProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function DragOpacityProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function ReorderHintOffsetProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function ListViewItemPresenterHorizontalContentAlignmentProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function ListViewItemPresenterVerticalContentAlignmentProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function ListViewItemPresenterPaddingProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function PointerOverBackgroundMarginProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function ContentMarginProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function SelectedPressedBackgroundProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function PressedBackgroundProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function CheckBoxBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function FocusSecondaryBorderBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function CheckModeProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function PointerOverForegroundProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function RevealBackgroundProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function RevealBorderBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function RevealBorderThicknessProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function RevealBackgroundShowsAboveContentProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function SelectedDisabledBackgroundProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function CheckPressedBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function CheckDisabledBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function CheckBoxPointerOverBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function CheckBoxPressedBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function CheckBoxDisabledBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function CheckBoxSelectedBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function CheckBoxSelectedPointerOverBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function CheckBoxSelectedPressedBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function CheckBoxSelectedDisabledBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function CheckBoxBorderBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function CheckBoxPointerOverBorderBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function CheckBoxPressedBorderBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function CheckBoxDisabledBorderBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function CheckBoxCornerRadiusProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function SelectionIndicatorCornerRadiusProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function SelectionIndicatorVisualEnabledProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function SelectionIndicatorModeProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function SelectionIndicatorBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function SelectionIndicatorPointerOverBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function SelectionIndicatorPressedBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function SelectionIndicatorDisabledBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function SelectedBorderBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function SelectedPressedBorderBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function SelectedDisabledBorderBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function SelectedInnerBorderBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function PointerOverBorderBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function SelectionCheckMarkVisualEnabledProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function CheckHintBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function CheckSelectingBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function CheckBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function DragBackgroundProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function DragForegroundProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function FocusBorderBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function PlaceholderBackgroundProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function PointerOverBackgroundProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function SelectedBackgroundProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function SelectedForegroundProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function SelectedPointerOverBackgroundProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function SelectedPointerOverBorderBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function SelectedBorderThicknessProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function DisabledOpacityProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function DragOpacityProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function ReorderHintOffsetProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function ListViewItemPresenterHorizontalContentAlignmentProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function ListViewItemPresenterVerticalContentAlignmentProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function ListViewItemPresenterPaddingProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function PointerOverBackgroundMarginProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function ContentMarginProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function SelectedPressedBackgroundProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function PressedBackgroundProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function CheckBoxBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function FocusSecondaryBorderBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function CheckModeProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function PointerOverForegroundProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function RevealBackgroundProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function RevealBorderBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function RevealBorderThicknessProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function RevealBackgroundShowsAboveContentProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function SelectedDisabledBackgroundProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function CheckPressedBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function CheckDisabledBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function CheckBoxPointerOverBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function CheckBoxPressedBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function CheckBoxDisabledBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function CheckBoxSelectedBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function CheckBoxSelectedPointerOverBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function CheckBoxSelectedPressedBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function CheckBoxSelectedDisabledBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function CheckBoxBorderBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function CheckBoxPointerOverBorderBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function CheckBoxPressedBorderBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function CheckBoxDisabledBorderBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function CheckBoxCornerRadiusProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function SelectionIndicatorCornerRadiusProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function SelectionIndicatorVisualEnabledProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function SelectionIndicatorModeProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function SelectionIndicatorBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function SelectionIndicatorPointerOverBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function SelectionIndicatorPressedBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function SelectionIndicatorDisabledBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function SelectedBorderBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function SelectedPressedBorderBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function SelectedDisabledBorderBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function SelectedInnerBorderBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function PointerOverBorderBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
}
