package winrt.microsoft.ui.xaml.automation;

@:valueType
@:include("winrt/Microsoft.UI.Xaml.Automation.h", true)
@:native("winrt::Microsoft::UI::Xaml::Automation::IAutomationPropertiesStatics")
extern interface IAutomationPropertiesStatics extends winrt.windows.foundation.IInspectable
{
    overload function AcceleratorKeyProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetAcceleratorKey(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): winrt.HString;
    function SetAcceleratorKey(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>, value: cxx.ConstRef<winrt.HString>): Void;
    overload function AccessKeyProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetAccessKey(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): winrt.HString;
    function SetAccessKey(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>, value: cxx.ConstRef<winrt.HString>): Void;
    overload function AutomationIdProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetAutomationId(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): winrt.HString;
    function SetAutomationId(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>, value: cxx.ConstRef<winrt.HString>): Void;
    overload function HelpTextProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetHelpText(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): winrt.HString;
    function SetHelpText(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>, value: cxx.ConstRef<winrt.HString>): Void;
    overload function IsRequiredForFormProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetIsRequiredForForm(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): Bool;
    function SetIsRequiredForForm(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function ItemStatusProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetItemStatus(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): winrt.HString;
    function SetItemStatus(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>, value: cxx.ConstRef<winrt.HString>): Void;
    overload function ItemTypeProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetItemType(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): winrt.HString;
    function SetItemType(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>, value: cxx.ConstRef<winrt.HString>): Void;
    overload function LabeledByProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetLabeledBy(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): winrt.microsoft.ui.xaml.UIElement;
    function SetLabeledBy(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>, value: cxx.ConstRef<winrt.microsoft.ui.xaml.UIElement>): Void;
    overload function NameProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetName(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): winrt.HString;
    function SetName(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>, value: cxx.ConstRef<winrt.HString>): Void;
    overload function LiveSettingProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetLiveSetting(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): winrt.microsoft.ui.xaml.automation.peers.AutomationLiveSetting;
    function SetLiveSetting(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>, value: cxx.ConstRef<winrt.microsoft.ui.xaml.automation.peers.AutomationLiveSetting>): Void;
    overload function AccessibilityViewProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetAccessibilityView(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): winrt.microsoft.ui.xaml.automation.peers.AccessibilityView;
    function SetAccessibilityView(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>, value: cxx.ConstRef<winrt.microsoft.ui.xaml.automation.peers.AccessibilityView>): Void;
    overload function ControlledPeersProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetControlledPeers(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): winrt.windows.foundation.collections.IVector<winrt.microsoft.ui.xaml.UIElement> /* GenericTypeInstSig */;
    overload function PositionInSetProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetPositionInSet(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): cxx.num.Int32;
    function SetPositionInSet(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>, value: cxx.num.Int32): Void;
    overload function SizeOfSetProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetSizeOfSet(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): cxx.num.Int32;
    function SetSizeOfSet(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>, value: cxx.num.Int32): Void;
    overload function LevelProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetLevel(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): cxx.num.Int32;
    function SetLevel(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>, value: cxx.num.Int32): Void;
    overload function AnnotationsProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetAnnotations(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): winrt.windows.foundation.collections.IVector<winrt.microsoft.ui.xaml.automation.AutomationAnnotation> /* GenericTypeInstSig */;
    overload function LandmarkTypeProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetLandmarkType(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): winrt.microsoft.ui.xaml.automation.peers.AutomationLandmarkType;
    function SetLandmarkType(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>, value: cxx.ConstRef<winrt.microsoft.ui.xaml.automation.peers.AutomationLandmarkType>): Void;
    overload function LocalizedLandmarkTypeProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetLocalizedLandmarkType(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): winrt.HString;
    function SetLocalizedLandmarkType(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>, value: cxx.ConstRef<winrt.HString>): Void;
    overload function IsPeripheralProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetIsPeripheral(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): Bool;
    function SetIsPeripheral(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function IsDataValidForFormProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetIsDataValidForForm(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): Bool;
    function SetIsDataValidForForm(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function FullDescriptionProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetFullDescription(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): winrt.HString;
    function SetFullDescription(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>, value: cxx.ConstRef<winrt.HString>): Void;
    overload function LocalizedControlTypeProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetLocalizedControlType(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): winrt.HString;
    function SetLocalizedControlType(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>, value: cxx.ConstRef<winrt.HString>): Void;
    overload function DescribedByProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetDescribedBy(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): winrt.windows.foundation.collections.IVector<winrt.microsoft.ui.xaml.DependencyObject> /* GenericTypeInstSig */;
    overload function FlowsToProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetFlowsTo(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): winrt.windows.foundation.collections.IVector<winrt.microsoft.ui.xaml.DependencyObject> /* GenericTypeInstSig */;
    overload function FlowsFromProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetFlowsFrom(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): winrt.windows.foundation.collections.IVector<winrt.microsoft.ui.xaml.DependencyObject> /* GenericTypeInstSig */;
    overload function CultureProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetCulture(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): cxx.num.Int32;
    function SetCulture(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>, value: cxx.num.Int32): Void;
    overload function HeadingLevelProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetHeadingLevel(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): winrt.microsoft.ui.xaml.automation.peers.AutomationHeadingLevel;
    function SetHeadingLevel(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>, value: cxx.ConstRef<winrt.microsoft.ui.xaml.automation.peers.AutomationHeadingLevel>): Void;
    overload function IsDialogProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetIsDialog(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): Bool;
    function SetIsDialog(element: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>, value: Bool): Void;
}
