package winrt.windows.ui;

@:valueType
@:include("winrt/Windows.UI.h", true)
@:native("winrt::Windows::UI::Colors")
extern class Colors
    implements winrt.windows.ui.IColors
{
    overload function AliceBlue(): winrt.windows.ui.Color;
    overload function AntiqueWhite(): winrt.windows.ui.Color;
    overload function Aqua(): winrt.windows.ui.Color;
    overload function Aquamarine(): winrt.windows.ui.Color;
    overload function Azure(): winrt.windows.ui.Color;
    overload function Beige(): winrt.windows.ui.Color;
    overload function Bisque(): winrt.windows.ui.Color;
    overload function Black(): winrt.windows.ui.Color;
    overload function BlanchedAlmond(): winrt.windows.ui.Color;
    overload function Blue(): winrt.windows.ui.Color;
    overload function BlueViolet(): winrt.windows.ui.Color;
    overload function Brown(): winrt.windows.ui.Color;
    overload function BurlyWood(): winrt.windows.ui.Color;
    overload function CadetBlue(): winrt.windows.ui.Color;
    overload function Chartreuse(): winrt.windows.ui.Color;
    overload function Chocolate(): winrt.windows.ui.Color;
    overload function Coral(): winrt.windows.ui.Color;
    overload function CornflowerBlue(): winrt.windows.ui.Color;
    overload function Cornsilk(): winrt.windows.ui.Color;
    overload function Crimson(): winrt.windows.ui.Color;
    overload function Cyan(): winrt.windows.ui.Color;
    overload function DarkBlue(): winrt.windows.ui.Color;
    overload function DarkCyan(): winrt.windows.ui.Color;
    overload function DarkGoldenrod(): winrt.windows.ui.Color;
    overload function DarkGray(): winrt.windows.ui.Color;
    overload function DarkGreen(): winrt.windows.ui.Color;
    overload function DarkKhaki(): winrt.windows.ui.Color;
    overload function DarkMagenta(): winrt.windows.ui.Color;
    overload function DarkOliveGreen(): winrt.windows.ui.Color;
    overload function DarkOrange(): winrt.windows.ui.Color;
    overload function DarkOrchid(): winrt.windows.ui.Color;
    overload function DarkRed(): winrt.windows.ui.Color;
    overload function DarkSalmon(): winrt.windows.ui.Color;
    overload function DarkSeaGreen(): winrt.windows.ui.Color;
    overload function DarkSlateBlue(): winrt.windows.ui.Color;
    overload function DarkSlateGray(): winrt.windows.ui.Color;
    overload function DarkTurquoise(): winrt.windows.ui.Color;
    overload function DarkViolet(): winrt.windows.ui.Color;
    overload function DeepPink(): winrt.windows.ui.Color;
    overload function DeepSkyBlue(): winrt.windows.ui.Color;
    overload function DimGray(): winrt.windows.ui.Color;
    overload function DodgerBlue(): winrt.windows.ui.Color;
    overload function Firebrick(): winrt.windows.ui.Color;
    overload function FloralWhite(): winrt.windows.ui.Color;
    overload function ForestGreen(): winrt.windows.ui.Color;
    overload function Fuchsia(): winrt.windows.ui.Color;
    overload function Gainsboro(): winrt.windows.ui.Color;
    overload function GhostWhite(): winrt.windows.ui.Color;
    overload function Gold(): winrt.windows.ui.Color;
    overload function Goldenrod(): winrt.windows.ui.Color;
    overload function Gray(): winrt.windows.ui.Color;
    overload function Green(): winrt.windows.ui.Color;
    overload function GreenYellow(): winrt.windows.ui.Color;
    overload function Honeydew(): winrt.windows.ui.Color;
    overload function HotPink(): winrt.windows.ui.Color;
    overload function IndianRed(): winrt.windows.ui.Color;
    overload function Indigo(): winrt.windows.ui.Color;
    overload function Ivory(): winrt.windows.ui.Color;
    overload function Khaki(): winrt.windows.ui.Color;
    overload function Lavender(): winrt.windows.ui.Color;
    overload function LavenderBlush(): winrt.windows.ui.Color;
    overload function LawnGreen(): winrt.windows.ui.Color;
    overload function LemonChiffon(): winrt.windows.ui.Color;
    overload function LightBlue(): winrt.windows.ui.Color;
    overload function LightCoral(): winrt.windows.ui.Color;
    overload function LightCyan(): winrt.windows.ui.Color;
    overload function LightGoldenrodYellow(): winrt.windows.ui.Color;
    overload function LightGreen(): winrt.windows.ui.Color;
    overload function LightGray(): winrt.windows.ui.Color;
    overload function LightPink(): winrt.windows.ui.Color;
    overload function LightSalmon(): winrt.windows.ui.Color;
    overload function LightSeaGreen(): winrt.windows.ui.Color;
    overload function LightSkyBlue(): winrt.windows.ui.Color;
    overload function LightSlateGray(): winrt.windows.ui.Color;
    overload function LightSteelBlue(): winrt.windows.ui.Color;
    overload function LightYellow(): winrt.windows.ui.Color;
    overload function Lime(): winrt.windows.ui.Color;
    overload function LimeGreen(): winrt.windows.ui.Color;
    overload function Linen(): winrt.windows.ui.Color;
    overload function Magenta(): winrt.windows.ui.Color;
    overload function Maroon(): winrt.windows.ui.Color;
    overload function MediumAquamarine(): winrt.windows.ui.Color;
    overload function MediumBlue(): winrt.windows.ui.Color;
    overload function MediumOrchid(): winrt.windows.ui.Color;
    overload function MediumPurple(): winrt.windows.ui.Color;
    overload function MediumSeaGreen(): winrt.windows.ui.Color;
    overload function MediumSlateBlue(): winrt.windows.ui.Color;
    overload function MediumSpringGreen(): winrt.windows.ui.Color;
    overload function MediumTurquoise(): winrt.windows.ui.Color;
    overload function MediumVioletRed(): winrt.windows.ui.Color;
    overload function MidnightBlue(): winrt.windows.ui.Color;
    overload function MintCream(): winrt.windows.ui.Color;
    overload function MistyRose(): winrt.windows.ui.Color;
    overload function Moccasin(): winrt.windows.ui.Color;
    overload function NavajoWhite(): winrt.windows.ui.Color;
    overload function Navy(): winrt.windows.ui.Color;
    overload function OldLace(): winrt.windows.ui.Color;
    overload function Olive(): winrt.windows.ui.Color;
    overload function OliveDrab(): winrt.windows.ui.Color;
    overload function Orange(): winrt.windows.ui.Color;
    overload function OrangeRed(): winrt.windows.ui.Color;
    overload function Orchid(): winrt.windows.ui.Color;
    overload function PaleGoldenrod(): winrt.windows.ui.Color;
    overload function PaleGreen(): winrt.windows.ui.Color;
    overload function PaleTurquoise(): winrt.windows.ui.Color;
    overload function PaleVioletRed(): winrt.windows.ui.Color;
    overload function PapayaWhip(): winrt.windows.ui.Color;
    overload function PeachPuff(): winrt.windows.ui.Color;
    overload function Peru(): winrt.windows.ui.Color;
    overload function Pink(): winrt.windows.ui.Color;
    overload function Plum(): winrt.windows.ui.Color;
    overload function PowderBlue(): winrt.windows.ui.Color;
    overload function Purple(): winrt.windows.ui.Color;
    overload function Red(): winrt.windows.ui.Color;
    overload function RosyBrown(): winrt.windows.ui.Color;
    overload function RoyalBlue(): winrt.windows.ui.Color;
    overload function SaddleBrown(): winrt.windows.ui.Color;
    overload function Salmon(): winrt.windows.ui.Color;
    overload function SandyBrown(): winrt.windows.ui.Color;
    overload function SeaGreen(): winrt.windows.ui.Color;
    overload function SeaShell(): winrt.windows.ui.Color;
    overload function Sienna(): winrt.windows.ui.Color;
    overload function Silver(): winrt.windows.ui.Color;
    overload function SkyBlue(): winrt.windows.ui.Color;
    overload function SlateBlue(): winrt.windows.ui.Color;
    overload function SlateGray(): winrt.windows.ui.Color;
    overload function Snow(): winrt.windows.ui.Color;
    overload function SpringGreen(): winrt.windows.ui.Color;
    overload function SteelBlue(): winrt.windows.ui.Color;
    overload function Tan(): winrt.windows.ui.Color;
    overload function Teal(): winrt.windows.ui.Color;
    overload function Thistle(): winrt.windows.ui.Color;
    overload function Tomato(): winrt.windows.ui.Color;
    overload function Transparent(): winrt.windows.ui.Color;
    overload function Turquoise(): winrt.windows.ui.Color;
    overload function Violet(): winrt.windows.ui.Color;
    overload function Wheat(): winrt.windows.ui.Color;
    overload function White(): winrt.windows.ui.Color;
    overload function WhiteSmoke(): winrt.windows.ui.Color;
    overload function Yellow(): winrt.windows.ui.Color;
    overload function YellowGreen(): winrt.windows.ui.Color;
    static overload function AliceBlue(): winrt.windows.ui.Color;
    static overload function AntiqueWhite(): winrt.windows.ui.Color;
    static overload function Aqua(): winrt.windows.ui.Color;
    static overload function Aquamarine(): winrt.windows.ui.Color;
    static overload function Azure(): winrt.windows.ui.Color;
    static overload function Beige(): winrt.windows.ui.Color;
    static overload function Bisque(): winrt.windows.ui.Color;
    static overload function Black(): winrt.windows.ui.Color;
    static overload function BlanchedAlmond(): winrt.windows.ui.Color;
    static overload function Blue(): winrt.windows.ui.Color;
    static overload function BlueViolet(): winrt.windows.ui.Color;
    static overload function Brown(): winrt.windows.ui.Color;
    static overload function BurlyWood(): winrt.windows.ui.Color;
    static overload function CadetBlue(): winrt.windows.ui.Color;
    static overload function Chartreuse(): winrt.windows.ui.Color;
    static overload function Chocolate(): winrt.windows.ui.Color;
    static overload function Coral(): winrt.windows.ui.Color;
    static overload function CornflowerBlue(): winrt.windows.ui.Color;
    static overload function Cornsilk(): winrt.windows.ui.Color;
    static overload function Crimson(): winrt.windows.ui.Color;
    static overload function Cyan(): winrt.windows.ui.Color;
    static overload function DarkBlue(): winrt.windows.ui.Color;
    static overload function DarkCyan(): winrt.windows.ui.Color;
    static overload function DarkGoldenrod(): winrt.windows.ui.Color;
    static overload function DarkGray(): winrt.windows.ui.Color;
    static overload function DarkGreen(): winrt.windows.ui.Color;
    static overload function DarkKhaki(): winrt.windows.ui.Color;
    static overload function DarkMagenta(): winrt.windows.ui.Color;
    static overload function DarkOliveGreen(): winrt.windows.ui.Color;
    static overload function DarkOrange(): winrt.windows.ui.Color;
    static overload function DarkOrchid(): winrt.windows.ui.Color;
    static overload function DarkRed(): winrt.windows.ui.Color;
    static overload function DarkSalmon(): winrt.windows.ui.Color;
    static overload function DarkSeaGreen(): winrt.windows.ui.Color;
    static overload function DarkSlateBlue(): winrt.windows.ui.Color;
    static overload function DarkSlateGray(): winrt.windows.ui.Color;
    static overload function DarkTurquoise(): winrt.windows.ui.Color;
    static overload function DarkViolet(): winrt.windows.ui.Color;
    static overload function DeepPink(): winrt.windows.ui.Color;
    static overload function DeepSkyBlue(): winrt.windows.ui.Color;
    static overload function DimGray(): winrt.windows.ui.Color;
    static overload function DodgerBlue(): winrt.windows.ui.Color;
    static overload function Firebrick(): winrt.windows.ui.Color;
    static overload function FloralWhite(): winrt.windows.ui.Color;
    static overload function ForestGreen(): winrt.windows.ui.Color;
    static overload function Fuchsia(): winrt.windows.ui.Color;
    static overload function Gainsboro(): winrt.windows.ui.Color;
    static overload function GhostWhite(): winrt.windows.ui.Color;
    static overload function Gold(): winrt.windows.ui.Color;
    static overload function Goldenrod(): winrt.windows.ui.Color;
    static overload function Gray(): winrt.windows.ui.Color;
    static overload function Green(): winrt.windows.ui.Color;
    static overload function GreenYellow(): winrt.windows.ui.Color;
    static overload function Honeydew(): winrt.windows.ui.Color;
    static overload function HotPink(): winrt.windows.ui.Color;
    static overload function IndianRed(): winrt.windows.ui.Color;
    static overload function Indigo(): winrt.windows.ui.Color;
    static overload function Ivory(): winrt.windows.ui.Color;
    static overload function Khaki(): winrt.windows.ui.Color;
    static overload function Lavender(): winrt.windows.ui.Color;
    static overload function LavenderBlush(): winrt.windows.ui.Color;
    static overload function LawnGreen(): winrt.windows.ui.Color;
    static overload function LemonChiffon(): winrt.windows.ui.Color;
    static overload function LightBlue(): winrt.windows.ui.Color;
    static overload function LightCoral(): winrt.windows.ui.Color;
    static overload function LightCyan(): winrt.windows.ui.Color;
    static overload function LightGoldenrodYellow(): winrt.windows.ui.Color;
    static overload function LightGreen(): winrt.windows.ui.Color;
    static overload function LightGray(): winrt.windows.ui.Color;
    static overload function LightPink(): winrt.windows.ui.Color;
    static overload function LightSalmon(): winrt.windows.ui.Color;
    static overload function LightSeaGreen(): winrt.windows.ui.Color;
    static overload function LightSkyBlue(): winrt.windows.ui.Color;
    static overload function LightSlateGray(): winrt.windows.ui.Color;
    static overload function LightSteelBlue(): winrt.windows.ui.Color;
    static overload function LightYellow(): winrt.windows.ui.Color;
    static overload function Lime(): winrt.windows.ui.Color;
    static overload function LimeGreen(): winrt.windows.ui.Color;
    static overload function Linen(): winrt.windows.ui.Color;
    static overload function Magenta(): winrt.windows.ui.Color;
    static overload function Maroon(): winrt.windows.ui.Color;
    static overload function MediumAquamarine(): winrt.windows.ui.Color;
    static overload function MediumBlue(): winrt.windows.ui.Color;
    static overload function MediumOrchid(): winrt.windows.ui.Color;
    static overload function MediumPurple(): winrt.windows.ui.Color;
    static overload function MediumSeaGreen(): winrt.windows.ui.Color;
    static overload function MediumSlateBlue(): winrt.windows.ui.Color;
    static overload function MediumSpringGreen(): winrt.windows.ui.Color;
    static overload function MediumTurquoise(): winrt.windows.ui.Color;
    static overload function MediumVioletRed(): winrt.windows.ui.Color;
    static overload function MidnightBlue(): winrt.windows.ui.Color;
    static overload function MintCream(): winrt.windows.ui.Color;
    static overload function MistyRose(): winrt.windows.ui.Color;
    static overload function Moccasin(): winrt.windows.ui.Color;
    static overload function NavajoWhite(): winrt.windows.ui.Color;
    static overload function Navy(): winrt.windows.ui.Color;
    static overload function OldLace(): winrt.windows.ui.Color;
    static overload function Olive(): winrt.windows.ui.Color;
    static overload function OliveDrab(): winrt.windows.ui.Color;
    static overload function Orange(): winrt.windows.ui.Color;
    static overload function OrangeRed(): winrt.windows.ui.Color;
    static overload function Orchid(): winrt.windows.ui.Color;
    static overload function PaleGoldenrod(): winrt.windows.ui.Color;
    static overload function PaleGreen(): winrt.windows.ui.Color;
    static overload function PaleTurquoise(): winrt.windows.ui.Color;
    static overload function PaleVioletRed(): winrt.windows.ui.Color;
    static overload function PapayaWhip(): winrt.windows.ui.Color;
    static overload function PeachPuff(): winrt.windows.ui.Color;
    static overload function Peru(): winrt.windows.ui.Color;
    static overload function Pink(): winrt.windows.ui.Color;
    static overload function Plum(): winrt.windows.ui.Color;
    static overload function PowderBlue(): winrt.windows.ui.Color;
    static overload function Purple(): winrt.windows.ui.Color;
    static overload function Red(): winrt.windows.ui.Color;
    static overload function RosyBrown(): winrt.windows.ui.Color;
    static overload function RoyalBlue(): winrt.windows.ui.Color;
    static overload function SaddleBrown(): winrt.windows.ui.Color;
    static overload function Salmon(): winrt.windows.ui.Color;
    static overload function SandyBrown(): winrt.windows.ui.Color;
    static overload function SeaGreen(): winrt.windows.ui.Color;
    static overload function SeaShell(): winrt.windows.ui.Color;
    static overload function Sienna(): winrt.windows.ui.Color;
    static overload function Silver(): winrt.windows.ui.Color;
    static overload function SkyBlue(): winrt.windows.ui.Color;
    static overload function SlateBlue(): winrt.windows.ui.Color;
    static overload function SlateGray(): winrt.windows.ui.Color;
    static overload function Snow(): winrt.windows.ui.Color;
    static overload function SpringGreen(): winrt.windows.ui.Color;
    static overload function SteelBlue(): winrt.windows.ui.Color;
    static overload function Tan(): winrt.windows.ui.Color;
    static overload function Teal(): winrt.windows.ui.Color;
    static overload function Thistle(): winrt.windows.ui.Color;
    static overload function Tomato(): winrt.windows.ui.Color;
    static overload function Transparent(): winrt.windows.ui.Color;
    static overload function Turquoise(): winrt.windows.ui.Color;
    static overload function Violet(): winrt.windows.ui.Color;
    static overload function Wheat(): winrt.windows.ui.Color;
    static overload function White(): winrt.windows.ui.Color;
    static overload function WhiteSmoke(): winrt.windows.ui.Color;
    static overload function Yellow(): winrt.windows.ui.Color;
    static overload function YellowGreen(): winrt.windows.ui.Color;
}
