package winrt.windows.networking.vpn;

@:valueType
@:include("winrt/Windows.Networking.Vpn.h", true)
@:native("winrt::Windows::Networking::Vpn::IVpnChannel2")
extern interface IVpnChannel2 extends winrt.windows.foundation.IInspectable
{
    function StartWithMainTransport(assignedClientIPv4list: cxx.ConstRef<winrt.windows.foundation.collections.IVectorView<winrt.windows.networking.HostName> /* temp_GenericTypeInstSig */>, assignedClientIPv6list: cxx.ConstRef<winrt.windows.foundation.collections.IVectorView<winrt.windows.networking.HostName> /* temp_GenericTypeInstSig */>, vpnInterfaceId: cxx.ConstRef<winrt.windows.networking.vpn.VpnInterfaceId>, assignedRoutes: cxx.ConstRef<winrt.windows.networking.vpn.VpnRouteAssignment>, assignedDomainName: cxx.ConstRef<winrt.windows.networking.vpn.VpnDomainNameAssignment>, mtuSize: cxx.num.UInt32, maxFrameSize: cxx.num.UInt32, Reserved: Bool, mainOuterTunnelTransport: cxx.ConstRef<winrt.windows.foundation.IInspectable>): Void;
    function StartExistingTransports(assignedClientIPv4list: cxx.ConstRef<winrt.windows.foundation.collections.IVectorView<winrt.windows.networking.HostName> /* temp_GenericTypeInstSig */>, assignedClientIPv6list: cxx.ConstRef<winrt.windows.foundation.collections.IVectorView<winrt.windows.networking.HostName> /* temp_GenericTypeInstSig */>, vpnInterfaceId: cxx.ConstRef<winrt.windows.networking.vpn.VpnInterfaceId>, assignedRoutes: cxx.ConstRef<winrt.windows.networking.vpn.VpnRouteAssignment>, assignedDomainName: cxx.ConstRef<winrt.windows.networking.vpn.VpnDomainNameAssignment>, mtuSize: cxx.num.UInt32, maxFrameSize: cxx.num.UInt32, Reserved: Bool): Void;
    overload function ActivityStateChange(handler: cxx.ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.windows.networking.vpn.VpnChannel, winrt.windows.networking.vpn.VpnChannelActivityStateChangedArgs> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function ActivityStateChange(token: cxx.ConstRef<winrt.EventToken>): Void;
    function GetVpnSendPacketBuffer(): winrt.windows.networking.vpn.VpnPacketBuffer;
    function GetVpnReceivePacketBuffer(): winrt.windows.networking.vpn.VpnPacketBuffer;
    function RequestCustomPromptAsync(customPromptElement: cxx.ConstRef<winrt.windows.foundation.collections.IVectorView<winrt.windows.networking.vpn.IVpnCustomPromptElement> /* temp_GenericTypeInstSig */>): winrt.windows.foundation.IAsyncAction;
    overload function RequestCredentialsAsync(credType: cxx.ConstRef<winrt.windows.networking.vpn.VpnCredentialType>, credOptions: cxx.num.UInt32, certificate: cxx.ConstRef<winrt.windows.security.cryptography.certificates.Certificate>): winrt.windows.foundation.IAsyncOperation<winrt.windows.networking.vpn.VpnCredential> /* GenericTypeInstSig */;
    overload function RequestCredentialsAsync(credType: cxx.ConstRef<winrt.windows.networking.vpn.VpnCredentialType>, credOptions: cxx.num.UInt32): winrt.windows.foundation.IAsyncOperation<winrt.windows.networking.vpn.VpnCredential> /* GenericTypeInstSig */;
    overload function RequestCredentialsAsync(credType: cxx.ConstRef<winrt.windows.networking.vpn.VpnCredentialType>): winrt.windows.foundation.IAsyncOperation<winrt.windows.networking.vpn.VpnCredential> /* GenericTypeInstSig */;
    function TerminateConnection(message: cxx.ConstRef<winrt.HString>): Void;
    function StartWithTrafficFilter(assignedClientIpv4List: cxx.ConstRef<winrt.windows.foundation.collections.IVectorView<winrt.windows.networking.HostName> /* temp_GenericTypeInstSig */>, assignedClientIpv6List: cxx.ConstRef<winrt.windows.foundation.collections.IVectorView<winrt.windows.networking.HostName> /* temp_GenericTypeInstSig */>, vpnInterfaceId: cxx.ConstRef<winrt.windows.networking.vpn.VpnInterfaceId>, assignedRoutes: cxx.ConstRef<winrt.windows.networking.vpn.VpnRouteAssignment>, assignedNamespace: cxx.ConstRef<winrt.windows.networking.vpn.VpnDomainNameAssignment>, mtuSize: cxx.num.UInt32, maxFrameSize: cxx.num.UInt32, reserved: Bool, mainOuterTunnelTransport: cxx.ConstRef<winrt.windows.foundation.IInspectable>, optionalOuterTunnelTransport: cxx.ConstRef<winrt.windows.foundation.IInspectable>, assignedTrafficFilters: cxx.ConstRef<winrt.windows.networking.vpn.VpnTrafficFilterAssignment>): Void;
}
