package winrt.windows.security.isolation;

@:valueType
@:include("winrt/Windows.Security.Isolation.h", true)
@:native("winrt::Windows::Security::Isolation::IsolatedWindowsEnvironment")
extern class IsolatedWindowsEnvironment
    implements winrt.windows.security.isolation.IIsolatedWindowsEnvironment
    implements winrt.windows.security.isolation.IIsolatedWindowsEnvironment2
    implements winrt.windows.security.isolation.IIsolatedWindowsEnvironment3
    implements winrt.windows.security.isolation.IIsolatedWindowsEnvironment4
{
    overload function Id(): winrt.HString;
    overload function StartProcessSilentlyAsync(hostExePath: cxx.ConstRef<winrt.HString>, arguments: cxx.ConstRef<winrt.HString>, activator: cxx.ConstRef<winrt.windows.security.isolation.IsolatedWindowsEnvironmentActivator>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.isolation.IsolatedWindowsEnvironmentStartProcessResult> /* GenericTypeInstSig */;
    overload function StartProcessSilentlyAsync(hostExePath: cxx.ConstRef<winrt.HString>, arguments: cxx.ConstRef<winrt.HString>, activator: cxx.ConstRef<winrt.windows.security.isolation.IsolatedWindowsEnvironmentActivator>, telemetryParameters: cxx.ConstRef<winrt.windows.security.isolation.IsolatedWindowsEnvironmentTelemetryParameters>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.isolation.IsolatedWindowsEnvironmentStartProcessResult> /* GenericTypeInstSig */;
    overload function ShareFolderAsync(hostFolder: cxx.ConstRef<winrt.HString>, requestOptions: cxx.ConstRef<winrt.windows.security.isolation.IsolatedWindowsEnvironmentShareFolderRequestOptions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.isolation.IsolatedWindowsEnvironmentShareFolderResult> /* GenericTypeInstSig */;
    overload function ShareFolderAsync(hostFolder: cxx.ConstRef<winrt.HString>, requestOptions: cxx.ConstRef<winrt.windows.security.isolation.IsolatedWindowsEnvironmentShareFolderRequestOptions>, telemetryParameters: cxx.ConstRef<winrt.windows.security.isolation.IsolatedWindowsEnvironmentTelemetryParameters>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.isolation.IsolatedWindowsEnvironmentShareFolderResult> /* GenericTypeInstSig */;
    overload function LaunchFileWithUIAsync(appExePath: cxx.ConstRef<winrt.HString>, argumentsTemplate: cxx.ConstRef<winrt.HString>, filePath: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.isolation.IsolatedWindowsEnvironmentLaunchFileResult> /* GenericTypeInstSig */;
    overload function LaunchFileWithUIAsync(appExePath: cxx.ConstRef<winrt.HString>, argumentsTemplate: cxx.ConstRef<winrt.HString>, filePath: cxx.ConstRef<winrt.HString>, telemetryParameters: cxx.ConstRef<winrt.windows.security.isolation.IsolatedWindowsEnvironmentTelemetryParameters>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.isolation.IsolatedWindowsEnvironmentLaunchFileResult> /* GenericTypeInstSig */;
    overload function TerminateAsync(): winrt.windows.foundation.IAsyncAction;
    overload function TerminateAsync(telemetryParameters: cxx.ConstRef<winrt.windows.security.isolation.IsolatedWindowsEnvironmentTelemetryParameters>): winrt.windows.foundation.IAsyncAction;
    function RegisterMessageReceiver(receiverId: cxx.ConstRef<winrt.Guid>, messageReceivedCallback: cxx.ConstRef<winrt.windows.security.isolation.MessageReceivedCallback>): Void;
    function UnregisterMessageReceiver(receiverId: cxx.ConstRef<winrt.Guid>): Void;
    overload function PostMessageToReceiverAsync(receiverId: cxx.ConstRef<winrt.Guid>, message: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.foundation.IInspectable> /* temp_GenericTypeInstSig */>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.isolation.IsolatedWindowsEnvironmentPostMessageResult> /* GenericTypeInstSig */;
    overload function PostMessageToReceiverAsync(receiverId: cxx.ConstRef<winrt.Guid>, message: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.foundation.IInspectable> /* temp_GenericTypeInstSig */>, telemetryParameters: cxx.ConstRef<winrt.windows.security.isolation.IsolatedWindowsEnvironmentTelemetryParameters>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.isolation.IsolatedWindowsEnvironmentPostMessageResult> /* GenericTypeInstSig */;
    function GetUserInfo(): winrt.windows.security.isolation.IsolatedWindowsEnvironmentUserInfo;
    overload function ShareFileAsync(filePath: cxx.ConstRef<winrt.HString>, options: cxx.ConstRef<winrt.windows.security.isolation.IsolatedWindowsEnvironmentShareFileRequestOptions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.isolation.IsolatedWindowsEnvironmentShareFileResult> /* GenericTypeInstSig */;
    overload function ShareFileAsync(filePath: cxx.ConstRef<winrt.HString>, options: cxx.ConstRef<winrt.windows.security.isolation.IsolatedWindowsEnvironmentShareFileRequestOptions>, telemetryParameters: cxx.ConstRef<winrt.windows.security.isolation.IsolatedWindowsEnvironmentTelemetryParameters>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.isolation.IsolatedWindowsEnvironmentShareFileResult> /* GenericTypeInstSig */;
    function ChangePriority(Priority: cxx.ConstRef<winrt.windows.security.isolation.IsolatedWindowsEnvironmentCreationPriority>): Void;
    overload function CreateAsync(options: cxx.ConstRef<winrt.windows.security.isolation.IsolatedWindowsEnvironmentOptions>): winrt.windows.foundation.IAsyncOperationWithProgress<winrt.windows.security.isolation.IsolatedWindowsEnvironmentCreateResult, winrt.windows.security.isolation.IsolatedWindowsEnvironmentCreateProgress> /* GenericTypeInstSig */;
    overload function CreateAsync(options: cxx.ConstRef<winrt.windows.security.isolation.IsolatedWindowsEnvironmentOptions>, telemetryParameters: cxx.ConstRef<winrt.windows.security.isolation.IsolatedWindowsEnvironmentTelemetryParameters>): winrt.windows.foundation.IAsyncOperationWithProgress<winrt.windows.security.isolation.IsolatedWindowsEnvironmentCreateResult, winrt.windows.security.isolation.IsolatedWindowsEnvironmentCreateProgress> /* GenericTypeInstSig */;
    function GetById(environmentId: cxx.ConstRef<winrt.HString>): winrt.windows.security.isolation.IsolatedWindowsEnvironment;
    function FindByOwnerId(environmentOwnerId: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.collections.IVectorView<winrt.windows.security.isolation.IsolatedWindowsEnvironment> /* GenericTypeInstSig */;
    static overload function CreateAsync(options: cxx.ConstRef<winrt.windows.security.isolation.IsolatedWindowsEnvironmentOptions>): winrt.windows.foundation.IAsyncOperationWithProgress<winrt.windows.security.isolation.IsolatedWindowsEnvironmentCreateResult, winrt.windows.security.isolation.IsolatedWindowsEnvironmentCreateProgress> /* GenericTypeInstSig */;
    static overload function CreateAsync(options: cxx.ConstRef<winrt.windows.security.isolation.IsolatedWindowsEnvironmentOptions>, telemetryParameters: cxx.ConstRef<winrt.windows.security.isolation.IsolatedWindowsEnvironmentTelemetryParameters>): winrt.windows.foundation.IAsyncOperationWithProgress<winrt.windows.security.isolation.IsolatedWindowsEnvironmentCreateResult, winrt.windows.security.isolation.IsolatedWindowsEnvironmentCreateProgress> /* GenericTypeInstSig */;
    static function GetById(environmentId: cxx.ConstRef<winrt.HString>): winrt.windows.security.isolation.IsolatedWindowsEnvironment;
    static function FindByOwnerId(environmentOwnerId: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.collections.IVectorView<winrt.windows.security.isolation.IsolatedWindowsEnvironment> /* GenericTypeInstSig */;
}
