package winrt.windows.security.isolation;

@:valueType
@:unreflective
@:structAccess
@:semantics(variable)
@:include("winrt/Windows.Security.Isolation.h", true)
@:native("winrt::Windows::Security::Isolation::IsolatedWindowsEnvironment")
extern class IsolatedWindowsEnvironment
    implements winrt.windows.security.isolation.IIsolatedWindowsEnvironment
    implements winrt.windows.security.isolation.IIsolatedWindowsEnvironment2
    implements winrt.windows.security.isolation.IIsolatedWindowsEnvironment3
    implements winrt.windows.security.isolation.IIsolatedWindowsEnvironment4
{
    overload function Id(): winrt.HString;
    overload function StartProcessSilentlyAsync(hostExePath: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.HString>, arguments: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.HString>, activator: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.security.isolation.IsolatedWindowsEnvironmentActivator>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.isolation.IsolatedWindowsEnvironmentStartProcessResult> /* GenericTypeInstSig */;
    overload function StartProcessSilentlyAsync(hostExePath: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.HString>, arguments: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.HString>, activator: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.security.isolation.IsolatedWindowsEnvironmentActivator>, telemetryParameters: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.security.isolation.IsolatedWindowsEnvironmentTelemetryParameters>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.isolation.IsolatedWindowsEnvironmentStartProcessResult> /* GenericTypeInstSig */;
    overload function ShareFolderAsync(hostFolder: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.HString>, requestOptions: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.security.isolation.IsolatedWindowsEnvironmentShareFolderRequestOptions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.isolation.IsolatedWindowsEnvironmentShareFolderResult> /* GenericTypeInstSig */;
    overload function ShareFolderAsync(hostFolder: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.HString>, requestOptions: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.security.isolation.IsolatedWindowsEnvironmentShareFolderRequestOptions>, telemetryParameters: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.security.isolation.IsolatedWindowsEnvironmentTelemetryParameters>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.isolation.IsolatedWindowsEnvironmentShareFolderResult> /* GenericTypeInstSig */;
    overload function LaunchFileWithUIAsync(appExePath: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.HString>, argumentsTemplate: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.HString>, filePath: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.isolation.IsolatedWindowsEnvironmentLaunchFileResult> /* GenericTypeInstSig */;
    overload function LaunchFileWithUIAsync(appExePath: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.HString>, argumentsTemplate: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.HString>, filePath: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.HString>, telemetryParameters: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.security.isolation.IsolatedWindowsEnvironmentTelemetryParameters>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.isolation.IsolatedWindowsEnvironmentLaunchFileResult> /* GenericTypeInstSig */;
    overload function TerminateAsync(): winrt.windows.foundation.IAsyncAction;
    overload function TerminateAsync(telemetryParameters: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.security.isolation.IsolatedWindowsEnvironmentTelemetryParameters>): winrt.windows.foundation.IAsyncAction;
    function RegisterMessageReceiver(receiverId: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.Guid>, messageReceivedCallback: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.security.isolation.MessageReceivedCallback>): Void;
    function UnregisterMessageReceiver(receiverId: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.Guid>): Void;
    overload function PostMessageToReceiverAsync(receiverId: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.Guid>, message: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.foundation.collections.IIterable<winrt.windows.foundation.IInspectable> /* temp_GenericTypeInstSig */>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.isolation.IsolatedWindowsEnvironmentPostMessageResult> /* GenericTypeInstSig */;
    overload function PostMessageToReceiverAsync(receiverId: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.Guid>, message: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.foundation.collections.IIterable<winrt.windows.foundation.IInspectable> /* temp_GenericTypeInstSig */>, telemetryParameters: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.security.isolation.IsolatedWindowsEnvironmentTelemetryParameters>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.isolation.IsolatedWindowsEnvironmentPostMessageResult> /* GenericTypeInstSig */;
    function GetUserInfo(): winrt.windows.security.isolation.IsolatedWindowsEnvironmentUserInfo;
    overload function ShareFileAsync(filePath: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.HString>, options: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.security.isolation.IsolatedWindowsEnvironmentShareFileRequestOptions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.isolation.IsolatedWindowsEnvironmentShareFileResult> /* GenericTypeInstSig */;
    overload function ShareFileAsync(filePath: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.HString>, options: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.security.isolation.IsolatedWindowsEnvironmentShareFileRequestOptions>, telemetryParameters: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.security.isolation.IsolatedWindowsEnvironmentTelemetryParameters>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.isolation.IsolatedWindowsEnvironmentShareFileResult> /* GenericTypeInstSig */;
    function ChangePriority(Priority: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.security.isolation.IsolatedWindowsEnvironmentCreationPriority>): Void;
    overload function CreateAsync(options: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.security.isolation.IsolatedWindowsEnvironmentOptions>): winrt.windows.foundation.IAsyncOperationWithProgress<winrt.windows.security.isolation.IsolatedWindowsEnvironmentCreateResult, winrt.windows.security.isolation.IsolatedWindowsEnvironmentCreateProgress> /* GenericTypeInstSig */;
    overload function CreateAsync(options: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.security.isolation.IsolatedWindowsEnvironmentOptions>, telemetryParameters: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.security.isolation.IsolatedWindowsEnvironmentTelemetryParameters>): winrt.windows.foundation.IAsyncOperationWithProgress<winrt.windows.security.isolation.IsolatedWindowsEnvironmentCreateResult, winrt.windows.security.isolation.IsolatedWindowsEnvironmentCreateProgress> /* GenericTypeInstSig */;
    function GetById(environmentId: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.HString>): winrt.windows.security.isolation.IsolatedWindowsEnvironment;
    function FindByOwnerId(environmentOwnerId: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.HString>): winrt.windows.foundation.collections.IVectorView<winrt.windows.security.isolation.IsolatedWindowsEnvironment> /* GenericTypeInstSig */;
    static overload function CreateAsync(options: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.security.isolation.IsolatedWindowsEnvironmentOptions>): winrt.windows.foundation.IAsyncOperationWithProgress<winrt.windows.security.isolation.IsolatedWindowsEnvironmentCreateResult, winrt.windows.security.isolation.IsolatedWindowsEnvironmentCreateProgress> /* GenericTypeInstSig */;
    static overload function CreateAsync(options: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.security.isolation.IsolatedWindowsEnvironmentOptions>, telemetryParameters: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.security.isolation.IsolatedWindowsEnvironmentTelemetryParameters>): winrt.windows.foundation.IAsyncOperationWithProgress<winrt.windows.security.isolation.IsolatedWindowsEnvironmentCreateResult, winrt.windows.security.isolation.IsolatedWindowsEnvironmentCreateProgress> /* GenericTypeInstSig */;
    static function GetById(environmentId: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.HString>): winrt.windows.security.isolation.IsolatedWindowsEnvironment;
    static function FindByOwnerId(environmentOwnerId: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.HString>): winrt.windows.foundation.collections.IVectorView<winrt.windows.security.isolation.IsolatedWindowsEnvironment> /* GenericTypeInstSig */;
}
