package winrt.windows.devices.perception.provider;

@:include("winrt/Windows.Devices.Perception.Provider.h", true)
@:native("winrt::Windows::Devices::Perception::Provider::PerceptionFrameProviderManagerService")
extern class PerceptionFrameProviderManagerService
{
    static function RegisterFrameProviderInfo(manager: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.devices.perception.provider.IPerceptionFrameProviderManager>, frameProviderInfo: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.devices.perception.provider.PerceptionFrameProviderInfo>): Void;
    static function UnregisterFrameProviderInfo(manager: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.devices.perception.provider.IPerceptionFrameProviderManager>, frameProviderInfo: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.devices.perception.provider.PerceptionFrameProviderInfo>): Void;
    static function RegisterFaceAuthenticationGroup(manager: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.devices.perception.provider.IPerceptionFrameProviderManager>, faceAuthenticationGroup: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.devices.perception.provider.PerceptionFaceAuthenticationGroup>): Void;
    static function UnregisterFaceAuthenticationGroup(manager: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.devices.perception.provider.IPerceptionFrameProviderManager>, faceAuthenticationGroup: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.devices.perception.provider.PerceptionFaceAuthenticationGroup>): Void;
    static function RegisterControlGroup(manager: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.devices.perception.provider.IPerceptionFrameProviderManager>, controlGroup: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.devices.perception.provider.PerceptionControlGroup>): Void;
    static function UnregisterControlGroup(manager: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.devices.perception.provider.IPerceptionFrameProviderManager>, controlGroup: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.devices.perception.provider.PerceptionControlGroup>): Void;
    static function RegisterCorrelationGroup(manager: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.devices.perception.provider.IPerceptionFrameProviderManager>, correlationGroup: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.devices.perception.provider.PerceptionCorrelationGroup>): Void;
    static function UnregisterCorrelationGroup(manager: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.devices.perception.provider.IPerceptionFrameProviderManager>, correlationGroup: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.devices.perception.provider.PerceptionCorrelationGroup>): Void;
    static function UpdateAvailabilityForProvider(provider: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.devices.perception.provider.IPerceptionFrameProvider>, available: Bool): Void;
    static function PublishFrameForProvider(provider: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.devices.perception.provider.IPerceptionFrameProvider>, frame: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.devices.perception.provider.PerceptionFrame>): Void;
}
