package winrt.microsoft.ui.xaml;

@:valueType
@:include("winrt/Microsoft.UI.Xaml.h", true)
@:native("winrt::Microsoft::UI::Xaml::UIElement")
extern class UIElement
    extends winrt.microsoft.ui.xaml.DependencyObject
    implements winrt.microsoft.ui.xaml.IUIElement
    implements winrt.microsoft.ui.xaml.IUIElementProtected
    implements winrt.microsoft.ui.xaml.IUIElementOverrides
    implements winrt.microsoft.ui.composition.IAnimationObject
    implements winrt.microsoft.ui.composition.IVisualElement
    implements winrt.microsoft.ui.composition.IVisualElement2
{
    overload function DesiredSize(): winrt.windows.foundation.Size;
    overload function AllowDrop(): Bool;
    overload function AllowDrop(value: Bool): Void;
    overload function Opacity(): cxx.num.Float64;
    overload function Opacity(value: cxx.num.Float64): Void;
    overload function Clip(): winrt.microsoft.ui.xaml.media.RectangleGeometry;
    overload function Clip(value: cxx.ConstRef<winrt.microsoft.ui.xaml.media.RectangleGeometry>): Void;
    overload function RenderTransform(): winrt.microsoft.ui.xaml.media.Transform;
    overload function RenderTransform(value: cxx.ConstRef<winrt.microsoft.ui.xaml.media.Transform>): Void;
    overload function Projection(): winrt.microsoft.ui.xaml.media.Projection;
    overload function Projection(value: cxx.ConstRef<winrt.microsoft.ui.xaml.media.Projection>): Void;
    overload function Transform3D(): winrt.microsoft.ui.xaml.media.media3d.Transform3D;
    overload function Transform3D(value: cxx.ConstRef<winrt.microsoft.ui.xaml.media.media3d.Transform3D>): Void;
    overload function RenderTransformOrigin(): winrt.windows.foundation.Point;
    overload function RenderTransformOrigin(value: cxx.ConstRef<winrt.windows.foundation.Point>): Void;
    overload function IsHitTestVisible(): Bool;
    overload function IsHitTestVisible(value: Bool): Void;
    overload function Visibility(): winrt.microsoft.ui.xaml.Visibility;
    overload function Visibility(value: cxx.ConstRef<winrt.microsoft.ui.xaml.Visibility>): Void;
    overload function RenderSize(): winrt.windows.foundation.Size;
    overload function UseLayoutRounding(): Bool;
    overload function UseLayoutRounding(value: Bool): Void;
    overload function Transitions(): winrt.microsoft.ui.xaml.media.animation.TransitionCollection;
    overload function Transitions(value: cxx.ConstRef<winrt.microsoft.ui.xaml.media.animation.TransitionCollection>): Void;
    overload function CacheMode(): winrt.microsoft.ui.xaml.media.CacheMode;
    overload function CacheMode(value: cxx.ConstRef<winrt.microsoft.ui.xaml.media.CacheMode>): Void;
    overload function IsTapEnabled(): Bool;
    overload function IsTapEnabled(value: Bool): Void;
    overload function IsDoubleTapEnabled(): Bool;
    overload function IsDoubleTapEnabled(value: Bool): Void;
    overload function CanDrag(): Bool;
    overload function CanDrag(value: Bool): Void;
    overload function IsRightTapEnabled(): Bool;
    overload function IsRightTapEnabled(value: Bool): Void;
    overload function IsHoldingEnabled(): Bool;
    overload function IsHoldingEnabled(value: Bool): Void;
    overload function ManipulationMode(): winrt.microsoft.ui.xaml.input.ManipulationModes;
    overload function ManipulationMode(value: cxx.ConstRef<winrt.microsoft.ui.xaml.input.ManipulationModes>): Void;
    overload function PointerCaptures(): winrt.windows.foundation.collections.IVectorView<winrt.microsoft.ui.xaml.input.Pointer> /* GenericTypeInstSig */;
    overload function ContextFlyout(): winrt.microsoft.ui.xaml.controls.primitives.FlyoutBase;
    overload function ContextFlyout(value: cxx.ConstRef<winrt.microsoft.ui.xaml.controls.primitives.FlyoutBase>): Void;
    overload function CompositeMode(): winrt.microsoft.ui.xaml.media.ElementCompositeMode;
    overload function CompositeMode(value: cxx.ConstRef<winrt.microsoft.ui.xaml.media.ElementCompositeMode>): Void;
    overload function Lights(): winrt.windows.foundation.collections.IVector<winrt.microsoft.ui.xaml.media.XamlLight> /* GenericTypeInstSig */;
    overload function CanBeScrollAnchor(): Bool;
    overload function CanBeScrollAnchor(value: Bool): Void;
    overload function ExitDisplayModeOnAccessKeyInvoked(): Bool;
    overload function ExitDisplayModeOnAccessKeyInvoked(value: Bool): Void;
    overload function IsAccessKeyScope(): Bool;
    overload function IsAccessKeyScope(value: Bool): Void;
    overload function AccessKeyScopeOwner(): winrt.microsoft.ui.xaml.DependencyObject;
    overload function AccessKeyScopeOwner(value: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): Void;
    overload function AccessKey(): winrt.HString;
    overload function AccessKey(value: cxx.ConstRef<winrt.HString>): Void;
    overload function KeyTipPlacementMode(): winrt.microsoft.ui.xaml.input.KeyTipPlacementMode;
    overload function KeyTipPlacementMode(value: cxx.ConstRef<winrt.microsoft.ui.xaml.input.KeyTipPlacementMode>): Void;
    overload function KeyTipHorizontalOffset(): cxx.num.Float64;
    overload function KeyTipHorizontalOffset(value: cxx.num.Float64): Void;
    overload function KeyTipVerticalOffset(): cxx.num.Float64;
    overload function KeyTipVerticalOffset(value: cxx.num.Float64): Void;
    overload function KeyTipTarget(): winrt.microsoft.ui.xaml.DependencyObject;
    overload function KeyTipTarget(value: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): Void;
    overload function XYFocusKeyboardNavigation(): winrt.microsoft.ui.xaml.input.XYFocusKeyboardNavigationMode;
    overload function XYFocusKeyboardNavigation(value: cxx.ConstRef<winrt.microsoft.ui.xaml.input.XYFocusKeyboardNavigationMode>): Void;
    overload function XYFocusUpNavigationStrategy(): winrt.microsoft.ui.xaml.input.XYFocusNavigationStrategy;
    overload function XYFocusUpNavigationStrategy(value: cxx.ConstRef<winrt.microsoft.ui.xaml.input.XYFocusNavigationStrategy>): Void;
    overload function XYFocusDownNavigationStrategy(): winrt.microsoft.ui.xaml.input.XYFocusNavigationStrategy;
    overload function XYFocusDownNavigationStrategy(value: cxx.ConstRef<winrt.microsoft.ui.xaml.input.XYFocusNavigationStrategy>): Void;
    overload function XYFocusLeftNavigationStrategy(): winrt.microsoft.ui.xaml.input.XYFocusNavigationStrategy;
    overload function XYFocusLeftNavigationStrategy(value: cxx.ConstRef<winrt.microsoft.ui.xaml.input.XYFocusNavigationStrategy>): Void;
    overload function XYFocusRightNavigationStrategy(): winrt.microsoft.ui.xaml.input.XYFocusNavigationStrategy;
    overload function XYFocusRightNavigationStrategy(value: cxx.ConstRef<winrt.microsoft.ui.xaml.input.XYFocusNavigationStrategy>): Void;
    overload function KeyboardAccelerators(): winrt.windows.foundation.collections.IVector<winrt.microsoft.ui.xaml.input.KeyboardAccelerator> /* GenericTypeInstSig */;
    overload function KeyboardAcceleratorPlacementTarget(): winrt.microsoft.ui.xaml.DependencyObject;
    overload function KeyboardAcceleratorPlacementTarget(value: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): Void;
    overload function KeyboardAcceleratorPlacementMode(): winrt.microsoft.ui.xaml.input.KeyboardAcceleratorPlacementMode;
    overload function KeyboardAcceleratorPlacementMode(value: cxx.ConstRef<winrt.microsoft.ui.xaml.input.KeyboardAcceleratorPlacementMode>): Void;
    overload function HighContrastAdjustment(): winrt.microsoft.ui.xaml.ElementHighContrastAdjustment;
    overload function HighContrastAdjustment(value: cxx.ConstRef<winrt.microsoft.ui.xaml.ElementHighContrastAdjustment>): Void;
    overload function TabFocusNavigation(): winrt.microsoft.ui.xaml.input.KeyboardNavigationMode;
    overload function TabFocusNavigation(value: cxx.ConstRef<winrt.microsoft.ui.xaml.input.KeyboardNavigationMode>): Void;
    overload function OpacityTransition(): winrt.microsoft.ui.xaml.ScalarTransition;
    overload function OpacityTransition(value: cxx.ConstRef<winrt.microsoft.ui.xaml.ScalarTransition>): Void;
    overload function Translation(): winrt.windows.foundation.numerics.Vector3;
    overload function Translation(value: cxx.ConstRef<winrt.windows.foundation.numerics.Vector3>): Void;
    overload function TranslationTransition(): winrt.microsoft.ui.xaml.Vector3Transition;
    overload function TranslationTransition(value: cxx.ConstRef<winrt.microsoft.ui.xaml.Vector3Transition>): Void;
    overload function Rotation(): cxx.num.Float32;
    overload function Rotation(value: cxx.num.Float32): Void;
    overload function RotationTransition(): winrt.microsoft.ui.xaml.ScalarTransition;
    overload function RotationTransition(value: cxx.ConstRef<winrt.microsoft.ui.xaml.ScalarTransition>): Void;
    overload function Scale(): winrt.windows.foundation.numerics.Vector3;
    overload function Scale(value: cxx.ConstRef<winrt.windows.foundation.numerics.Vector3>): Void;
    overload function ScaleTransition(): winrt.microsoft.ui.xaml.Vector3Transition;
    overload function ScaleTransition(value: cxx.ConstRef<winrt.microsoft.ui.xaml.Vector3Transition>): Void;
    overload function TransformMatrix(): winrt.windows.foundation.numerics.Matrix4x4;
    overload function TransformMatrix(value: cxx.ConstRef<winrt.windows.foundation.numerics.Matrix4x4>): Void;
    overload function CenterPoint(): winrt.windows.foundation.numerics.Vector3;
    overload function CenterPoint(value: cxx.ConstRef<winrt.windows.foundation.numerics.Vector3>): Void;
    overload function RotationAxis(): winrt.windows.foundation.numerics.Vector3;
    overload function RotationAxis(value: cxx.ConstRef<winrt.windows.foundation.numerics.Vector3>): Void;
    overload function ActualOffset(): winrt.windows.foundation.numerics.Vector3;
    overload function ActualSize(): winrt.windows.foundation.numerics.Vector2;
    overload function XamlRoot(): winrt.microsoft.ui.xaml.XamlRoot;
    overload function XamlRoot(value: cxx.ConstRef<winrt.microsoft.ui.xaml.XamlRoot>): Void;
    overload function Shadow(): winrt.microsoft.ui.xaml.media.Shadow;
    overload function Shadow(value: cxx.ConstRef<winrt.microsoft.ui.xaml.media.Shadow>): Void;
    overload function RasterizationScale(): cxx.num.Float64;
    overload function RasterizationScale(value: cxx.num.Float64): Void;
    overload function FocusState(): winrt.microsoft.ui.xaml.FocusState;
    overload function UseSystemFocusVisuals(): Bool;
    overload function UseSystemFocusVisuals(value: Bool): Void;
    overload function XYFocusLeft(): winrt.microsoft.ui.xaml.DependencyObject;
    overload function XYFocusLeft(value: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): Void;
    overload function XYFocusRight(): winrt.microsoft.ui.xaml.DependencyObject;
    overload function XYFocusRight(value: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): Void;
    overload function XYFocusUp(): winrt.microsoft.ui.xaml.DependencyObject;
    overload function XYFocusUp(value: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): Void;
    overload function XYFocusDown(): winrt.microsoft.ui.xaml.DependencyObject;
    overload function XYFocusDown(value: cxx.ConstRef<winrt.microsoft.ui.xaml.DependencyObject>): Void;
    overload function IsTabStop(): Bool;
    overload function IsTabStop(value: Bool): Void;
    overload function TabIndex(): cxx.num.Int32;
    overload function TabIndex(value: cxx.num.Int32): Void;
    overload function KeyUp(handler: cxx.ConstRef<winrt.microsoft.ui.xaml.input.KeyEventHandler>): winrt.EventToken;
    @:noExcept overload function KeyUp(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function KeyDown(handler: cxx.ConstRef<winrt.microsoft.ui.xaml.input.KeyEventHandler>): winrt.EventToken;
    @:noExcept overload function KeyDown(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function GotFocus(handler: cxx.ConstRef<winrt.microsoft.ui.xaml.RoutedEventHandler>): winrt.EventToken;
    @:noExcept overload function GotFocus(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function LostFocus(handler: cxx.ConstRef<winrt.microsoft.ui.xaml.RoutedEventHandler>): winrt.EventToken;
    @:noExcept overload function LostFocus(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function DragStarting(handler: cxx.ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.microsoft.ui.xaml.UIElement, winrt.microsoft.ui.xaml.DragStartingEventArgs> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function DragStarting(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function DropCompleted(handler: cxx.ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.microsoft.ui.xaml.UIElement, winrt.microsoft.ui.xaml.DropCompletedEventArgs> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function DropCompleted(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function CharacterReceived(handler: cxx.ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.microsoft.ui.xaml.UIElement, winrt.microsoft.ui.xaml.input.CharacterReceivedRoutedEventArgs> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function CharacterReceived(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function DragEnter(handler: cxx.ConstRef<winrt.microsoft.ui.xaml.DragEventHandler>): winrt.EventToken;
    @:noExcept overload function DragEnter(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function DragLeave(handler: cxx.ConstRef<winrt.microsoft.ui.xaml.DragEventHandler>): winrt.EventToken;
    @:noExcept overload function DragLeave(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function DragOver(handler: cxx.ConstRef<winrt.microsoft.ui.xaml.DragEventHandler>): winrt.EventToken;
    @:noExcept overload function DragOver(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function Drop(handler: cxx.ConstRef<winrt.microsoft.ui.xaml.DragEventHandler>): winrt.EventToken;
    @:noExcept overload function Drop(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function PointerPressed(handler: cxx.ConstRef<winrt.microsoft.ui.xaml.input.PointerEventHandler>): winrt.EventToken;
    @:noExcept overload function PointerPressed(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function PointerMoved(handler: cxx.ConstRef<winrt.microsoft.ui.xaml.input.PointerEventHandler>): winrt.EventToken;
    @:noExcept overload function PointerMoved(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function PointerReleased(handler: cxx.ConstRef<winrt.microsoft.ui.xaml.input.PointerEventHandler>): winrt.EventToken;
    @:noExcept overload function PointerReleased(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function PointerEntered(handler: cxx.ConstRef<winrt.microsoft.ui.xaml.input.PointerEventHandler>): winrt.EventToken;
    @:noExcept overload function PointerEntered(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function PointerExited(handler: cxx.ConstRef<winrt.microsoft.ui.xaml.input.PointerEventHandler>): winrt.EventToken;
    @:noExcept overload function PointerExited(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function PointerCaptureLost(handler: cxx.ConstRef<winrt.microsoft.ui.xaml.input.PointerEventHandler>): winrt.EventToken;
    @:noExcept overload function PointerCaptureLost(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function PointerCanceled(handler: cxx.ConstRef<winrt.microsoft.ui.xaml.input.PointerEventHandler>): winrt.EventToken;
    @:noExcept overload function PointerCanceled(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function PointerWheelChanged(handler: cxx.ConstRef<winrt.microsoft.ui.xaml.input.PointerEventHandler>): winrt.EventToken;
    @:noExcept overload function PointerWheelChanged(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function Tapped(handler: cxx.ConstRef<winrt.microsoft.ui.xaml.input.TappedEventHandler>): winrt.EventToken;
    @:noExcept overload function Tapped(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function DoubleTapped(handler: cxx.ConstRef<winrt.microsoft.ui.xaml.input.DoubleTappedEventHandler>): winrt.EventToken;
    @:noExcept overload function DoubleTapped(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function Holding(handler: cxx.ConstRef<winrt.microsoft.ui.xaml.input.HoldingEventHandler>): winrt.EventToken;
    @:noExcept overload function Holding(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function ContextRequested(handler: cxx.ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.microsoft.ui.xaml.UIElement, winrt.microsoft.ui.xaml.input.ContextRequestedEventArgs> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function ContextRequested(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function ContextCanceled(handler: cxx.ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.microsoft.ui.xaml.UIElement, winrt.microsoft.ui.xaml.RoutedEventArgs> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function ContextCanceled(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function RightTapped(handler: cxx.ConstRef<winrt.microsoft.ui.xaml.input.RightTappedEventHandler>): winrt.EventToken;
    @:noExcept overload function RightTapped(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function ManipulationStarting(handler: cxx.ConstRef<winrt.microsoft.ui.xaml.input.ManipulationStartingEventHandler>): winrt.EventToken;
    @:noExcept overload function ManipulationStarting(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function ManipulationInertiaStarting(handler: cxx.ConstRef<winrt.microsoft.ui.xaml.input.ManipulationInertiaStartingEventHandler>): winrt.EventToken;
    @:noExcept overload function ManipulationInertiaStarting(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function ManipulationStarted(handler: cxx.ConstRef<winrt.microsoft.ui.xaml.input.ManipulationStartedEventHandler>): winrt.EventToken;
    @:noExcept overload function ManipulationStarted(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function ManipulationDelta(handler: cxx.ConstRef<winrt.microsoft.ui.xaml.input.ManipulationDeltaEventHandler>): winrt.EventToken;
    @:noExcept overload function ManipulationDelta(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function ManipulationCompleted(handler: cxx.ConstRef<winrt.microsoft.ui.xaml.input.ManipulationCompletedEventHandler>): winrt.EventToken;
    @:noExcept overload function ManipulationCompleted(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function AccessKeyDisplayRequested(handler: cxx.ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.microsoft.ui.xaml.UIElement, winrt.microsoft.ui.xaml.input.AccessKeyDisplayRequestedEventArgs> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function AccessKeyDisplayRequested(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function AccessKeyDisplayDismissed(handler: cxx.ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.microsoft.ui.xaml.UIElement, winrt.microsoft.ui.xaml.input.AccessKeyDisplayDismissedEventArgs> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function AccessKeyDisplayDismissed(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function AccessKeyInvoked(handler: cxx.ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.microsoft.ui.xaml.UIElement, winrt.microsoft.ui.xaml.input.AccessKeyInvokedEventArgs> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function AccessKeyInvoked(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function ProcessKeyboardAccelerators(handler: cxx.ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.microsoft.ui.xaml.UIElement, winrt.microsoft.ui.xaml.input.ProcessKeyboardAcceleratorEventArgs> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function ProcessKeyboardAccelerators(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function GettingFocus(handler: cxx.ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.microsoft.ui.xaml.UIElement, winrt.microsoft.ui.xaml.input.GettingFocusEventArgs> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function GettingFocus(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function LosingFocus(handler: cxx.ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.microsoft.ui.xaml.UIElement, winrt.microsoft.ui.xaml.input.LosingFocusEventArgs> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function LosingFocus(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function NoFocusCandidateFound(handler: cxx.ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.microsoft.ui.xaml.UIElement, winrt.microsoft.ui.xaml.input.NoFocusCandidateFoundEventArgs> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function NoFocusCandidateFound(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function PreviewKeyDown(handler: cxx.ConstRef<winrt.microsoft.ui.xaml.input.KeyEventHandler>): winrt.EventToken;
    @:noExcept overload function PreviewKeyDown(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function PreviewKeyUp(handler: cxx.ConstRef<winrt.microsoft.ui.xaml.input.KeyEventHandler>): winrt.EventToken;
    @:noExcept overload function PreviewKeyUp(token: cxx.ConstRef<winrt.EventToken>): Void;
    overload function BringIntoViewRequested(handler: cxx.ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.microsoft.ui.xaml.UIElement, winrt.microsoft.ui.xaml.BringIntoViewRequestedEventArgs> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function BringIntoViewRequested(token: cxx.ConstRef<winrt.EventToken>): Void;
    function Measure(availableSize: cxx.ConstRef<winrt.windows.foundation.Size>): Void;
    function Arrange(finalRect: cxx.ConstRef<winrt.windows.foundation.Rect>): Void;
    function CapturePointer(value: cxx.ConstRef<winrt.microsoft.ui.xaml.input.Pointer>): Bool;
    function ReleasePointerCapture(value: cxx.ConstRef<winrt.microsoft.ui.xaml.input.Pointer>): Void;
    function ReleasePointerCaptures(): Void;
    function AddHandler(routedEvent: cxx.ConstRef<winrt.microsoft.ui.xaml.RoutedEvent>, handler: cxx.ConstRef<winrt.windows.foundation.IInspectable>, handledEventsToo: Bool): Void;
    function RemoveHandler(routedEvent: cxx.ConstRef<winrt.microsoft.ui.xaml.RoutedEvent>, handler: cxx.ConstRef<winrt.windows.foundation.IInspectable>): Void;
    function TransformToVisual(visual: cxx.ConstRef<winrt.microsoft.ui.xaml.UIElement>): winrt.microsoft.ui.xaml.media.GeneralTransform;
    function InvalidateMeasure(): Void;
    function InvalidateArrange(): Void;
    function UpdateLayout(): Void;
    function CancelDirectManipulations(): Bool;
    function StartDragAsync(pointerPoint: cxx.ConstRef<winrt.microsoft.ui.input.PointerPoint>): winrt.windows.foundation.IAsyncOperation<winrt.windows.applicationmodel.datatransfer.DataPackageOperation> /* GenericTypeInstSig */;
    overload function StartBringIntoView(): Void;
    overload function StartBringIntoView(options: cxx.ConstRef<winrt.microsoft.ui.xaml.BringIntoViewOptions>): Void;
    function TryInvokeKeyboardAccelerator(args: cxx.ConstRef<winrt.microsoft.ui.xaml.input.ProcessKeyboardAcceleratorEventArgs>): Void;
    function Focus(value: cxx.ConstRef<winrt.microsoft.ui.xaml.FocusState>): Bool;
    function StartAnimation(animation: cxx.ConstRef<winrt.microsoft.ui.composition.ICompositionAnimationBase>): Void;
    function StopAnimation(animation: cxx.ConstRef<winrt.microsoft.ui.composition.ICompositionAnimationBase>): Void;
    overload function ProtectedCursor(): winrt.microsoft.ui.input.InputCursor;
    overload function ProtectedCursor(value: cxx.ConstRef<winrt.microsoft.ui.input.InputCursor>): Void;
    function OnCreateAutomationPeer(): winrt.microsoft.ui.xaml.automation.peers.AutomationPeer;
    function OnDisconnectVisualChildren(): Void;
    function FindSubElementsForTouchTargeting(point: cxx.ConstRef<winrt.windows.foundation.Point>, boundingRect: cxx.ConstRef<winrt.windows.foundation.Rect>): winrt.windows.foundation.collections.IIterable<winrt.windows.foundation.collections.IIterable<winrt.windows.foundation.Point> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    function GetChildrenInTabFocusOrder(): winrt.windows.foundation.collections.IIterable<winrt.microsoft.ui.xaml.DependencyObject> /* GenericTypeInstSig */;
    function OnKeyboardAcceleratorInvoked(args: cxx.ConstRef<winrt.microsoft.ui.xaml.input.KeyboardAcceleratorInvokedEventArgs>): Void;
    function OnProcessKeyboardAccelerators(args: cxx.ConstRef<winrt.microsoft.ui.xaml.input.ProcessKeyboardAcceleratorEventArgs>): Void;
    function OnBringIntoViewRequested(e: cxx.ConstRef<winrt.microsoft.ui.xaml.BringIntoViewRequestedEventArgs>): Void;
    function PopulatePropertyInfoOverride(propertyName: cxx.ConstRef<winrt.HString>, animationPropertyInfo: cxx.ConstRef<winrt.microsoft.ui.composition.AnimationPropertyInfo>): Void;
    function PopulatePropertyInfo(propertyName: cxx.ConstRef<winrt.HString>, propertyInfo: cxx.ConstRef<winrt.microsoft.ui.composition.AnimationPropertyInfo>): Void;
    function GetVisualInternal(): winrt.microsoft.ui.composition.Visual;
    overload function KeyDownEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    overload function KeyUpEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    overload function PointerEnteredEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    overload function PointerPressedEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    overload function PointerMovedEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    overload function PointerReleasedEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    overload function PointerExitedEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    overload function PointerCaptureLostEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    overload function PointerCanceledEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    overload function PointerWheelChangedEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    overload function TappedEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    overload function DoubleTappedEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    overload function HoldingEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    overload function RightTappedEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    overload function ManipulationStartingEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    overload function ManipulationInertiaStartingEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    overload function ManipulationStartedEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    overload function ManipulationDeltaEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    overload function ManipulationCompletedEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    overload function DragEnterEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    overload function DragLeaveEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    overload function DragOverEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    overload function DropEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    overload function GettingFocusEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    overload function LosingFocusEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    overload function NoFocusCandidateFoundEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    overload function PreviewKeyDownEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    overload function CharacterReceivedEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    overload function PreviewKeyUpEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    overload function BringIntoViewRequestedEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    overload function ContextRequestedEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    overload function AllowDropProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function OpacityProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function ClipProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function RenderTransformProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function ProjectionProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function Transform3DProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function RenderTransformOriginProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function IsHitTestVisibleProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function VisibilityProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function UseLayoutRoundingProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function TransitionsProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function CacheModeProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function IsTapEnabledProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function IsDoubleTapEnabledProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function CanDragProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function IsRightTapEnabledProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function IsHoldingEnabledProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function ManipulationModeProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function PointerCapturesProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function ContextFlyoutProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function CompositeModeProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function LightsProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function CanBeScrollAnchorProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function ExitDisplayModeOnAccessKeyInvokedProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function IsAccessKeyScopeProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function AccessKeyScopeOwnerProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function AccessKeyProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function KeyTipPlacementModeProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function KeyTipHorizontalOffsetProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function KeyTipVerticalOffsetProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function KeyTipTargetProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function XYFocusKeyboardNavigationProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function XYFocusUpNavigationStrategyProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function XYFocusDownNavigationStrategyProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function XYFocusLeftNavigationStrategyProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function XYFocusRightNavigationStrategyProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function KeyboardAcceleratorPlacementTargetProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function KeyboardAcceleratorPlacementModeProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function HighContrastAdjustmentProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function TabFocusNavigationProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function ShadowProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function FocusStateProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function UseSystemFocusVisualsProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function XYFocusLeftProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function XYFocusRightProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function XYFocusUpProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function XYFocusDownProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function IsTabStopProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function TabIndexProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function TryStartDirectManipulation(value: cxx.ConstRef<winrt.microsoft.ui.xaml.input.Pointer>): Bool;
    function RegisterAsScrollPort(element: cxx.ConstRef<winrt.microsoft.ui.xaml.UIElement>): Void;
    static overload function KeyDownEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    static overload function KeyUpEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    static overload function PointerEnteredEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    static overload function PointerPressedEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    static overload function PointerMovedEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    static overload function PointerReleasedEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    static overload function PointerExitedEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    static overload function PointerCaptureLostEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    static overload function PointerCanceledEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    static overload function PointerWheelChangedEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    static overload function TappedEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    static overload function DoubleTappedEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    static overload function HoldingEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    static overload function RightTappedEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    static overload function ManipulationStartingEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    static overload function ManipulationInertiaStartingEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    static overload function ManipulationStartedEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    static overload function ManipulationDeltaEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    static overload function ManipulationCompletedEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    static overload function DragEnterEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    static overload function DragLeaveEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    static overload function DragOverEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    static overload function DropEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    static overload function GettingFocusEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    static overload function LosingFocusEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    static overload function NoFocusCandidateFoundEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    static overload function PreviewKeyDownEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    static overload function CharacterReceivedEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    static overload function PreviewKeyUpEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    static overload function BringIntoViewRequestedEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    static overload function ContextRequestedEvent(): winrt.microsoft.ui.xaml.RoutedEvent;
    static overload function AllowDropProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function OpacityProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function ClipProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function RenderTransformProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function ProjectionProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function Transform3DProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function RenderTransformOriginProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function IsHitTestVisibleProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function VisibilityProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function UseLayoutRoundingProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function TransitionsProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function CacheModeProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function IsTapEnabledProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function IsDoubleTapEnabledProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function CanDragProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function IsRightTapEnabledProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function IsHoldingEnabledProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function ManipulationModeProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function PointerCapturesProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function ContextFlyoutProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function CompositeModeProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function LightsProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function CanBeScrollAnchorProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function ExitDisplayModeOnAccessKeyInvokedProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function IsAccessKeyScopeProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function AccessKeyScopeOwnerProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function AccessKeyProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function KeyTipPlacementModeProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function KeyTipHorizontalOffsetProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function KeyTipVerticalOffsetProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function KeyTipTargetProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function XYFocusKeyboardNavigationProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function XYFocusUpNavigationStrategyProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function XYFocusDownNavigationStrategyProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function XYFocusLeftNavigationStrategyProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function XYFocusRightNavigationStrategyProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function KeyboardAcceleratorPlacementTargetProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function KeyboardAcceleratorPlacementModeProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function HighContrastAdjustmentProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function TabFocusNavigationProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function ShadowProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function FocusStateProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function UseSystemFocusVisualsProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function XYFocusLeftProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function XYFocusRightProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function XYFocusUpProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function XYFocusDownProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function IsTabStopProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function TabIndexProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static function TryStartDirectManipulation(value: cxx.ConstRef<winrt.microsoft.ui.xaml.input.Pointer>): Bool;
    static function RegisterAsScrollPort(element: cxx.ConstRef<winrt.microsoft.ui.xaml.UIElement>): Void;
}
