package winrt.windows.ui.xaml.automation;

@:valueType
@:unreflective
@:structAccess
@:semantics(variable)
@:include("winrt/Windows.UI.Xaml.Automation.h", true)
@:native("winrt::Windows::UI::Xaml::Automation::AutomationProperties")
extern class AutomationProperties
    implements winrt.windows.ui.xaml.automation.IAutomationProperties
{
    overload function AutomationControlTypeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetAutomationControlType(element: ConstRef<winrt.windows.ui.xaml.UIElement>): winrt.windows.ui.xaml.automation.peers.AutomationControlType;
    function SetAutomationControlType(element: ConstRef<winrt.windows.ui.xaml.UIElement>, value: ConstRef<winrt.windows.ui.xaml.automation.peers.AutomationControlType>): Void;
    overload function IsDialogProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetIsDialog(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetIsDialog(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function HeadingLevelProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetHeadingLevel(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.windows.ui.xaml.automation.peers.AutomationHeadingLevel;
    function SetHeadingLevel(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.windows.ui.xaml.automation.peers.AutomationHeadingLevel>): Void;
    overload function CultureProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetCulture(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Int32;
    function SetCulture(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Int32): Void;
    overload function IsPeripheralProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetIsPeripheral(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetIsPeripheral(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function IsDataValidForFormProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetIsDataValidForForm(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetIsDataValidForForm(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function FullDescriptionProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetFullDescription(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.HString;
    function SetFullDescription(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.HString>): Void;
    overload function LocalizedControlTypeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetLocalizedControlType(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.HString;
    function SetLocalizedControlType(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.HString>): Void;
    overload function DescribedByProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetDescribedBy(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.windows.foundation.collections.IVector<winrt.windows.ui.xaml.DependencyObject> /* GenericTypeInstSig */;
    overload function FlowsToProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetFlowsTo(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.windows.foundation.collections.IVector<winrt.windows.ui.xaml.DependencyObject> /* GenericTypeInstSig */;
    overload function FlowsFromProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetFlowsFrom(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.windows.foundation.collections.IVector<winrt.windows.ui.xaml.DependencyObject> /* GenericTypeInstSig */;
    overload function LandmarkTypeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetLandmarkType(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.windows.ui.xaml.automation.peers.AutomationLandmarkType;
    function SetLandmarkType(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.windows.ui.xaml.automation.peers.AutomationLandmarkType>): Void;
    overload function LocalizedLandmarkTypeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetLocalizedLandmarkType(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.HString;
    function SetLocalizedLandmarkType(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.HString>): Void;
    overload function PositionInSetProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetPositionInSet(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Int32;
    function SetPositionInSet(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Int32): Void;
    overload function SizeOfSetProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetSizeOfSet(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Int32;
    function SetSizeOfSet(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Int32): Void;
    overload function LevelProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetLevel(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Int32;
    function SetLevel(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Int32): Void;
    overload function AnnotationsProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetAnnotations(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.windows.foundation.collections.IVector<winrt.windows.ui.xaml.automation.AutomationAnnotation> /* GenericTypeInstSig */;
    overload function AccessibilityViewProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetAccessibilityView(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.windows.ui.xaml.automation.peers.AccessibilityView;
    function SetAccessibilityView(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.windows.ui.xaml.automation.peers.AccessibilityView>): Void;
    overload function ControlledPeersProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetControlledPeers(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.windows.foundation.collections.IVector<winrt.windows.ui.xaml.UIElement> /* GenericTypeInstSig */;
    overload function AcceleratorKeyProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetAcceleratorKey(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.HString;
    function SetAcceleratorKey(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.HString>): Void;
    overload function AccessKeyProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetAccessKey(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.HString;
    function SetAccessKey(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.HString>): Void;
    overload function AutomationIdProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetAutomationId(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.HString;
    function SetAutomationId(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.HString>): Void;
    overload function HelpTextProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetHelpText(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.HString;
    function SetHelpText(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.HString>): Void;
    overload function IsRequiredForFormProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetIsRequiredForForm(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetIsRequiredForForm(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function ItemStatusProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetItemStatus(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.HString;
    function SetItemStatus(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.HString>): Void;
    overload function ItemTypeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetItemType(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.HString;
    function SetItemType(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.HString>): Void;
    overload function LabeledByProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetLabeledBy(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.windows.ui.xaml.UIElement;
    function SetLabeledBy(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.windows.ui.xaml.UIElement>): Void;
    overload function NameProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetName(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.HString;
    function SetName(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.HString>): Void;
    overload function LiveSettingProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetLiveSetting(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.windows.ui.xaml.automation.peers.AutomationLiveSetting;
    function SetLiveSetting(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.windows.ui.xaml.automation.peers.AutomationLiveSetting>): Void;
    static overload function AcceleratorKeyProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static function GetAcceleratorKey(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.HString;
    static function SetAcceleratorKey(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.HString>): Void;
    static overload function AccessKeyProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static function GetAccessKey(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.HString;
    static function SetAccessKey(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.HString>): Void;
    static overload function AutomationIdProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static function GetAutomationId(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.HString;
    static function SetAutomationId(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.HString>): Void;
    static overload function HelpTextProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static function GetHelpText(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.HString;
    static function SetHelpText(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.HString>): Void;
    static overload function IsRequiredForFormProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static function GetIsRequiredForForm(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    static function SetIsRequiredForForm(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    static overload function ItemStatusProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static function GetItemStatus(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.HString;
    static function SetItemStatus(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.HString>): Void;
    static overload function ItemTypeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static function GetItemType(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.HString;
    static function SetItemType(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.HString>): Void;
    static overload function LabeledByProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static function GetLabeledBy(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.windows.ui.xaml.UIElement;
    static function SetLabeledBy(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.windows.ui.xaml.UIElement>): Void;
    static overload function NameProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static function GetName(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.HString;
    static function SetName(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.HString>): Void;
    static overload function LiveSettingProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static function GetLiveSetting(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.windows.ui.xaml.automation.peers.AutomationLiveSetting;
    static function SetLiveSetting(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.windows.ui.xaml.automation.peers.AutomationLiveSetting>): Void;
    static overload function AccessibilityViewProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static function GetAccessibilityView(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.windows.ui.xaml.automation.peers.AccessibilityView;
    static function SetAccessibilityView(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.windows.ui.xaml.automation.peers.AccessibilityView>): Void;
    static overload function ControlledPeersProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static function GetControlledPeers(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.windows.foundation.collections.IVector<winrt.windows.ui.xaml.UIElement> /* GenericTypeInstSig */;
    static overload function PositionInSetProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static function GetPositionInSet(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Int32;
    static function SetPositionInSet(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Int32): Void;
    static overload function SizeOfSetProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static function GetSizeOfSet(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Int32;
    static function SetSizeOfSet(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Int32): Void;
    static overload function LevelProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static function GetLevel(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Int32;
    static function SetLevel(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Int32): Void;
    static overload function AnnotationsProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static function GetAnnotations(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.windows.foundation.collections.IVector<winrt.windows.ui.xaml.automation.AutomationAnnotation> /* GenericTypeInstSig */;
    static overload function LandmarkTypeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static function GetLandmarkType(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.windows.ui.xaml.automation.peers.AutomationLandmarkType;
    static function SetLandmarkType(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.windows.ui.xaml.automation.peers.AutomationLandmarkType>): Void;
    static overload function LocalizedLandmarkTypeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static function GetLocalizedLandmarkType(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.HString;
    static function SetLocalizedLandmarkType(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.HString>): Void;
    static overload function IsPeripheralProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static function GetIsPeripheral(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    static function SetIsPeripheral(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    static overload function IsDataValidForFormProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static function GetIsDataValidForForm(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    static function SetIsDataValidForForm(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    static overload function FullDescriptionProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static function GetFullDescription(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.HString;
    static function SetFullDescription(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.HString>): Void;
    static overload function LocalizedControlTypeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static function GetLocalizedControlType(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.HString;
    static function SetLocalizedControlType(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.HString>): Void;
    static overload function DescribedByProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static function GetDescribedBy(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.windows.foundation.collections.IVector<winrt.windows.ui.xaml.DependencyObject> /* GenericTypeInstSig */;
    static overload function FlowsToProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static function GetFlowsTo(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.windows.foundation.collections.IVector<winrt.windows.ui.xaml.DependencyObject> /* GenericTypeInstSig */;
    static overload function FlowsFromProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static function GetFlowsFrom(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.windows.foundation.collections.IVector<winrt.windows.ui.xaml.DependencyObject> /* GenericTypeInstSig */;
    static overload function CultureProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static function GetCulture(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Int32;
    static function SetCulture(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Int32): Void;
    static overload function HeadingLevelProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static function GetHeadingLevel(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.windows.ui.xaml.automation.peers.AutomationHeadingLevel;
    static function SetHeadingLevel(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.windows.ui.xaml.automation.peers.AutomationHeadingLevel>): Void;
    static overload function IsDialogProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static function GetIsDialog(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    static function SetIsDialog(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    static overload function AutomationControlTypeProperty(): winrt.windows.ui.xaml.DependencyProperty;
    static function GetAutomationControlType(element: ConstRef<winrt.windows.ui.xaml.UIElement>): winrt.windows.ui.xaml.automation.peers.AutomationControlType;
    static function SetAutomationControlType(element: ConstRef<winrt.windows.ui.xaml.UIElement>, value: ConstRef<winrt.windows.ui.xaml.automation.peers.AutomationControlType>): Void;
}
