package winrt.windows.services.store;

@:valueType
@:include("winrt/Windows.Services.Store.h", true)
@:native("winrt::Windows::Services::Store::StoreContext")
extern class StoreContext
    implements winrt.windows.services.store.IStoreContext
    implements winrt.windows.services.store.IStoreContext2
    implements winrt.windows.services.store.IStoreContext3
    implements winrt.windows.services.store.IStoreContext4
    implements winrt.windows.services.store.IStoreContext5
{
    overload function User(): winrt.windows.system.User;
    overload function OfflineLicensesChanged(handler: cxx.ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.windows.services.store.StoreContext, winrt.windows.foundation.IInspectable> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function OfflineLicensesChanged(token: cxx.ConstRef<winrt.EventToken>): Void;
    function GetCustomerPurchaseIdAsync(serviceTicket: cxx.ConstRef<winrt.HString>, publisherUserId: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.HString> /* GenericTypeInstSig */;
    function GetCustomerCollectionsIdAsync(serviceTicket: cxx.ConstRef<winrt.HString>, publisherUserId: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.HString> /* GenericTypeInstSig */;
    function GetAppLicenseAsync(): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.store.StoreAppLicense> /* GenericTypeInstSig */;
    function GetStoreProductForCurrentAppAsync(): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.store.StoreProductResult> /* GenericTypeInstSig */;
    overload function GetStoreProductsAsync(productKinds: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>, storeIds: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.store.StoreProductQueryResult> /* GenericTypeInstSig */;
    function GetAssociatedStoreProductsAsync(productKinds: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.store.StoreProductQueryResult> /* GenericTypeInstSig */;
    function GetAssociatedStoreProductsWithPagingAsync(productKinds: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>, maxItemsToRetrievePerPage: cxx.num.UInt32): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.store.StoreProductPagedQueryResult> /* GenericTypeInstSig */;
    function GetUserCollectionAsync(productKinds: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.store.StoreProductQueryResult> /* GenericTypeInstSig */;
    function GetUserCollectionWithPagingAsync(productKinds: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>, maxItemsToRetrievePerPage: cxx.num.UInt32): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.store.StoreProductPagedQueryResult> /* GenericTypeInstSig */;
    function ReportConsumableFulfillmentAsync(productStoreId: cxx.ConstRef<winrt.HString>, quantity: cxx.num.UInt32, trackingId: cxx.ConstRef<winrt.Guid>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.store.StoreConsumableResult> /* GenericTypeInstSig */;
    function GetConsumableBalanceRemainingAsync(productStoreId: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.store.StoreConsumableResult> /* GenericTypeInstSig */;
    function AcquireStoreLicenseForOptionalPackageAsync(optionalPackage: cxx.ConstRef<winrt.windows.applicationmodel.Package>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.store.StoreAcquireLicenseResult> /* GenericTypeInstSig */;
    overload function RequestPurchaseAsync(storeId: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.store.StorePurchaseResult> /* GenericTypeInstSig */;
    overload function RequestPurchaseAsync(storeId: cxx.ConstRef<winrt.HString>, storePurchaseProperties: cxx.ConstRef<winrt.windows.services.store.StorePurchaseProperties>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.store.StorePurchaseResult> /* GenericTypeInstSig */;
    function GetAppAndOptionalStorePackageUpdatesAsync(): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.services.store.StorePackageUpdate> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    function RequestDownloadStorePackageUpdatesAsync(storePackageUpdates: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.services.store.StorePackageUpdate> /* temp_GenericTypeInstSig */>): winrt.windows.foundation.IAsyncOperationWithProgress<winrt.windows.services.store.StorePackageUpdateResult, winrt.windows.services.store.StorePackageUpdateStatus> /* GenericTypeInstSig */;
    function RequestDownloadAndInstallStorePackageUpdatesAsync(storePackageUpdates: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.services.store.StorePackageUpdate> /* temp_GenericTypeInstSig */>): winrt.windows.foundation.IAsyncOperationWithProgress<winrt.windows.services.store.StorePackageUpdateResult, winrt.windows.services.store.StorePackageUpdateStatus> /* GenericTypeInstSig */;
    overload function RequestDownloadAndInstallStorePackagesAsync(storeIds: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>): winrt.windows.foundation.IAsyncOperationWithProgress<winrt.windows.services.store.StorePackageUpdateResult, winrt.windows.services.store.StorePackageUpdateStatus> /* GenericTypeInstSig */;
    function FindStoreProductForPackageAsync(productKinds: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>, package: cxx.ConstRef<winrt.windows.applicationmodel.Package>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.store.StoreProductResult> /* GenericTypeInstSig */;
    overload function CanSilentlyDownloadStorePackageUpdates(): Bool;
    function TrySilentDownloadStorePackageUpdatesAsync(storePackageUpdates: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.services.store.StorePackageUpdate> /* temp_GenericTypeInstSig */>): winrt.windows.foundation.IAsyncOperationWithProgress<winrt.windows.services.store.StorePackageUpdateResult, winrt.windows.services.store.StorePackageUpdateStatus> /* GenericTypeInstSig */;
    function TrySilentDownloadAndInstallStorePackageUpdatesAsync(storePackageUpdates: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.services.store.StorePackageUpdate> /* temp_GenericTypeInstSig */>): winrt.windows.foundation.IAsyncOperationWithProgress<winrt.windows.services.store.StorePackageUpdateResult, winrt.windows.services.store.StorePackageUpdateStatus> /* GenericTypeInstSig */;
    function CanAcquireStoreLicenseForOptionalPackageAsync(optionalPackage: cxx.ConstRef<winrt.windows.applicationmodel.Package>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.store.StoreCanAcquireLicenseResult> /* GenericTypeInstSig */;
    function CanAcquireStoreLicenseAsync(productStoreId: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.store.StoreCanAcquireLicenseResult> /* GenericTypeInstSig */;
    overload function GetStoreProductsAsync(productKinds: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>, storeIds: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>, storeProductOptions: cxx.ConstRef<winrt.windows.services.store.StoreProductOptions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.store.StoreProductQueryResult> /* GenericTypeInstSig */;
    function GetAssociatedStoreQueueItemsAsync(): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.services.store.StoreQueueItem> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    function GetStoreQueueItemsAsync(storeIds: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.services.store.StoreQueueItem> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    overload function RequestDownloadAndInstallStorePackagesAsync(storeIds: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>, storePackageInstallOptions: cxx.ConstRef<winrt.windows.services.store.StorePackageInstallOptions>): winrt.windows.foundation.IAsyncOperationWithProgress<winrt.windows.services.store.StorePackageUpdateResult, winrt.windows.services.store.StorePackageUpdateStatus> /* GenericTypeInstSig */;
    function DownloadAndInstallStorePackagesAsync(storeIds: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>): winrt.windows.foundation.IAsyncOperationWithProgress<winrt.windows.services.store.StorePackageUpdateResult, winrt.windows.services.store.StorePackageUpdateStatus> /* GenericTypeInstSig */;
    function RequestUninstallStorePackageAsync(package: cxx.ConstRef<winrt.windows.applicationmodel.Package>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.store.StoreUninstallStorePackageResult> /* GenericTypeInstSig */;
    function RequestUninstallStorePackageByStoreIdAsync(storeId: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.store.StoreUninstallStorePackageResult> /* GenericTypeInstSig */;
    function UninstallStorePackageAsync(package: cxx.ConstRef<winrt.windows.applicationmodel.Package>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.store.StoreUninstallStorePackageResult> /* GenericTypeInstSig */;
    function UninstallStorePackageByStoreIdAsync(storeId: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.store.StoreUninstallStorePackageResult> /* GenericTypeInstSig */;
    function RequestRateAndReviewAppAsync(): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.store.StoreRateAndReviewResult> /* GenericTypeInstSig */;
    function SetInstallOrderForAssociatedStoreQueueItemsAsync(items: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.services.store.StoreQueueItem> /* temp_GenericTypeInstSig */>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.services.store.StoreQueueItem> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    function GetUserPurchaseHistoryAsync(productKinds: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.store.StoreProductQueryResult> /* GenericTypeInstSig */;
    function GetAssociatedStoreProductsByInAppOfferTokenAsync(inAppOfferTokens: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.store.StoreProductQueryResult> /* GenericTypeInstSig */;
    function RequestPurchaseByInAppOfferTokenAsync(inAppOfferToken: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.store.StorePurchaseResult> /* GenericTypeInstSig */;
    function GetDefault(): winrt.windows.services.store.StoreContext;
    function GetForUser(user: cxx.ConstRef<winrt.windows.system.User>): winrt.windows.services.store.StoreContext;
    static function GetDefault(): winrt.windows.services.store.StoreContext;
    static function GetForUser(user: cxx.ConstRef<winrt.windows.system.User>): winrt.windows.services.store.StoreContext;
}
