package winrt.windows.devices.printers;

@:valueType
@:include("winrt/Windows.Devices.Printers.h", true)
@:native("winrt::Windows::Devices::Printers::IppAttributeValue")
extern class IppAttributeValue
    implements winrt.windows.devices.printers.IIppAttributeValue
{
    overload function Kind(): winrt.windows.devices.printers.IppAttributeValueKind;
    function GetIntegerArray(): winrt.windows.foundation.collections.IVector<cxx.num.Int32> /* GenericTypeInstSig */;
    function GetBooleanArray(): winrt.windows.foundation.collections.IVector<Bool> /* GenericTypeInstSig */;
    function GetEnumArray(): winrt.windows.foundation.collections.IVector<cxx.num.Int32> /* GenericTypeInstSig */;
    function GetOctetStringArray(): winrt.windows.foundation.collections.IVector<winrt.windows.storage.streams.IBuffer> /* GenericTypeInstSig */;
    function GetDateTimeArray(): winrt.windows.foundation.collections.IVector<winrt.windows.foundation.DateTime> /* GenericTypeInstSig */;
    function GetResolutionArray(): winrt.windows.foundation.collections.IVector<winrt.windows.devices.printers.IppResolution> /* GenericTypeInstSig */;
    function GetRangeOfIntegerArray(): winrt.windows.foundation.collections.IVector<winrt.windows.devices.printers.IppIntegerRange> /* GenericTypeInstSig */;
    function GetCollectionArray(): winrt.windows.foundation.collections.IVector<winrt.windows.foundation.collections.IMapView<winrt.HString, winrt.windows.devices.printers.IppAttributeValue> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    function GetTextWithLanguageArray(): winrt.windows.foundation.collections.IVector<winrt.windows.devices.printers.IppTextWithLanguage> /* GenericTypeInstSig */;
    function GetNameWithLanguageArray(): winrt.windows.foundation.collections.IVector<winrt.windows.devices.printers.IppTextWithLanguage> /* GenericTypeInstSig */;
    function GetTextWithoutLanguageArray(): winrt.windows.foundation.collections.IVector<winrt.HString> /* GenericTypeInstSig */;
    function GetNameWithoutLanguageArray(): winrt.windows.foundation.collections.IVector<winrt.HString> /* GenericTypeInstSig */;
    function GetKeywordArray(): winrt.windows.foundation.collections.IVector<winrt.HString> /* GenericTypeInstSig */;
    function GetUriArray(): winrt.windows.foundation.collections.IVector<winrt.windows.foundation.Uri> /* GenericTypeInstSig */;
    function GetUriSchemaArray(): winrt.windows.foundation.collections.IVector<winrt.HString> /* GenericTypeInstSig */;
    function GetCharsetArray(): winrt.windows.foundation.collections.IVector<winrt.HString> /* GenericTypeInstSig */;
    function GetNaturalLanguageArray(): winrt.windows.foundation.collections.IVector<winrt.HString> /* GenericTypeInstSig */;
    function GetMimeMediaTypeArray(): winrt.windows.foundation.collections.IVector<winrt.HString> /* GenericTypeInstSig */;
    function CreateUnsupported(): winrt.windows.devices.printers.IppAttributeValue;
    function CreateUnknown(): winrt.windows.devices.printers.IppAttributeValue;
    function CreateNoValue(): winrt.windows.devices.printers.IppAttributeValue;
    function CreateInteger(value: cxx.num.Int32): winrt.windows.devices.printers.IppAttributeValue;
    function CreateIntegerArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<cxx.num.Int32> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateBoolean(value: Bool): winrt.windows.devices.printers.IppAttributeValue;
    function CreateBooleanArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<Bool> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateEnum(value: cxx.num.Int32): winrt.windows.devices.printers.IppAttributeValue;
    function CreateEnumArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<cxx.num.Int32> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateOctetString(value: cxx.ConstRef<winrt.windows.storage.streams.IBuffer>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateOctetStringArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.storage.streams.IBuffer> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateDateTime(value: cxx.ConstRef<winrt.windows.foundation.DateTime>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateDateTimeArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.foundation.DateTime> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateResolution(value: cxx.ConstRef<winrt.windows.devices.printers.IppResolution>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateResolutionArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.devices.printers.IppResolution> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateRangeOfInteger(value: cxx.ConstRef<winrt.windows.devices.printers.IppIntegerRange>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateRangeOfIntegerArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.devices.printers.IppIntegerRange> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateCollection(memberAttributes: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.foundation.collections.IKeyValuePair<winrt.HString, winrt.windows.devices.printers.IppAttributeValue> /* GenericTypeInstSig */> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateCollectionArray(memberAttributesArray: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.foundation.collections.IIterable<winrt.windows.foundation.collections.IKeyValuePair<winrt.HString, winrt.windows.devices.printers.IppAttributeValue> /* GenericTypeInstSig */> /* GenericTypeInstSig */> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateTextWithLanguage(value: cxx.ConstRef<winrt.windows.devices.printers.IppTextWithLanguage>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateTextWithLanguageArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.devices.printers.IppTextWithLanguage> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateNameWithLanguage(value: cxx.ConstRef<winrt.windows.devices.printers.IppTextWithLanguage>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateNameWithLanguageArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.devices.printers.IppTextWithLanguage> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateTextWithoutLanguage(value: cxx.ConstRef<winrt.HString>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateTextWithoutLanguageArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateNameWithoutLanguage(value: cxx.ConstRef<winrt.HString>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateNameWithoutLanguageArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateKeyword(value: cxx.ConstRef<winrt.HString>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateKeywordArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateUri(value: cxx.ConstRef<winrt.windows.foundation.Uri>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateUriArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.foundation.Uri> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateUriSchema(value: cxx.ConstRef<winrt.HString>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateUriSchemaArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateCharset(value: cxx.ConstRef<winrt.HString>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateCharsetArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateNaturalLanguage(value: cxx.ConstRef<winrt.HString>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateNaturalLanguageArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateMimeMedia(value: cxx.ConstRef<winrt.HString>): winrt.windows.devices.printers.IppAttributeValue;
    function CreateMimeMediaArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateUnsupported(): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateUnknown(): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateNoValue(): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateInteger(value: cxx.num.Int32): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateIntegerArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<cxx.num.Int32> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateBoolean(value: Bool): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateBooleanArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<Bool> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateEnum(value: cxx.num.Int32): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateEnumArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<cxx.num.Int32> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateOctetString(value: cxx.ConstRef<winrt.windows.storage.streams.IBuffer>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateOctetStringArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.storage.streams.IBuffer> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateDateTime(value: cxx.ConstRef<winrt.windows.foundation.DateTime>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateDateTimeArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.foundation.DateTime> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateResolution(value: cxx.ConstRef<winrt.windows.devices.printers.IppResolution>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateResolutionArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.devices.printers.IppResolution> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateRangeOfInteger(value: cxx.ConstRef<winrt.windows.devices.printers.IppIntegerRange>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateRangeOfIntegerArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.devices.printers.IppIntegerRange> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateCollection(memberAttributes: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.foundation.collections.IKeyValuePair<winrt.HString, winrt.windows.devices.printers.IppAttributeValue> /* GenericTypeInstSig */> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateCollectionArray(memberAttributesArray: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.foundation.collections.IIterable<winrt.windows.foundation.collections.IKeyValuePair<winrt.HString, winrt.windows.devices.printers.IppAttributeValue> /* GenericTypeInstSig */> /* GenericTypeInstSig */> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateTextWithLanguage(value: cxx.ConstRef<winrt.windows.devices.printers.IppTextWithLanguage>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateTextWithLanguageArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.devices.printers.IppTextWithLanguage> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateNameWithLanguage(value: cxx.ConstRef<winrt.windows.devices.printers.IppTextWithLanguage>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateNameWithLanguageArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.devices.printers.IppTextWithLanguage> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateTextWithoutLanguage(value: cxx.ConstRef<winrt.HString>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateTextWithoutLanguageArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateNameWithoutLanguage(value: cxx.ConstRef<winrt.HString>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateNameWithoutLanguageArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateKeyword(value: cxx.ConstRef<winrt.HString>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateKeywordArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateUri(value: cxx.ConstRef<winrt.windows.foundation.Uri>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateUriArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.foundation.Uri> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateUriSchema(value: cxx.ConstRef<winrt.HString>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateUriSchemaArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateCharset(value: cxx.ConstRef<winrt.HString>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateCharsetArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateNaturalLanguage(value: cxx.ConstRef<winrt.HString>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateNaturalLanguageArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateMimeMedia(value: cxx.ConstRef<winrt.HString>): winrt.windows.devices.printers.IppAttributeValue;
    static function CreateMimeMediaArray(values: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>): winrt.windows.devices.printers.IppAttributeValue;
}
