package winrt.windows.ui.xaml.documents;

@:valueType
@:unreflective
@:structAccess
@:semantics(variable)
@:include("winrt/Windows.UI.Xaml.Documents.h", true)
@:native("winrt::Windows::UI::Xaml::Documents::ITypographyStatics")
extern interface ITypographyStatics extends winrt.windows.foundation.IInspectable
{
    overload function AnnotationAlternatesProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetAnnotationAlternates(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Int32;
    function SetAnnotationAlternates(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Int32): Void;
    overload function EastAsianExpertFormsProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetEastAsianExpertForms(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetEastAsianExpertForms(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function EastAsianLanguageProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetEastAsianLanguage(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.windows.ui.xaml.FontEastAsianLanguage;
    function SetEastAsianLanguage(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.windows.ui.xaml.FontEastAsianLanguage>): Void;
    overload function EastAsianWidthsProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetEastAsianWidths(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.windows.ui.xaml.FontEastAsianWidths;
    function SetEastAsianWidths(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.windows.ui.xaml.FontEastAsianWidths>): Void;
    overload function StandardLigaturesProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetStandardLigatures(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetStandardLigatures(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function ContextualLigaturesProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetContextualLigatures(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetContextualLigatures(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function DiscretionaryLigaturesProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetDiscretionaryLigatures(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetDiscretionaryLigatures(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function HistoricalLigaturesProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetHistoricalLigatures(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetHistoricalLigatures(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function StandardSwashesProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetStandardSwashes(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Int32;
    function SetStandardSwashes(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Int32): Void;
    overload function ContextualSwashesProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetContextualSwashes(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Int32;
    function SetContextualSwashes(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Int32): Void;
    overload function ContextualAlternatesProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetContextualAlternates(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetContextualAlternates(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function StylisticAlternatesProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetStylisticAlternates(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Int32;
    function SetStylisticAlternates(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Int32): Void;
    overload function StylisticSet1Property(): winrt.windows.ui.xaml.DependencyProperty;
    function GetStylisticSet1(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetStylisticSet1(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function StylisticSet2Property(): winrt.windows.ui.xaml.DependencyProperty;
    function GetStylisticSet2(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetStylisticSet2(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function StylisticSet3Property(): winrt.windows.ui.xaml.DependencyProperty;
    function GetStylisticSet3(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetStylisticSet3(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function StylisticSet4Property(): winrt.windows.ui.xaml.DependencyProperty;
    function GetStylisticSet4(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetStylisticSet4(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function StylisticSet5Property(): winrt.windows.ui.xaml.DependencyProperty;
    function GetStylisticSet5(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetStylisticSet5(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function StylisticSet6Property(): winrt.windows.ui.xaml.DependencyProperty;
    function GetStylisticSet6(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetStylisticSet6(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function StylisticSet7Property(): winrt.windows.ui.xaml.DependencyProperty;
    function GetStylisticSet7(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetStylisticSet7(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function StylisticSet8Property(): winrt.windows.ui.xaml.DependencyProperty;
    function GetStylisticSet8(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetStylisticSet8(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function StylisticSet9Property(): winrt.windows.ui.xaml.DependencyProperty;
    function GetStylisticSet9(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetStylisticSet9(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function StylisticSet10Property(): winrt.windows.ui.xaml.DependencyProperty;
    function GetStylisticSet10(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetStylisticSet10(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function StylisticSet11Property(): winrt.windows.ui.xaml.DependencyProperty;
    function GetStylisticSet11(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetStylisticSet11(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function StylisticSet12Property(): winrt.windows.ui.xaml.DependencyProperty;
    function GetStylisticSet12(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetStylisticSet12(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function StylisticSet13Property(): winrt.windows.ui.xaml.DependencyProperty;
    function GetStylisticSet13(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetStylisticSet13(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function StylisticSet14Property(): winrt.windows.ui.xaml.DependencyProperty;
    function GetStylisticSet14(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetStylisticSet14(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function StylisticSet15Property(): winrt.windows.ui.xaml.DependencyProperty;
    function GetStylisticSet15(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetStylisticSet15(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function StylisticSet16Property(): winrt.windows.ui.xaml.DependencyProperty;
    function GetStylisticSet16(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetStylisticSet16(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function StylisticSet17Property(): winrt.windows.ui.xaml.DependencyProperty;
    function GetStylisticSet17(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetStylisticSet17(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function StylisticSet18Property(): winrt.windows.ui.xaml.DependencyProperty;
    function GetStylisticSet18(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetStylisticSet18(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function StylisticSet19Property(): winrt.windows.ui.xaml.DependencyProperty;
    function GetStylisticSet19(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetStylisticSet19(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function StylisticSet20Property(): winrt.windows.ui.xaml.DependencyProperty;
    function GetStylisticSet20(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetStylisticSet20(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function CapitalsProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetCapitals(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.windows.ui.xaml.FontCapitals;
    function SetCapitals(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.windows.ui.xaml.FontCapitals>): Void;
    overload function CapitalSpacingProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetCapitalSpacing(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetCapitalSpacing(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function KerningProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetKerning(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetKerning(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function CaseSensitiveFormsProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetCaseSensitiveForms(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetCaseSensitiveForms(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function HistoricalFormsProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetHistoricalForms(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetHistoricalForms(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function FractionProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetFraction(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.windows.ui.xaml.FontFraction;
    function SetFraction(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.windows.ui.xaml.FontFraction>): Void;
    overload function NumeralStyleProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetNumeralStyle(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.windows.ui.xaml.FontNumeralStyle;
    function SetNumeralStyle(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.windows.ui.xaml.FontNumeralStyle>): Void;
    overload function NumeralAlignmentProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetNumeralAlignment(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.windows.ui.xaml.FontNumeralAlignment;
    function SetNumeralAlignment(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.windows.ui.xaml.FontNumeralAlignment>): Void;
    overload function SlashedZeroProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetSlashedZero(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetSlashedZero(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function MathematicalGreekProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetMathematicalGreek(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): Bool;
    function SetMathematicalGreek(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: Bool): Void;
    overload function VariantsProperty(): winrt.windows.ui.xaml.DependencyProperty;
    function GetVariants(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>): winrt.windows.ui.xaml.FontVariants;
    function SetVariants(element: ConstRef<winrt.windows.ui.xaml.DependencyObject>, value: ConstRef<winrt.windows.ui.xaml.FontVariants>): Void;
}
