package winrt.windows.security.authentication.web.provider;

@:include("winrt/Windows.Security.Authentication.Web.Provider.h", true)
@:native("winrt::Windows::Security::Authentication::Web::Provider::WebAccountManager")
extern class WebAccountManager
{
    static function UpdateWebAccountPropertiesAsync(webAccount: ConstRef<winrt.windows.security.credentials.WebAccount>, webAccountUserName: ConstRef<winrt.HString>, additionalProperties: ConstRef<winrt.windows.foundation.collections.IMapView<winrt.HString, winrt.HString> /* temp_GenericTypeInstSig */>): winrt.windows.foundation.IAsyncAction;
    static function AddWebAccountAsync(webAccountId: ConstRef<winrt.HString>, webAccountUserName: ConstRef<winrt.HString>, props: ConstRef<winrt.windows.foundation.collections.IMapView<winrt.HString, winrt.HString> /* temp_GenericTypeInstSig */>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.credentials.WebAccount> /* GenericTypeInstSig */;
    static function DeleteWebAccountAsync(webAccount: ConstRef<winrt.windows.security.credentials.WebAccount>): winrt.windows.foundation.IAsyncAction;
    static function FindAllProviderWebAccountsAsync(): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.security.credentials.WebAccount> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    static function PushCookiesAsync(uri: ConstRef<winrt.windows.foundation.Uri>, cookies: ConstRef<winrt.windows.foundation.collections.IVectorView<winrt.windows.web.http.HttpCookie> /* temp_GenericTypeInstSig */>): winrt.windows.foundation.IAsyncAction;
    static function SetViewAsync(webAccount: ConstRef<winrt.windows.security.credentials.WebAccount>, view: ConstRef<winrt.windows.security.authentication.web.provider.WebAccountClientView>): winrt.windows.foundation.IAsyncAction;
    static function ClearViewAsync(webAccount: ConstRef<winrt.windows.security.credentials.WebAccount>, applicationCallbackUri: ConstRef<winrt.windows.foundation.Uri>): winrt.windows.foundation.IAsyncAction;
    static function GetViewsAsync(webAccount: ConstRef<winrt.windows.security.credentials.WebAccount>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.security.authentication.web.provider.WebAccountClientView> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    static function SetWebAccountPictureAsync(webAccount: ConstRef<winrt.windows.security.credentials.WebAccount>, webAccountPicture: ConstRef<winrt.windows.storage.streams.IRandomAccessStream>): winrt.windows.foundation.IAsyncAction;
    static function ClearWebAccountPictureAsync(webAccount: ConstRef<winrt.windows.security.credentials.WebAccount>): winrt.windows.foundation.IAsyncAction;
    static function PullCookiesAsync(uriString: ConstRef<winrt.HString>, callerPFN: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncAction;
    static function FindAllProviderWebAccountsForUserAsync(user: ConstRef<winrt.windows.system.User>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.security.credentials.WebAccount> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    static overload function AddWebAccountForUserAsync(user: ConstRef<winrt.windows.system.User>, webAccountId: ConstRef<winrt.HString>, webAccountUserName: ConstRef<winrt.HString>, props: ConstRef<winrt.windows.foundation.collections.IMapView<winrt.HString, winrt.HString> /* temp_GenericTypeInstSig */>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.credentials.WebAccount> /* GenericTypeInstSig */;
    static overload function AddWebAccountForUserAsync(user: ConstRef<winrt.windows.system.User>, webAccountId: ConstRef<winrt.HString>, webAccountUserName: ConstRef<winrt.HString>, props: ConstRef<winrt.windows.foundation.collections.IMapView<winrt.HString, winrt.HString> /* temp_GenericTypeInstSig */>, scope: ConstRef<winrt.windows.security.authentication.web.provider.WebAccountScope>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.credentials.WebAccount> /* GenericTypeInstSig */;
    static overload function AddWebAccountForUserAsync(user: ConstRef<winrt.windows.system.User>, webAccountId: ConstRef<winrt.HString>, webAccountUserName: ConstRef<winrt.HString>, props: ConstRef<winrt.windows.foundation.collections.IMapView<winrt.HString, winrt.HString> /* temp_GenericTypeInstSig */>, scope: ConstRef<winrt.windows.security.authentication.web.provider.WebAccountScope>, perUserWebAccountId: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.credentials.WebAccount> /* GenericTypeInstSig */;
    static function InvalidateAppCacheForAllAccountsAsync(): winrt.windows.foundation.IAsyncAction;
    static function InvalidateAppCacheForAccountAsync(webAccount: ConstRef<winrt.windows.security.credentials.WebAccount>): winrt.windows.foundation.IAsyncAction;
    static function AddWebAccountAsync(webAccountId: ConstRef<winrt.HString>, webAccountUserName: ConstRef<winrt.HString>, props: ConstRef<winrt.windows.foundation.collections.IMapView<winrt.HString, winrt.HString> /* temp_GenericTypeInstSig */>, scope: ConstRef<winrt.windows.security.authentication.web.provider.WebAccountScope>, perUserWebAccountId: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.credentials.WebAccount> /* GenericTypeInstSig */;
    static function SetPerAppToPerUserAccountAsync(perAppAccount: ConstRef<winrt.windows.security.credentials.WebAccount>, perUserWebAccountId: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncAction;
    static function GetPerUserFromPerAppAccountAsync(perAppAccount: ConstRef<winrt.windows.security.credentials.WebAccount>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.credentials.WebAccount> /* GenericTypeInstSig */;
    static function ClearPerUserFromPerAppAccountAsync(perAppAccount: ConstRef<winrt.windows.security.credentials.WebAccount>): winrt.windows.foundation.IAsyncAction;
    static function AddWebAccountAsync(webAccountId: ConstRef<winrt.HString>, webAccountUserName: ConstRef<winrt.HString>, props: ConstRef<winrt.windows.foundation.collections.IMapView<winrt.HString, winrt.HString> /* temp_GenericTypeInstSig */>, scope: ConstRef<winrt.windows.security.authentication.web.provider.WebAccountScope>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.credentials.WebAccount> /* GenericTypeInstSig */;
    static function SetScopeAsync(webAccount: ConstRef<winrt.windows.security.credentials.WebAccount>, scope: ConstRef<winrt.windows.security.authentication.web.provider.WebAccountScope>): winrt.windows.foundation.IAsyncAction;
    static function GetScope(webAccount: ConstRef<winrt.windows.security.credentials.WebAccount>): winrt.windows.security.authentication.web.provider.WebAccountScope;
}
