package winrt.windows.services.maps;

@:valueType
@:include("winrt/Windows.Services.Maps.h", true)
@:native("winrt::Windows::Services::Maps::IMapRouteFinderStatics")
extern interface IMapRouteFinderStatics extends winrt.windows.foundation.IInspectable
{
    overload function GetDrivingRouteAsync(startPoint: cxx.ConstRef<winrt.windows.devices.geolocation.Geopoint>, endPoint: cxx.ConstRef<winrt.windows.devices.geolocation.Geopoint>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    overload function GetDrivingRouteAsync(startPoint: cxx.ConstRef<winrt.windows.devices.geolocation.Geopoint>, endPoint: cxx.ConstRef<winrt.windows.devices.geolocation.Geopoint>, optimization: cxx.ConstRef<winrt.windows.services.maps.MapRouteOptimization>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    overload function GetDrivingRouteAsync(startPoint: cxx.ConstRef<winrt.windows.devices.geolocation.Geopoint>, endPoint: cxx.ConstRef<winrt.windows.devices.geolocation.Geopoint>, optimization: cxx.ConstRef<winrt.windows.services.maps.MapRouteOptimization>, restrictions: cxx.ConstRef<winrt.windows.services.maps.MapRouteRestrictions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    overload function GetDrivingRouteAsync(startPoint: cxx.ConstRef<winrt.windows.devices.geolocation.Geopoint>, endPoint: cxx.ConstRef<winrt.windows.devices.geolocation.Geopoint>, optimization: cxx.ConstRef<winrt.windows.services.maps.MapRouteOptimization>, restrictions: cxx.ConstRef<winrt.windows.services.maps.MapRouteRestrictions>, headingInDegrees: cxx.num.Float64): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    overload function GetDrivingRouteFromWaypointsAsync(wayPoints: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.devices.geolocation.Geopoint> /* temp_GenericTypeInstSig */>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    overload function GetDrivingRouteFromWaypointsAsync(wayPoints: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.devices.geolocation.Geopoint> /* temp_GenericTypeInstSig */>, optimization: cxx.ConstRef<winrt.windows.services.maps.MapRouteOptimization>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    overload function GetDrivingRouteFromWaypointsAsync(wayPoints: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.devices.geolocation.Geopoint> /* temp_GenericTypeInstSig */>, optimization: cxx.ConstRef<winrt.windows.services.maps.MapRouteOptimization>, restrictions: cxx.ConstRef<winrt.windows.services.maps.MapRouteRestrictions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    overload function GetDrivingRouteFromWaypointsAsync(wayPoints: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.devices.geolocation.Geopoint> /* temp_GenericTypeInstSig */>, optimization: cxx.ConstRef<winrt.windows.services.maps.MapRouteOptimization>, restrictions: cxx.ConstRef<winrt.windows.services.maps.MapRouteRestrictions>, headingInDegrees: cxx.num.Float64): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    function GetWalkingRouteAsync(startPoint: cxx.ConstRef<winrt.windows.devices.geolocation.Geopoint>, endPoint: cxx.ConstRef<winrt.windows.devices.geolocation.Geopoint>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    function GetWalkingRouteFromWaypointsAsync(wayPoints: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.devices.geolocation.Geopoint> /* temp_GenericTypeInstSig */>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
}
