package winrt.windows.services.maps;

@:include("winrt/Windows.Services.Maps.h", true)
@:native("winrt::Windows::Services::Maps::MapRouteFinder")
extern class MapRouteFinder
{
    static overload function GetDrivingRouteAsync(startPoint: cxx.ConstRef<winrt.windows.devices.geolocation.Geopoint>, endPoint: cxx.ConstRef<winrt.windows.devices.geolocation.Geopoint>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    static overload function GetDrivingRouteAsync(startPoint: cxx.ConstRef<winrt.windows.devices.geolocation.Geopoint>, endPoint: cxx.ConstRef<winrt.windows.devices.geolocation.Geopoint>, optimization: cxx.ConstRef<winrt.windows.services.maps.MapRouteOptimization>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    static overload function GetDrivingRouteAsync(startPoint: cxx.ConstRef<winrt.windows.devices.geolocation.Geopoint>, endPoint: cxx.ConstRef<winrt.windows.devices.geolocation.Geopoint>, optimization: cxx.ConstRef<winrt.windows.services.maps.MapRouteOptimization>, restrictions: cxx.ConstRef<winrt.windows.services.maps.MapRouteRestrictions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    static overload function GetDrivingRouteAsync(startPoint: cxx.ConstRef<winrt.windows.devices.geolocation.Geopoint>, endPoint: cxx.ConstRef<winrt.windows.devices.geolocation.Geopoint>, optimization: cxx.ConstRef<winrt.windows.services.maps.MapRouteOptimization>, restrictions: cxx.ConstRef<winrt.windows.services.maps.MapRouteRestrictions>, headingInDegrees: cxx.num.Float64): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    static overload function GetDrivingRouteFromWaypointsAsync(wayPoints: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.devices.geolocation.Geopoint> /* temp_GenericTypeInstSig */>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    static overload function GetDrivingRouteFromWaypointsAsync(wayPoints: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.devices.geolocation.Geopoint> /* temp_GenericTypeInstSig */>, optimization: cxx.ConstRef<winrt.windows.services.maps.MapRouteOptimization>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    static overload function GetDrivingRouteFromWaypointsAsync(wayPoints: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.devices.geolocation.Geopoint> /* temp_GenericTypeInstSig */>, optimization: cxx.ConstRef<winrt.windows.services.maps.MapRouteOptimization>, restrictions: cxx.ConstRef<winrt.windows.services.maps.MapRouteRestrictions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    static overload function GetDrivingRouteFromWaypointsAsync(wayPoints: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.devices.geolocation.Geopoint> /* temp_GenericTypeInstSig */>, optimization: cxx.ConstRef<winrt.windows.services.maps.MapRouteOptimization>, restrictions: cxx.ConstRef<winrt.windows.services.maps.MapRouteRestrictions>, headingInDegrees: cxx.num.Float64): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    static function GetWalkingRouteAsync(startPoint: cxx.ConstRef<winrt.windows.devices.geolocation.Geopoint>, endPoint: cxx.ConstRef<winrt.windows.devices.geolocation.Geopoint>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    static function GetWalkingRouteFromWaypointsAsync(wayPoints: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.devices.geolocation.Geopoint> /* temp_GenericTypeInstSig */>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    static function GetDrivingRouteAsync(startPoint: cxx.ConstRef<winrt.windows.devices.geolocation.Geopoint>, endPoint: cxx.ConstRef<winrt.windows.devices.geolocation.Geopoint>, options: cxx.ConstRef<winrt.windows.services.maps.MapRouteDrivingOptions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    static overload function GetDrivingRouteFromEnhancedWaypointsAsync(waypoints: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.services.maps.EnhancedWaypoint> /* temp_GenericTypeInstSig */>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    static overload function GetDrivingRouteFromEnhancedWaypointsAsync(waypoints: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.services.maps.EnhancedWaypoint> /* temp_GenericTypeInstSig */>, options: cxx.ConstRef<winrt.windows.services.maps.MapRouteDrivingOptions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
}
