package winrt.windows.services.maps;

@:include("winrt/Windows.Services.Maps.h", true)
@:native("winrt::Windows::Services::Maps::MapRouteFinder")
extern class MapRouteFinder
{
    static overload function GetDrivingRouteAsync(startPoint: ConstRef<winrt.windows.devices.geolocation.Geopoint>, endPoint: ConstRef<winrt.windows.devices.geolocation.Geopoint>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    static overload function GetDrivingRouteAsync(startPoint: ConstRef<winrt.windows.devices.geolocation.Geopoint>, endPoint: ConstRef<winrt.windows.devices.geolocation.Geopoint>, optimization: ConstRef<winrt.windows.services.maps.MapRouteOptimization>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    static overload function GetDrivingRouteAsync(startPoint: ConstRef<winrt.windows.devices.geolocation.Geopoint>, endPoint: ConstRef<winrt.windows.devices.geolocation.Geopoint>, optimization: ConstRef<winrt.windows.services.maps.MapRouteOptimization>, restrictions: ConstRef<winrt.windows.services.maps.MapRouteRestrictions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    static overload function GetDrivingRouteAsync(startPoint: ConstRef<winrt.windows.devices.geolocation.Geopoint>, endPoint: ConstRef<winrt.windows.devices.geolocation.Geopoint>, optimization: ConstRef<winrt.windows.services.maps.MapRouteOptimization>, restrictions: ConstRef<winrt.windows.services.maps.MapRouteRestrictions>, headingInDegrees: Float64): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    static overload function GetDrivingRouteFromWaypointsAsync(wayPoints: ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.devices.geolocation.Geopoint> /* temp_GenericTypeInstSig */>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    static overload function GetDrivingRouteFromWaypointsAsync(wayPoints: ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.devices.geolocation.Geopoint> /* temp_GenericTypeInstSig */>, optimization: ConstRef<winrt.windows.services.maps.MapRouteOptimization>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    static overload function GetDrivingRouteFromWaypointsAsync(wayPoints: ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.devices.geolocation.Geopoint> /* temp_GenericTypeInstSig */>, optimization: ConstRef<winrt.windows.services.maps.MapRouteOptimization>, restrictions: ConstRef<winrt.windows.services.maps.MapRouteRestrictions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    static overload function GetDrivingRouteFromWaypointsAsync(wayPoints: ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.devices.geolocation.Geopoint> /* temp_GenericTypeInstSig */>, optimization: ConstRef<winrt.windows.services.maps.MapRouteOptimization>, restrictions: ConstRef<winrt.windows.services.maps.MapRouteRestrictions>, headingInDegrees: Float64): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    static function GetWalkingRouteAsync(startPoint: ConstRef<winrt.windows.devices.geolocation.Geopoint>, endPoint: ConstRef<winrt.windows.devices.geolocation.Geopoint>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    static function GetWalkingRouteFromWaypointsAsync(wayPoints: ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.devices.geolocation.Geopoint> /* temp_GenericTypeInstSig */>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    static function GetDrivingRouteAsync(startPoint: ConstRef<winrt.windows.devices.geolocation.Geopoint>, endPoint: ConstRef<winrt.windows.devices.geolocation.Geopoint>, options: ConstRef<winrt.windows.services.maps.MapRouteDrivingOptions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    static overload function GetDrivingRouteFromEnhancedWaypointsAsync(waypoints: ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.services.maps.EnhancedWaypoint> /* temp_GenericTypeInstSig */>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
    static overload function GetDrivingRouteFromEnhancedWaypointsAsync(waypoints: ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.services.maps.EnhancedWaypoint> /* temp_GenericTypeInstSig */>, options: ConstRef<winrt.windows.services.maps.MapRouteDrivingOptions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.services.maps.MapRouteFinderResult> /* GenericTypeInstSig */;
}
