package winrt.microsoft.ui.xaml.controls;

@:valueType
@:unreflective
@:structAccess
@:semantics(variable)
@:include("winrt/Microsoft.UI.Xaml.Controls.h", true)
@:native("winrt::Microsoft::UI::Xaml::Controls::ICalendarView")
extern interface ICalendarView extends winrt.windows.foundation.IInspectable
{
    overload function CalendarIdentifier(): winrt.HString;
    overload function CalendarIdentifier(value: ConstRef<winrt.HString>): Void;
    overload function DayOfWeekFormat(): winrt.HString;
    overload function DayOfWeekFormat(value: ConstRef<winrt.HString>): Void;
    overload function IsGroupLabelVisible(): Bool;
    overload function IsGroupLabelVisible(value: Bool): Void;
    overload function DisplayMode(): winrt.microsoft.ui.xaml.controls.CalendarViewDisplayMode;
    overload function DisplayMode(value: ConstRef<winrt.microsoft.ui.xaml.controls.CalendarViewDisplayMode>): Void;
    overload function FirstDayOfWeek(): winrt.windows.globalization.DayOfWeek;
    overload function FirstDayOfWeek(value: ConstRef<winrt.windows.globalization.DayOfWeek>): Void;
    overload function IsOutOfScopeEnabled(): Bool;
    overload function IsOutOfScopeEnabled(value: Bool): Void;
    overload function IsTodayHighlighted(): Bool;
    overload function IsTodayHighlighted(value: Bool): Void;
    overload function MaxDate(): winrt.windows.foundation.DateTime;
    overload function MaxDate(value: ConstRef<winrt.windows.foundation.DateTime>): Void;
    overload function MinDate(): winrt.windows.foundation.DateTime;
    overload function MinDate(value: ConstRef<winrt.windows.foundation.DateTime>): Void;
    overload function NumberOfWeeksInView(): Int32;
    overload function NumberOfWeeksInView(value: Int32): Void;
    overload function SelectedDates(): winrt.windows.foundation.collections.IVector<winrt.windows.foundation.DateTime> /* GenericTypeInstSig */;
    overload function SelectionMode(): winrt.microsoft.ui.xaml.controls.CalendarViewSelectionMode;
    overload function SelectionMode(value: ConstRef<winrt.microsoft.ui.xaml.controls.CalendarViewSelectionMode>): Void;
    overload function TemplateSettings(): winrt.microsoft.ui.xaml.controls.primitives.CalendarViewTemplateSettings;
    overload function FocusBorderBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function FocusBorderBrush(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function SelectedHoverBorderBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function SelectedHoverBorderBrush(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function SelectedPressedBorderBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function SelectedPressedBorderBrush(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function SelectedDisabledBorderBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function SelectedDisabledBorderBrush(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function SelectedBorderBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function SelectedBorderBrush(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function HoverBorderBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function HoverBorderBrush(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function PressedBorderBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function PressedBorderBrush(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function TodaySelectedInnerBorderBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function TodaySelectedInnerBorderBrush(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function BlackoutStrikethroughBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function BlackoutStrikethroughBrush(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function CalendarItemBorderBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function CalendarItemBorderBrush(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function BlackoutBackground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function BlackoutBackground(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function OutOfScopeBackground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function OutOfScopeBackground(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function CalendarItemBackground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function CalendarItemBackground(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function CalendarItemHoverBackground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function CalendarItemHoverBackground(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function CalendarItemPressedBackground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function CalendarItemPressedBackground(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function CalendarItemDisabledBackground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function CalendarItemDisabledBackground(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function TodayBackground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function TodayBackground(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function TodayBlackoutBackground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function TodayBlackoutBackground(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function TodayHoverBackground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function TodayHoverBackground(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function TodayPressedBackground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function TodayPressedBackground(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function TodayDisabledBackground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function TodayDisabledBackground(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function PressedForeground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function PressedForeground(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function TodayForeground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function TodayForeground(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function BlackoutForeground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function BlackoutForeground(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function TodayBlackoutForeground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function TodayBlackoutForeground(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function SelectedForeground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function SelectedForeground(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function SelectedHoverForeground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function SelectedHoverForeground(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function SelectedPressedForeground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function SelectedPressedForeground(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function SelectedDisabledForeground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function SelectedDisabledForeground(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function OutOfScopeForeground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function OutOfScopeForeground(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function OutOfScopeHoverForeground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function OutOfScopeHoverForeground(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function OutOfScopePressedForeground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function OutOfScopePressedForeground(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function CalendarItemForeground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function CalendarItemForeground(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function DisabledForeground(): winrt.microsoft.ui.xaml.media.Brush;
    overload function DisabledForeground(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function DayItemFontFamily(): winrt.microsoft.ui.xaml.media.FontFamily;
    overload function DayItemFontFamily(value: ConstRef<winrt.microsoft.ui.xaml.media.FontFamily>): Void;
    overload function DayItemFontSize(): Float64;
    overload function DayItemFontSize(value: Float64): Void;
    overload function DayItemFontStyle(): winrt.windows.ui.text.FontStyle;
    overload function DayItemFontStyle(value: ConstRef<winrt.windows.ui.text.FontStyle>): Void;
    overload function DayItemFontWeight(): winrt.windows.ui.text.FontWeight;
    overload function DayItemFontWeight(value: ConstRef<winrt.windows.ui.text.FontWeight>): Void;
    overload function TodayFontWeight(): winrt.windows.ui.text.FontWeight;
    overload function TodayFontWeight(value: ConstRef<winrt.windows.ui.text.FontWeight>): Void;
    overload function FirstOfMonthLabelFontFamily(): winrt.microsoft.ui.xaml.media.FontFamily;
    overload function FirstOfMonthLabelFontFamily(value: ConstRef<winrt.microsoft.ui.xaml.media.FontFamily>): Void;
    overload function FirstOfMonthLabelFontSize(): Float64;
    overload function FirstOfMonthLabelFontSize(value: Float64): Void;
    overload function FirstOfMonthLabelFontStyle(): winrt.windows.ui.text.FontStyle;
    overload function FirstOfMonthLabelFontStyle(value: ConstRef<winrt.windows.ui.text.FontStyle>): Void;
    overload function FirstOfMonthLabelFontWeight(): winrt.windows.ui.text.FontWeight;
    overload function FirstOfMonthLabelFontWeight(value: ConstRef<winrt.windows.ui.text.FontWeight>): Void;
    overload function MonthYearItemFontFamily(): winrt.microsoft.ui.xaml.media.FontFamily;
    overload function MonthYearItemFontFamily(value: ConstRef<winrt.microsoft.ui.xaml.media.FontFamily>): Void;
    overload function MonthYearItemFontSize(): Float64;
    overload function MonthYearItemFontSize(value: Float64): Void;
    overload function MonthYearItemFontStyle(): winrt.windows.ui.text.FontStyle;
    overload function MonthYearItemFontStyle(value: ConstRef<winrt.windows.ui.text.FontStyle>): Void;
    overload function MonthYearItemFontWeight(): winrt.windows.ui.text.FontWeight;
    overload function MonthYearItemFontWeight(value: ConstRef<winrt.windows.ui.text.FontWeight>): Void;
    overload function FirstOfYearDecadeLabelFontFamily(): winrt.microsoft.ui.xaml.media.FontFamily;
    overload function FirstOfYearDecadeLabelFontFamily(value: ConstRef<winrt.microsoft.ui.xaml.media.FontFamily>): Void;
    overload function FirstOfYearDecadeLabelFontSize(): Float64;
    overload function FirstOfYearDecadeLabelFontSize(value: Float64): Void;
    overload function FirstOfYearDecadeLabelFontStyle(): winrt.windows.ui.text.FontStyle;
    overload function FirstOfYearDecadeLabelFontStyle(value: ConstRef<winrt.windows.ui.text.FontStyle>): Void;
    overload function FirstOfYearDecadeLabelFontWeight(): winrt.windows.ui.text.FontWeight;
    overload function FirstOfYearDecadeLabelFontWeight(value: ConstRef<winrt.windows.ui.text.FontWeight>): Void;
    overload function DayItemMargin(): winrt.microsoft.ui.xaml.Thickness;
    overload function DayItemMargin(value: ConstRef<winrt.microsoft.ui.xaml.Thickness>): Void;
    overload function MonthYearItemMargin(): winrt.microsoft.ui.xaml.Thickness;
    overload function MonthYearItemMargin(value: ConstRef<winrt.microsoft.ui.xaml.Thickness>): Void;
    overload function FirstOfMonthLabelMargin(): winrt.microsoft.ui.xaml.Thickness;
    overload function FirstOfMonthLabelMargin(value: ConstRef<winrt.microsoft.ui.xaml.Thickness>): Void;
    overload function FirstOfYearDecadeLabelMargin(): winrt.microsoft.ui.xaml.Thickness;
    overload function FirstOfYearDecadeLabelMargin(value: ConstRef<winrt.microsoft.ui.xaml.Thickness>): Void;
    overload function HorizontalDayItemAlignment(): winrt.microsoft.ui.xaml.HorizontalAlignment;
    overload function HorizontalDayItemAlignment(value: ConstRef<winrt.microsoft.ui.xaml.HorizontalAlignment>): Void;
    overload function VerticalDayItemAlignment(): winrt.microsoft.ui.xaml.VerticalAlignment;
    overload function VerticalDayItemAlignment(value: ConstRef<winrt.microsoft.ui.xaml.VerticalAlignment>): Void;
    overload function HorizontalFirstOfMonthLabelAlignment(): winrt.microsoft.ui.xaml.HorizontalAlignment;
    overload function HorizontalFirstOfMonthLabelAlignment(value: ConstRef<winrt.microsoft.ui.xaml.HorizontalAlignment>): Void;
    overload function VerticalFirstOfMonthLabelAlignment(): winrt.microsoft.ui.xaml.VerticalAlignment;
    overload function VerticalFirstOfMonthLabelAlignment(value: ConstRef<winrt.microsoft.ui.xaml.VerticalAlignment>): Void;
    overload function CalendarItemBorderThickness(): winrt.microsoft.ui.xaml.Thickness;
    overload function CalendarItemBorderThickness(value: ConstRef<winrt.microsoft.ui.xaml.Thickness>): Void;
    overload function CalendarViewDayItemStyle(): winrt.microsoft.ui.xaml.Style;
    overload function CalendarViewDayItemStyle(value: ConstRef<winrt.microsoft.ui.xaml.Style>): Void;
    overload function CalendarItemCornerRadius(): winrt.microsoft.ui.xaml.CornerRadius;
    overload function CalendarItemCornerRadius(value: ConstRef<winrt.microsoft.ui.xaml.CornerRadius>): Void;
    overload function CalendarViewDayItemChanging(handler: ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.microsoft.ui.xaml.controls.CalendarView, winrt.microsoft.ui.xaml.controls.CalendarViewDayItemChangingEventArgs> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function CalendarViewDayItemChanging(token: ConstRef<winrt.EventToken>): Void;
    overload function SelectedDatesChanged(handler: ConstRef<winrt.windows.foundation.TypedEventHandler<winrt.microsoft.ui.xaml.controls.CalendarView, winrt.microsoft.ui.xaml.controls.CalendarViewSelectedDatesChangedEventArgs> /* temp_GenericTypeInstSig */>): winrt.EventToken;
    @:noExcept overload function SelectedDatesChanged(token: ConstRef<winrt.EventToken>): Void;
    function SetDisplayDate(date: ConstRef<winrt.windows.foundation.DateTime>): Void;
    function SetYearDecadeDisplayDimensions(columns: Int32, rows: Int32): Void;
}
