package winrt.microsoft.ui.xaml.controls;

@:valueType
@:unreflective
@:structAccess
@:semantics(variable)
@:include("winrt/Microsoft.UI.Xaml.Controls.h", true)
@:native("winrt::Microsoft::UI::Xaml::Controls::RelativePanel")
extern class RelativePanel
    extends winrt.microsoft.ui.xaml.controls.Panel
    implements winrt.microsoft.ui.xaml.controls.IRelativePanel
{
    function new();
    overload function BackgroundSizing(): winrt.microsoft.ui.xaml.controls.BackgroundSizing;
    overload function BackgroundSizing(value: ConstRef<winrt.microsoft.ui.xaml.controls.BackgroundSizing>): Void;
    overload function BorderBrush(): winrt.microsoft.ui.xaml.media.Brush;
    overload function BorderBrush(value: ConstRef<winrt.microsoft.ui.xaml.media.Brush>): Void;
    overload function BorderThickness(): winrt.microsoft.ui.xaml.Thickness;
    overload function BorderThickness(value: ConstRef<winrt.microsoft.ui.xaml.Thickness>): Void;
    overload function CornerRadius(): winrt.microsoft.ui.xaml.CornerRadius;
    overload function CornerRadius(value: ConstRef<winrt.microsoft.ui.xaml.CornerRadius>): Void;
    overload function Padding(): winrt.microsoft.ui.xaml.Thickness;
    overload function Padding(value: ConstRef<winrt.microsoft.ui.xaml.Thickness>): Void;
    overload function BackgroundSizingProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function LeftOfProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetLeftOf(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): winrt.windows.foundation.IInspectable;
    function SetLeftOf(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: ConstRef<winrt.windows.foundation.IInspectable>): Void;
    overload function AboveProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetAbove(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): winrt.windows.foundation.IInspectable;
    function SetAbove(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: ConstRef<winrt.windows.foundation.IInspectable>): Void;
    overload function RightOfProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetRightOf(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): winrt.windows.foundation.IInspectable;
    function SetRightOf(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: ConstRef<winrt.windows.foundation.IInspectable>): Void;
    overload function BelowProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetBelow(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): winrt.windows.foundation.IInspectable;
    function SetBelow(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: ConstRef<winrt.windows.foundation.IInspectable>): Void;
    overload function AlignHorizontalCenterWithProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetAlignHorizontalCenterWith(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): winrt.windows.foundation.IInspectable;
    function SetAlignHorizontalCenterWith(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: ConstRef<winrt.windows.foundation.IInspectable>): Void;
    overload function AlignVerticalCenterWithProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetAlignVerticalCenterWith(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): winrt.windows.foundation.IInspectable;
    function SetAlignVerticalCenterWith(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: ConstRef<winrt.windows.foundation.IInspectable>): Void;
    overload function AlignLeftWithProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetAlignLeftWith(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): winrt.windows.foundation.IInspectable;
    function SetAlignLeftWith(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: ConstRef<winrt.windows.foundation.IInspectable>): Void;
    overload function AlignTopWithProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetAlignTopWith(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): winrt.windows.foundation.IInspectable;
    function SetAlignTopWith(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: ConstRef<winrt.windows.foundation.IInspectable>): Void;
    overload function AlignRightWithProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetAlignRightWith(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): winrt.windows.foundation.IInspectable;
    function SetAlignRightWith(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: ConstRef<winrt.windows.foundation.IInspectable>): Void;
    overload function AlignBottomWithProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetAlignBottomWith(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): winrt.windows.foundation.IInspectable;
    function SetAlignBottomWith(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: ConstRef<winrt.windows.foundation.IInspectable>): Void;
    overload function AlignLeftWithPanelProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetAlignLeftWithPanel(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): Bool;
    function SetAlignLeftWithPanel(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: Bool): Void;
    overload function AlignTopWithPanelProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetAlignTopWithPanel(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): Bool;
    function SetAlignTopWithPanel(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: Bool): Void;
    overload function AlignRightWithPanelProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetAlignRightWithPanel(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): Bool;
    function SetAlignRightWithPanel(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: Bool): Void;
    overload function AlignBottomWithPanelProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetAlignBottomWithPanel(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): Bool;
    function SetAlignBottomWithPanel(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: Bool): Void;
    overload function AlignHorizontalCenterWithPanelProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetAlignHorizontalCenterWithPanel(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): Bool;
    function SetAlignHorizontalCenterWithPanel(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: Bool): Void;
    overload function AlignVerticalCenterWithPanelProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    function GetAlignVerticalCenterWithPanel(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): Bool;
    function SetAlignVerticalCenterWithPanel(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: Bool): Void;
    overload function BorderBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function BorderThicknessProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function CornerRadiusProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    overload function PaddingProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function BackgroundSizingProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function LeftOfProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static function GetLeftOf(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): winrt.windows.foundation.IInspectable;
    static function SetLeftOf(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: ConstRef<winrt.windows.foundation.IInspectable>): Void;
    static overload function AboveProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static function GetAbove(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): winrt.windows.foundation.IInspectable;
    static function SetAbove(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: ConstRef<winrt.windows.foundation.IInspectable>): Void;
    static overload function RightOfProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static function GetRightOf(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): winrt.windows.foundation.IInspectable;
    static function SetRightOf(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: ConstRef<winrt.windows.foundation.IInspectable>): Void;
    static overload function BelowProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static function GetBelow(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): winrt.windows.foundation.IInspectable;
    static function SetBelow(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: ConstRef<winrt.windows.foundation.IInspectable>): Void;
    static overload function AlignHorizontalCenterWithProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static function GetAlignHorizontalCenterWith(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): winrt.windows.foundation.IInspectable;
    static function SetAlignHorizontalCenterWith(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: ConstRef<winrt.windows.foundation.IInspectable>): Void;
    static overload function AlignVerticalCenterWithProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static function GetAlignVerticalCenterWith(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): winrt.windows.foundation.IInspectable;
    static function SetAlignVerticalCenterWith(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: ConstRef<winrt.windows.foundation.IInspectable>): Void;
    static overload function AlignLeftWithProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static function GetAlignLeftWith(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): winrt.windows.foundation.IInspectable;
    static function SetAlignLeftWith(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: ConstRef<winrt.windows.foundation.IInspectable>): Void;
    static overload function AlignTopWithProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static function GetAlignTopWith(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): winrt.windows.foundation.IInspectable;
    static function SetAlignTopWith(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: ConstRef<winrt.windows.foundation.IInspectable>): Void;
    static overload function AlignRightWithProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static function GetAlignRightWith(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): winrt.windows.foundation.IInspectable;
    static function SetAlignRightWith(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: ConstRef<winrt.windows.foundation.IInspectable>): Void;
    static overload function AlignBottomWithProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static function GetAlignBottomWith(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): winrt.windows.foundation.IInspectable;
    static function SetAlignBottomWith(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: ConstRef<winrt.windows.foundation.IInspectable>): Void;
    static overload function AlignLeftWithPanelProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static function GetAlignLeftWithPanel(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): Bool;
    static function SetAlignLeftWithPanel(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: Bool): Void;
    static overload function AlignTopWithPanelProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static function GetAlignTopWithPanel(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): Bool;
    static function SetAlignTopWithPanel(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: Bool): Void;
    static overload function AlignRightWithPanelProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static function GetAlignRightWithPanel(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): Bool;
    static function SetAlignRightWithPanel(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: Bool): Void;
    static overload function AlignBottomWithPanelProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static function GetAlignBottomWithPanel(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): Bool;
    static function SetAlignBottomWithPanel(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: Bool): Void;
    static overload function AlignHorizontalCenterWithPanelProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static function GetAlignHorizontalCenterWithPanel(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): Bool;
    static function SetAlignHorizontalCenterWithPanel(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: Bool): Void;
    static overload function AlignVerticalCenterWithPanelProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static function GetAlignVerticalCenterWithPanel(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>): Bool;
    static function SetAlignVerticalCenterWithPanel(element: ConstRef<winrt.microsoft.ui.xaml.UIElement>, value: Bool): Void;
    static overload function BorderBrushProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function BorderThicknessProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function CornerRadiusProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
    static overload function PaddingProperty(): winrt.microsoft.ui.xaml.DependencyProperty;
}
