package winrt.windows.globalization.datetimeformatting;

@:valueType
@:include("winrt/Windows.Globalization.DateTimeFormatting.h", true)
@:native("winrt::Windows::Globalization::DateTimeFormatting::IDateTimeFormatterFactory")
extern interface IDateTimeFormatterFactory extends winrt.windows.foundation.IInspectable
{
    function CreateDateTimeFormatter(formatTemplate: cxx.ConstRef<winrt.HString>): winrt.windows.globalization.datetimeformatting.DateTimeFormatter;
    function CreateDateTimeFormatterLanguages(formatTemplate: cxx.ConstRef<winrt.HString>, languages: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>): winrt.windows.globalization.datetimeformatting.DateTimeFormatter;
    function CreateDateTimeFormatterContext(formatTemplate: cxx.ConstRef<winrt.HString>, languages: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>, geographicRegion: cxx.ConstRef<winrt.HString>, calendar: cxx.ConstRef<winrt.HString>, clock: cxx.ConstRef<winrt.HString>): winrt.windows.globalization.datetimeformatting.DateTimeFormatter;
    function CreateDateTimeFormatterDate(yearFormat: cxx.ConstRef<winrt.windows.globalization.datetimeformatting.YearFormat>, monthFormat: cxx.ConstRef<winrt.windows.globalization.datetimeformatting.MonthFormat>, dayFormat: cxx.ConstRef<winrt.windows.globalization.datetimeformatting.DayFormat>, dayOfWeekFormat: cxx.ConstRef<winrt.windows.globalization.datetimeformatting.DayOfWeekFormat>): winrt.windows.globalization.datetimeformatting.DateTimeFormatter;
    function CreateDateTimeFormatterTime(hourFormat: cxx.ConstRef<winrt.windows.globalization.datetimeformatting.HourFormat>, minuteFormat: cxx.ConstRef<winrt.windows.globalization.datetimeformatting.MinuteFormat>, secondFormat: cxx.ConstRef<winrt.windows.globalization.datetimeformatting.SecondFormat>): winrt.windows.globalization.datetimeformatting.DateTimeFormatter;
    function CreateDateTimeFormatterDateTimeLanguages(yearFormat: cxx.ConstRef<winrt.windows.globalization.datetimeformatting.YearFormat>, monthFormat: cxx.ConstRef<winrt.windows.globalization.datetimeformatting.MonthFormat>, dayFormat: cxx.ConstRef<winrt.windows.globalization.datetimeformatting.DayFormat>, dayOfWeekFormat: cxx.ConstRef<winrt.windows.globalization.datetimeformatting.DayOfWeekFormat>, hourFormat: cxx.ConstRef<winrt.windows.globalization.datetimeformatting.HourFormat>, minuteFormat: cxx.ConstRef<winrt.windows.globalization.datetimeformatting.MinuteFormat>, secondFormat: cxx.ConstRef<winrt.windows.globalization.datetimeformatting.SecondFormat>, languages: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>): winrt.windows.globalization.datetimeformatting.DateTimeFormatter;
    function CreateDateTimeFormatterDateTimeContext(yearFormat: cxx.ConstRef<winrt.windows.globalization.datetimeformatting.YearFormat>, monthFormat: cxx.ConstRef<winrt.windows.globalization.datetimeformatting.MonthFormat>, dayFormat: cxx.ConstRef<winrt.windows.globalization.datetimeformatting.DayFormat>, dayOfWeekFormat: cxx.ConstRef<winrt.windows.globalization.datetimeformatting.DayOfWeekFormat>, hourFormat: cxx.ConstRef<winrt.windows.globalization.datetimeformatting.HourFormat>, minuteFormat: cxx.ConstRef<winrt.windows.globalization.datetimeformatting.MinuteFormat>, secondFormat: cxx.ConstRef<winrt.windows.globalization.datetimeformatting.SecondFormat>, languages: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>, geographicRegion: cxx.ConstRef<winrt.HString>, calendar: cxx.ConstRef<winrt.HString>, clock: cxx.ConstRef<winrt.HString>): winrt.windows.globalization.datetimeformatting.DateTimeFormatter;
}
