package winrt.windows.devices.smartcards;

@:valueType
@:include("winrt/Windows.Devices.SmartCards.h", true)
@:native("winrt::Windows::Devices::SmartCards::SmartCardCryptogramGenerator")
extern class SmartCardCryptogramGenerator
    implements winrt.windows.devices.smartcards.ISmartCardCryptogramGenerator
    implements winrt.windows.devices.smartcards.ISmartCardCryptogramGenerator2
{
    overload function SupportedCryptogramMaterialTypes(): winrt.windows.foundation.collections.IVectorView<winrt.windows.devices.smartcards.SmartCardCryptogramMaterialType> /* GenericTypeInstSig */;
    overload function SupportedCryptogramAlgorithms(): winrt.windows.foundation.collections.IVectorView<winrt.windows.devices.smartcards.SmartCardCryptogramAlgorithm> /* GenericTypeInstSig */;
    overload function SupportedCryptogramMaterialPackageFormats(): winrt.windows.foundation.collections.IVectorView<winrt.windows.devices.smartcards.SmartCardCryptogramMaterialPackageFormat> /* GenericTypeInstSig */;
    overload function SupportedCryptogramMaterialPackageConfirmationResponseFormats(): winrt.windows.foundation.collections.IVectorView<winrt.windows.devices.smartcards.SmartCardCryptogramMaterialPackageConfirmationResponseFormat> /* GenericTypeInstSig */;
    overload function SupportedSmartCardCryptogramStorageKeyCapabilities(): winrt.windows.foundation.collections.IVectorView<winrt.windows.devices.smartcards.SmartCardCryptogramStorageKeyCapabilities> /* GenericTypeInstSig */;
    function DeleteCryptogramMaterialStorageKeyAsync(storageKeyName: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.devices.smartcards.SmartCardCryptogramGeneratorOperationStatus> /* GenericTypeInstSig */;
    function CreateCryptogramMaterialStorageKeyAsync(promptingBehavior: cxx.ConstRef<winrt.windows.devices.smartcards.SmartCardUnlockPromptingBehavior>, storageKeyName: cxx.ConstRef<winrt.HString>, algorithm: cxx.ConstRef<winrt.windows.devices.smartcards.SmartCardCryptogramStorageKeyAlgorithm>, capabilities: cxx.ConstRef<winrt.windows.devices.smartcards.SmartCardCryptogramStorageKeyCapabilities>): winrt.windows.foundation.IAsyncOperation<winrt.windows.devices.smartcards.SmartCardCryptogramGeneratorOperationStatus> /* GenericTypeInstSig */;
    function RequestCryptogramMaterialStorageKeyInfoAsync(promptingBehavior: cxx.ConstRef<winrt.windows.devices.smartcards.SmartCardUnlockPromptingBehavior>, storageKeyName: cxx.ConstRef<winrt.HString>, format: cxx.ConstRef<winrt.windows.security.cryptography.core.CryptographicPublicKeyBlobType>): winrt.windows.foundation.IAsyncOperation<winrt.windows.devices.smartcards.SmartCardCryptogramStorageKeyInfo> /* GenericTypeInstSig */;
    function ImportCryptogramMaterialPackageAsync(format: cxx.ConstRef<winrt.windows.devices.smartcards.SmartCardCryptogramMaterialPackageFormat>, storageKeyName: cxx.ConstRef<winrt.HString>, materialPackageName: cxx.ConstRef<winrt.HString>, cryptogramMaterialPackage: cxx.ConstRef<winrt.windows.storage.streams.IBuffer>): winrt.windows.foundation.IAsyncOperation<winrt.windows.devices.smartcards.SmartCardCryptogramGeneratorOperationStatus> /* GenericTypeInstSig */;
    function TryProvePossessionOfCryptogramMaterialPackageAsync(promptingBehavior: cxx.ConstRef<winrt.windows.devices.smartcards.SmartCardUnlockPromptingBehavior>, responseFormat: cxx.ConstRef<winrt.windows.devices.smartcards.SmartCardCryptogramMaterialPackageConfirmationResponseFormat>, materialPackageName: cxx.ConstRef<winrt.HString>, materialName: cxx.ConstRef<winrt.HString>, challenge: cxx.ConstRef<winrt.windows.storage.streams.IBuffer>): winrt.windows.foundation.IAsyncOperation<winrt.windows.devices.smartcards.SmartCardCryptogramMaterialPossessionProof> /* GenericTypeInstSig */;
    function RequestUnlockCryptogramMaterialForUseAsync(promptingBehavior: cxx.ConstRef<winrt.windows.devices.smartcards.SmartCardUnlockPromptingBehavior>): winrt.windows.foundation.IAsyncOperation<winrt.windows.devices.smartcards.SmartCardCryptogramGeneratorOperationStatus> /* GenericTypeInstSig */;
    function DeleteCryptogramMaterialPackageAsync(materialPackageName: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.devices.smartcards.SmartCardCryptogramGeneratorOperationStatus> /* GenericTypeInstSig */;
    function ValidateRequestApduAsync(promptingBehavior: cxx.ConstRef<winrt.windows.devices.smartcards.SmartCardUnlockPromptingBehavior>, apduToValidate: cxx.ConstRef<winrt.windows.storage.streams.IBuffer>, cryptogramPlacementSteps: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.devices.smartcards.SmartCardCryptogramPlacementStep> /* temp_GenericTypeInstSig */>): winrt.windows.foundation.IAsyncOperation<winrt.windows.devices.smartcards.SmartCardCryptogramGeneratorOperationStatus> /* GenericTypeInstSig */;
    function GetAllCryptogramStorageKeyCharacteristicsAsync(): winrt.windows.foundation.IAsyncOperation<winrt.windows.devices.smartcards.SmartCardCryptogramGetAllCryptogramStorageKeyCharacteristicsResult> /* GenericTypeInstSig */;
    overload function GetAllCryptogramMaterialPackageCharacteristicsAsync(): winrt.windows.foundation.IAsyncOperation<winrt.windows.devices.smartcards.SmartCardCryptogramGetAllCryptogramMaterialPackageCharacteristicsResult> /* GenericTypeInstSig */;
    overload function GetAllCryptogramMaterialPackageCharacteristicsAsync(storageKeyName: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.devices.smartcards.SmartCardCryptogramGetAllCryptogramMaterialPackageCharacteristicsResult> /* GenericTypeInstSig */;
    function GetAllCryptogramMaterialCharacteristicsAsync(promptingBehavior: cxx.ConstRef<winrt.windows.devices.smartcards.SmartCardUnlockPromptingBehavior>, materialPackageName: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.devices.smartcards.SmartCardCryptogramGetAllCryptogramMaterialCharacteristicsResult> /* GenericTypeInstSig */;
    function IsSupported(): Bool;
    function GetSmartCardCryptogramGeneratorAsync(): winrt.windows.foundation.IAsyncOperation<winrt.windows.devices.smartcards.SmartCardCryptogramGenerator> /* GenericTypeInstSig */;
    static function GetSmartCardCryptogramGeneratorAsync(): winrt.windows.foundation.IAsyncOperation<winrt.windows.devices.smartcards.SmartCardCryptogramGenerator> /* GenericTypeInstSig */;
    static function IsSupported(): Bool;
}
