package winrt.windows.system;

@:include("winrt/Windows.System.h", true)
@:native("winrt::Windows::System::Launcher")
extern class Launcher
{
    static overload function LaunchFileAsync(file: ConstRef<winrt.windows.storage.IStorageFile>): winrt.windows.foundation.IAsyncOperation<Bool> /* GenericTypeInstSig */;
    static overload function LaunchFileAsync(file: ConstRef<winrt.windows.storage.IStorageFile>, options: ConstRef<winrt.windows.system.LauncherOptions>): winrt.windows.foundation.IAsyncOperation<Bool> /* GenericTypeInstSig */;
    static overload function LaunchUriAsync(uri: ConstRef<winrt.windows.foundation.Uri>): winrt.windows.foundation.IAsyncOperation<Bool> /* GenericTypeInstSig */;
    static overload function LaunchUriAsync(uri: ConstRef<winrt.windows.foundation.Uri>, options: ConstRef<winrt.windows.system.LauncherOptions>): winrt.windows.foundation.IAsyncOperation<Bool> /* GenericTypeInstSig */;
    static overload function LaunchUriForResultsAsync(uri: ConstRef<winrt.windows.foundation.Uri>, options: ConstRef<winrt.windows.system.LauncherOptions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.system.LaunchUriResult> /* GenericTypeInstSig */;
    static overload function LaunchUriForResultsAsync(uri: ConstRef<winrt.windows.foundation.Uri>, options: ConstRef<winrt.windows.system.LauncherOptions>, inputData: ConstRef<winrt.windows.foundation.collections.ValueSet>): winrt.windows.foundation.IAsyncOperation<winrt.windows.system.LaunchUriResult> /* GenericTypeInstSig */;
    static function LaunchUriAsync(uri: ConstRef<winrt.windows.foundation.Uri>, options: ConstRef<winrt.windows.system.LauncherOptions>, inputData: ConstRef<winrt.windows.foundation.collections.ValueSet>): winrt.windows.foundation.IAsyncOperation<Bool> /* GenericTypeInstSig */;
    static overload function QueryUriSupportAsync(uri: ConstRef<winrt.windows.foundation.Uri>, launchQuerySupportType: ConstRef<winrt.windows.system.LaunchQuerySupportType>): winrt.windows.foundation.IAsyncOperation<winrt.windows.system.LaunchQuerySupportStatus> /* GenericTypeInstSig */;
    static overload function QueryUriSupportAsync(uri: ConstRef<winrt.windows.foundation.Uri>, launchQuerySupportType: ConstRef<winrt.windows.system.LaunchQuerySupportType>, packageFamilyName: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.system.LaunchQuerySupportStatus> /* GenericTypeInstSig */;
    static overload function QueryFileSupportAsync(file: ConstRef<winrt.windows.storage.StorageFile>): winrt.windows.foundation.IAsyncOperation<winrt.windows.system.LaunchQuerySupportStatus> /* GenericTypeInstSig */;
    static overload function QueryFileSupportAsync(file: ConstRef<winrt.windows.storage.StorageFile>, packageFamilyName: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.system.LaunchQuerySupportStatus> /* GenericTypeInstSig */;
    static overload function FindUriSchemeHandlersAsync(scheme: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.AppInfo> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    static overload function FindUriSchemeHandlersAsync(scheme: ConstRef<winrt.HString>, launchQuerySupportType: ConstRef<winrt.windows.system.LaunchQuerySupportType>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.AppInfo> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    static function FindFileHandlersAsync(extension: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.AppInfo> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    static overload function LaunchFolderAsync(folder: ConstRef<winrt.windows.storage.IStorageFolder>): winrt.windows.foundation.IAsyncOperation<Bool> /* GenericTypeInstSig */;
    static overload function LaunchFolderAsync(folder: ConstRef<winrt.windows.storage.IStorageFolder>, options: ConstRef<winrt.windows.system.FolderLauncherOptions>): winrt.windows.foundation.IAsyncOperation<Bool> /* GenericTypeInstSig */;
    static overload function QueryAppUriSupportAsync(uri: ConstRef<winrt.windows.foundation.Uri>): winrt.windows.foundation.IAsyncOperation<winrt.windows.system.LaunchQuerySupportStatus> /* GenericTypeInstSig */;
    static overload function QueryAppUriSupportAsync(uri: ConstRef<winrt.windows.foundation.Uri>, packageFamilyName: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<winrt.windows.system.LaunchQuerySupportStatus> /* GenericTypeInstSig */;
    static function FindAppUriHandlersAsync(uri: ConstRef<winrt.windows.foundation.Uri>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.applicationmodel.AppInfo> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    static overload function LaunchUriForUserAsync(user: ConstRef<winrt.windows.system.User>, uri: ConstRef<winrt.windows.foundation.Uri>): winrt.windows.foundation.IAsyncOperation<winrt.windows.system.LaunchUriStatus> /* GenericTypeInstSig */;
    static overload function LaunchUriForUserAsync(user: ConstRef<winrt.windows.system.User>, uri: ConstRef<winrt.windows.foundation.Uri>, options: ConstRef<winrt.windows.system.LauncherOptions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.system.LaunchUriStatus> /* GenericTypeInstSig */;
    static overload function LaunchUriForUserAsync(user: ConstRef<winrt.windows.system.User>, uri: ConstRef<winrt.windows.foundation.Uri>, options: ConstRef<winrt.windows.system.LauncherOptions>, inputData: ConstRef<winrt.windows.foundation.collections.ValueSet>): winrt.windows.foundation.IAsyncOperation<winrt.windows.system.LaunchUriStatus> /* GenericTypeInstSig */;
    static overload function LaunchUriForResultsForUserAsync(user: ConstRef<winrt.windows.system.User>, uri: ConstRef<winrt.windows.foundation.Uri>, options: ConstRef<winrt.windows.system.LauncherOptions>): winrt.windows.foundation.IAsyncOperation<winrt.windows.system.LaunchUriResult> /* GenericTypeInstSig */;
    static overload function LaunchUriForResultsForUserAsync(user: ConstRef<winrt.windows.system.User>, uri: ConstRef<winrt.windows.foundation.Uri>, options: ConstRef<winrt.windows.system.LauncherOptions>, inputData: ConstRef<winrt.windows.foundation.collections.ValueSet>): winrt.windows.foundation.IAsyncOperation<winrt.windows.system.LaunchUriResult> /* GenericTypeInstSig */;
    static overload function LaunchFolderPathAsync(path: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<Bool> /* GenericTypeInstSig */;
    static overload function LaunchFolderPathAsync(path: ConstRef<winrt.HString>, options: ConstRef<winrt.windows.system.FolderLauncherOptions>): winrt.windows.foundation.IAsyncOperation<Bool> /* GenericTypeInstSig */;
    static overload function LaunchFolderPathForUserAsync(user: ConstRef<winrt.windows.system.User>, path: ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperation<Bool> /* GenericTypeInstSig */;
    static overload function LaunchFolderPathForUserAsync(user: ConstRef<winrt.windows.system.User>, path: ConstRef<winrt.HString>, options: ConstRef<winrt.windows.system.FolderLauncherOptions>): winrt.windows.foundation.IAsyncOperation<Bool> /* GenericTypeInstSig */;
}
