package winrt.windows.foundation.diagnostics;

@:valueType
@:unreflective
@:structAccess
@:semantics(variable)
@:include("winrt/Windows.Foundation.Diagnostics.h", true)
@:native("winrt::Windows::Foundation::Diagnostics::ILoggingFields")
extern interface ILoggingFields extends winrt.windows.foundation.IInspectable
{
    function Clear(): Void;
    overload function BeginStruct(name: ConstRef<winrt.HString>): Void;
    overload function BeginStruct(name: ConstRef<winrt.HString>, tags: Int32): Void;
    function EndStruct(): Void;
    overload function AddEmpty(name: ConstRef<winrt.HString>): Void;
    overload function AddEmpty(name: ConstRef<winrt.HString>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddEmpty(name: ConstRef<winrt.HString>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddUInt8(name: ConstRef<winrt.HString>, value: UInt8): Void;
    overload function AddUInt8(name: ConstRef<winrt.HString>, value: UInt8, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddUInt8(name: ConstRef<winrt.HString>, value: UInt8, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddUInt8Array(name: ConstRef<winrt.HString>, value: winrt.ArrayView<UInt8>): Void;
    overload function AddUInt8Array(name: ConstRef<winrt.HString>, value: winrt.ArrayView<UInt8>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddUInt8Array(name: ConstRef<winrt.HString>, value: winrt.ArrayView<UInt8>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddInt16(name: ConstRef<winrt.HString>, value: Int16): Void;
    overload function AddInt16(name: ConstRef<winrt.HString>, value: Int16, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddInt16(name: ConstRef<winrt.HString>, value: Int16, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddInt16Array(name: ConstRef<winrt.HString>, value: winrt.ArrayView<Int16>): Void;
    overload function AddInt16Array(name: ConstRef<winrt.HString>, value: winrt.ArrayView<Int16>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddInt16Array(name: ConstRef<winrt.HString>, value: winrt.ArrayView<Int16>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddUInt16(name: ConstRef<winrt.HString>, value: UInt16): Void;
    overload function AddUInt16(name: ConstRef<winrt.HString>, value: UInt16, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddUInt16(name: ConstRef<winrt.HString>, value: UInt16, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddUInt16Array(name: ConstRef<winrt.HString>, value: winrt.ArrayView<UInt16>): Void;
    overload function AddUInt16Array(name: ConstRef<winrt.HString>, value: winrt.ArrayView<UInt16>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddUInt16Array(name: ConstRef<winrt.HString>, value: winrt.ArrayView<UInt16>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddInt32(name: ConstRef<winrt.HString>, value: Int32): Void;
    overload function AddInt32(name: ConstRef<winrt.HString>, value: Int32, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddInt32(name: ConstRef<winrt.HString>, value: Int32, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddInt32Array(name: ConstRef<winrt.HString>, value: winrt.ArrayView<Int32>): Void;
    overload function AddInt32Array(name: ConstRef<winrt.HString>, value: winrt.ArrayView<Int32>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddInt32Array(name: ConstRef<winrt.HString>, value: winrt.ArrayView<Int32>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddUInt32(name: ConstRef<winrt.HString>, value: UInt32): Void;
    overload function AddUInt32(name: ConstRef<winrt.HString>, value: UInt32, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddUInt32(name: ConstRef<winrt.HString>, value: UInt32, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddUInt32Array(name: ConstRef<winrt.HString>, value: winrt.ArrayView<UInt32>): Void;
    overload function AddUInt32Array(name: ConstRef<winrt.HString>, value: winrt.ArrayView<UInt32>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddUInt32Array(name: ConstRef<winrt.HString>, value: winrt.ArrayView<UInt32>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddInt64(name: ConstRef<winrt.HString>, value: Int64): Void;
    overload function AddInt64(name: ConstRef<winrt.HString>, value: Int64, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddInt64(name: ConstRef<winrt.HString>, value: Int64, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddInt64Array(name: ConstRef<winrt.HString>, value: winrt.ArrayView<Int64>): Void;
    overload function AddInt64Array(name: ConstRef<winrt.HString>, value: winrt.ArrayView<Int64>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddInt64Array(name: ConstRef<winrt.HString>, value: winrt.ArrayView<Int64>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddUInt64(name: ConstRef<winrt.HString>, value: UInt64): Void;
    overload function AddUInt64(name: ConstRef<winrt.HString>, value: UInt64, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddUInt64(name: ConstRef<winrt.HString>, value: UInt64, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddUInt64Array(name: ConstRef<winrt.HString>, value: winrt.ArrayView<UInt64>): Void;
    overload function AddUInt64Array(name: ConstRef<winrt.HString>, value: winrt.ArrayView<UInt64>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddUInt64Array(name: ConstRef<winrt.HString>, value: winrt.ArrayView<UInt64>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddSingle(name: ConstRef<winrt.HString>, value: Float32): Void;
    overload function AddSingle(name: ConstRef<winrt.HString>, value: Float32, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddSingle(name: ConstRef<winrt.HString>, value: Float32, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddSingleArray(name: ConstRef<winrt.HString>, value: winrt.ArrayView<Float32>): Void;
    overload function AddSingleArray(name: ConstRef<winrt.HString>, value: winrt.ArrayView<Float32>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddSingleArray(name: ConstRef<winrt.HString>, value: winrt.ArrayView<Float32>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddDouble(name: ConstRef<winrt.HString>, value: Float64): Void;
    overload function AddDouble(name: ConstRef<winrt.HString>, value: Float64, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddDouble(name: ConstRef<winrt.HString>, value: Float64, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddDoubleArray(name: ConstRef<winrt.HString>, value: winrt.ArrayView<Float64>): Void;
    overload function AddDoubleArray(name: ConstRef<winrt.HString>, value: winrt.ArrayView<Float64>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddDoubleArray(name: ConstRef<winrt.HString>, value: winrt.ArrayView<Float64>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddChar16(name: ConstRef<winrt.HString>, value: Char): Void;
    overload function AddChar16(name: ConstRef<winrt.HString>, value: Char, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddChar16(name: ConstRef<winrt.HString>, value: Char, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddChar16Array(name: ConstRef<winrt.HString>, value: winrt.ArrayView<Char>): Void;
    overload function AddChar16Array(name: ConstRef<winrt.HString>, value: winrt.ArrayView<Char>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddChar16Array(name: ConstRef<winrt.HString>, value: winrt.ArrayView<Char>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddBoolean(name: ConstRef<winrt.HString>, value: Bool): Void;
    overload function AddBoolean(name: ConstRef<winrt.HString>, value: Bool, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddBoolean(name: ConstRef<winrt.HString>, value: Bool, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddBooleanArray(name: ConstRef<winrt.HString>, value: winrt.ArrayView<Bool>): Void;
    overload function AddBooleanArray(name: ConstRef<winrt.HString>, value: winrt.ArrayView<Bool>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddBooleanArray(name: ConstRef<winrt.HString>, value: winrt.ArrayView<Bool>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddString(name: ConstRef<winrt.HString>, value: ConstRef<winrt.HString>): Void;
    overload function AddString(name: ConstRef<winrt.HString>, value: ConstRef<winrt.HString>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddString(name: ConstRef<winrt.HString>, value: ConstRef<winrt.HString>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddStringArray(name: ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.HString>): Void;
    overload function AddStringArray(name: ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.HString>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddStringArray(name: ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.HString>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddGuid(name: ConstRef<winrt.HString>, value: ConstRef<winrt.Guid>): Void;
    overload function AddGuid(name: ConstRef<winrt.HString>, value: ConstRef<winrt.Guid>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddGuid(name: ConstRef<winrt.HString>, value: ConstRef<winrt.Guid>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddGuidArray(name: ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.Guid>): Void;
    overload function AddGuidArray(name: ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.Guid>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddGuidArray(name: ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.Guid>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddDateTime(name: ConstRef<winrt.HString>, value: ConstRef<winrt.windows.foundation.DateTime>): Void;
    overload function AddDateTime(name: ConstRef<winrt.HString>, value: ConstRef<winrt.windows.foundation.DateTime>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddDateTime(name: ConstRef<winrt.HString>, value: ConstRef<winrt.windows.foundation.DateTime>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddDateTimeArray(name: ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.windows.foundation.DateTime>): Void;
    overload function AddDateTimeArray(name: ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.windows.foundation.DateTime>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddDateTimeArray(name: ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.windows.foundation.DateTime>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddTimeSpan(name: ConstRef<winrt.HString>, value: ConstRef<winrt.windows.foundation.TimeSpan>): Void;
    overload function AddTimeSpan(name: ConstRef<winrt.HString>, value: ConstRef<winrt.windows.foundation.TimeSpan>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddTimeSpan(name: ConstRef<winrt.HString>, value: ConstRef<winrt.windows.foundation.TimeSpan>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddTimeSpanArray(name: ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.windows.foundation.TimeSpan>): Void;
    overload function AddTimeSpanArray(name: ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.windows.foundation.TimeSpan>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddTimeSpanArray(name: ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.windows.foundation.TimeSpan>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddPoint(name: ConstRef<winrt.HString>, value: ConstRef<winrt.windows.foundation.Point>): Void;
    overload function AddPoint(name: ConstRef<winrt.HString>, value: ConstRef<winrt.windows.foundation.Point>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddPoint(name: ConstRef<winrt.HString>, value: ConstRef<winrt.windows.foundation.Point>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddPointArray(name: ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.windows.foundation.Point>): Void;
    overload function AddPointArray(name: ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.windows.foundation.Point>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddPointArray(name: ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.windows.foundation.Point>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddSize(name: ConstRef<winrt.HString>, value: ConstRef<winrt.windows.foundation.Size>): Void;
    overload function AddSize(name: ConstRef<winrt.HString>, value: ConstRef<winrt.windows.foundation.Size>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddSize(name: ConstRef<winrt.HString>, value: ConstRef<winrt.windows.foundation.Size>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddSizeArray(name: ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.windows.foundation.Size>): Void;
    overload function AddSizeArray(name: ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.windows.foundation.Size>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddSizeArray(name: ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.windows.foundation.Size>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddRect(name: ConstRef<winrt.HString>, value: ConstRef<winrt.windows.foundation.Rect>): Void;
    overload function AddRect(name: ConstRef<winrt.HString>, value: ConstRef<winrt.windows.foundation.Rect>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddRect(name: ConstRef<winrt.HString>, value: ConstRef<winrt.windows.foundation.Rect>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
    overload function AddRectArray(name: ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.windows.foundation.Rect>): Void;
    overload function AddRectArray(name: ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.windows.foundation.Rect>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddRectArray(name: ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.windows.foundation.Rect>, format: ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: Int32): Void;
}
