package winrt.windows.foundation.diagnostics;

@:valueType
@:include("winrt/Windows.Foundation.Diagnostics.h", true)
@:native("winrt::Windows::Foundation::Diagnostics::ILoggingFields")
extern interface ILoggingFields extends winrt.windows.foundation.IInspectable
{
    function Clear(): Void;
    overload function BeginStruct(name: cxx.ConstRef<winrt.HString>): Void;
    overload function BeginStruct(name: cxx.ConstRef<winrt.HString>, tags: cxx.num.Int32): Void;
    function EndStruct(): Void;
    overload function AddEmpty(name: cxx.ConstRef<winrt.HString>): Void;
    overload function AddEmpty(name: cxx.ConstRef<winrt.HString>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddEmpty(name: cxx.ConstRef<winrt.HString>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddUInt8(name: cxx.ConstRef<winrt.HString>, value: cxx.num.UInt8): Void;
    overload function AddUInt8(name: cxx.ConstRef<winrt.HString>, value: cxx.num.UInt8, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddUInt8(name: cxx.ConstRef<winrt.HString>, value: cxx.num.UInt8, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddUInt8Array(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<cxx.num.UInt8>): Void;
    overload function AddUInt8Array(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<cxx.num.UInt8>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddUInt8Array(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<cxx.num.UInt8>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddInt16(name: cxx.ConstRef<winrt.HString>, value: cxx.num.Int16): Void;
    overload function AddInt16(name: cxx.ConstRef<winrt.HString>, value: cxx.num.Int16, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddInt16(name: cxx.ConstRef<winrt.HString>, value: cxx.num.Int16, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddInt16Array(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<cxx.num.Int16>): Void;
    overload function AddInt16Array(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<cxx.num.Int16>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddInt16Array(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<cxx.num.Int16>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddUInt16(name: cxx.ConstRef<winrt.HString>, value: cxx.num.UInt16): Void;
    overload function AddUInt16(name: cxx.ConstRef<winrt.HString>, value: cxx.num.UInt16, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddUInt16(name: cxx.ConstRef<winrt.HString>, value: cxx.num.UInt16, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddUInt16Array(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<cxx.num.UInt16>): Void;
    overload function AddUInt16Array(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<cxx.num.UInt16>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddUInt16Array(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<cxx.num.UInt16>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddInt32(name: cxx.ConstRef<winrt.HString>, value: cxx.num.Int32): Void;
    overload function AddInt32(name: cxx.ConstRef<winrt.HString>, value: cxx.num.Int32, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddInt32(name: cxx.ConstRef<winrt.HString>, value: cxx.num.Int32, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddInt32Array(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<cxx.num.Int32>): Void;
    overload function AddInt32Array(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<cxx.num.Int32>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddInt32Array(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<cxx.num.Int32>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddUInt32(name: cxx.ConstRef<winrt.HString>, value: cxx.num.UInt32): Void;
    overload function AddUInt32(name: cxx.ConstRef<winrt.HString>, value: cxx.num.UInt32, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddUInt32(name: cxx.ConstRef<winrt.HString>, value: cxx.num.UInt32, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddUInt32Array(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<cxx.num.UInt32>): Void;
    overload function AddUInt32Array(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<cxx.num.UInt32>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddUInt32Array(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<cxx.num.UInt32>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddInt64(name: cxx.ConstRef<winrt.HString>, value: cxx.num.Int64): Void;
    overload function AddInt64(name: cxx.ConstRef<winrt.HString>, value: cxx.num.Int64, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddInt64(name: cxx.ConstRef<winrt.HString>, value: cxx.num.Int64, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddInt64Array(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<cxx.num.Int64>): Void;
    overload function AddInt64Array(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<cxx.num.Int64>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddInt64Array(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<cxx.num.Int64>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddUInt64(name: cxx.ConstRef<winrt.HString>, value: cxx.num.UInt64): Void;
    overload function AddUInt64(name: cxx.ConstRef<winrt.HString>, value: cxx.num.UInt64, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddUInt64(name: cxx.ConstRef<winrt.HString>, value: cxx.num.UInt64, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddUInt64Array(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<cxx.num.UInt64>): Void;
    overload function AddUInt64Array(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<cxx.num.UInt64>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddUInt64Array(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<cxx.num.UInt64>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddSingle(name: cxx.ConstRef<winrt.HString>, value: cxx.num.Float32): Void;
    overload function AddSingle(name: cxx.ConstRef<winrt.HString>, value: cxx.num.Float32, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddSingle(name: cxx.ConstRef<winrt.HString>, value: cxx.num.Float32, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddSingleArray(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<cxx.num.Float32>): Void;
    overload function AddSingleArray(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<cxx.num.Float32>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddSingleArray(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<cxx.num.Float32>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddDouble(name: cxx.ConstRef<winrt.HString>, value: cxx.num.Float64): Void;
    overload function AddDouble(name: cxx.ConstRef<winrt.HString>, value: cxx.num.Float64, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddDouble(name: cxx.ConstRef<winrt.HString>, value: cxx.num.Float64, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddDoubleArray(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<cxx.num.Float64>): Void;
    overload function AddDoubleArray(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<cxx.num.Float64>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddDoubleArray(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<cxx.num.Float64>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddChar16(name: cxx.ConstRef<winrt.HString>, value: cxx.Char): Void;
    overload function AddChar16(name: cxx.ConstRef<winrt.HString>, value: cxx.Char, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddChar16(name: cxx.ConstRef<winrt.HString>, value: cxx.Char, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddChar16Array(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<cxx.Char>): Void;
    overload function AddChar16Array(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<cxx.Char>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddChar16Array(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<cxx.Char>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddBoolean(name: cxx.ConstRef<winrt.HString>, value: Bool): Void;
    overload function AddBoolean(name: cxx.ConstRef<winrt.HString>, value: Bool, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddBoolean(name: cxx.ConstRef<winrt.HString>, value: Bool, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddBooleanArray(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<Bool>): Void;
    overload function AddBooleanArray(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<Bool>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddBooleanArray(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<Bool>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddString(name: cxx.ConstRef<winrt.HString>, value: cxx.ConstRef<winrt.HString>): Void;
    overload function AddString(name: cxx.ConstRef<winrt.HString>, value: cxx.ConstRef<winrt.HString>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddString(name: cxx.ConstRef<winrt.HString>, value: cxx.ConstRef<winrt.HString>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddStringArray(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.HString>): Void;
    overload function AddStringArray(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.HString>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddStringArray(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.HString>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddGuid(name: cxx.ConstRef<winrt.HString>, value: cxx.ConstRef<winrt.Guid>): Void;
    overload function AddGuid(name: cxx.ConstRef<winrt.HString>, value: cxx.ConstRef<winrt.Guid>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddGuid(name: cxx.ConstRef<winrt.HString>, value: cxx.ConstRef<winrt.Guid>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddGuidArray(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.Guid>): Void;
    overload function AddGuidArray(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.Guid>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddGuidArray(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.Guid>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddDateTime(name: cxx.ConstRef<winrt.HString>, value: cxx.ConstRef<winrt.windows.foundation.DateTime>): Void;
    overload function AddDateTime(name: cxx.ConstRef<winrt.HString>, value: cxx.ConstRef<winrt.windows.foundation.DateTime>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddDateTime(name: cxx.ConstRef<winrt.HString>, value: cxx.ConstRef<winrt.windows.foundation.DateTime>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddDateTimeArray(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.windows.foundation.DateTime>): Void;
    overload function AddDateTimeArray(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.windows.foundation.DateTime>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddDateTimeArray(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.windows.foundation.DateTime>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddTimeSpan(name: cxx.ConstRef<winrt.HString>, value: cxx.ConstRef<winrt.windows.foundation.TimeSpan>): Void;
    overload function AddTimeSpan(name: cxx.ConstRef<winrt.HString>, value: cxx.ConstRef<winrt.windows.foundation.TimeSpan>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddTimeSpan(name: cxx.ConstRef<winrt.HString>, value: cxx.ConstRef<winrt.windows.foundation.TimeSpan>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddTimeSpanArray(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.windows.foundation.TimeSpan>): Void;
    overload function AddTimeSpanArray(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.windows.foundation.TimeSpan>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddTimeSpanArray(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.windows.foundation.TimeSpan>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddPoint(name: cxx.ConstRef<winrt.HString>, value: cxx.ConstRef<winrt.windows.foundation.Point>): Void;
    overload function AddPoint(name: cxx.ConstRef<winrt.HString>, value: cxx.ConstRef<winrt.windows.foundation.Point>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddPoint(name: cxx.ConstRef<winrt.HString>, value: cxx.ConstRef<winrt.windows.foundation.Point>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddPointArray(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.windows.foundation.Point>): Void;
    overload function AddPointArray(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.windows.foundation.Point>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddPointArray(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.windows.foundation.Point>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddSize(name: cxx.ConstRef<winrt.HString>, value: cxx.ConstRef<winrt.windows.foundation.Size>): Void;
    overload function AddSize(name: cxx.ConstRef<winrt.HString>, value: cxx.ConstRef<winrt.windows.foundation.Size>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddSize(name: cxx.ConstRef<winrt.HString>, value: cxx.ConstRef<winrt.windows.foundation.Size>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddSizeArray(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.windows.foundation.Size>): Void;
    overload function AddSizeArray(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.windows.foundation.Size>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddSizeArray(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.windows.foundation.Size>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddRect(name: cxx.ConstRef<winrt.HString>, value: cxx.ConstRef<winrt.windows.foundation.Rect>): Void;
    overload function AddRect(name: cxx.ConstRef<winrt.HString>, value: cxx.ConstRef<winrt.windows.foundation.Rect>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddRect(name: cxx.ConstRef<winrt.HString>, value: cxx.ConstRef<winrt.windows.foundation.Rect>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
    overload function AddRectArray(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.windows.foundation.Rect>): Void;
    overload function AddRectArray(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.windows.foundation.Rect>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>): Void;
    overload function AddRectArray(name: cxx.ConstRef<winrt.HString>, value: winrt.ArrayView<winrt.windows.foundation.Rect>, format: cxx.ConstRef<winrt.windows.foundation.diagnostics.LoggingFieldFormat>, tags: cxx.num.Int32): Void;
}
