package winrt.windows.ui.xaml.controls.maps;

@:include("winrt/Windows.UI.Xaml.Controls.Maps.h", true)
@:native("winrt::Windows::UI::Xaml::Controls::Maps::MapStyleSheetEntries")
extern class MapStyleSheetEntries
{
    static overload function Area(): winrt.HString;
    static overload function Airport(): winrt.HString;
    static overload function Cemetery(): winrt.HString;
    static overload function Continent(): winrt.HString;
    static overload function Education(): winrt.HString;
    static overload function IndigenousPeoplesReserve(): winrt.HString;
    static overload function Island(): winrt.HString;
    static overload function Medical(): winrt.HString;
    static overload function Military(): winrt.HString;
    static overload function Nautical(): winrt.HString;
    static overload function Neighborhood(): winrt.HString;
    static overload function Runway(): winrt.HString;
    static overload function Sand(): winrt.HString;
    static overload function ShoppingCenter(): winrt.HString;
    static overload function Stadium(): winrt.HString;
    static overload function Vegetation(): winrt.HString;
    static overload function Forest(): winrt.HString;
    static overload function GolfCourse(): winrt.HString;
    static overload function Park(): winrt.HString;
    static overload function PlayingField(): winrt.HString;
    static overload function Reserve(): winrt.HString;
    static overload function Point(): winrt.HString;
    static overload function NaturalPoint(): winrt.HString;
    static overload function Peak(): winrt.HString;
    static overload function VolcanicPeak(): winrt.HString;
    static overload function WaterPoint(): winrt.HString;
    static overload function PointOfInterest(): winrt.HString;
    static overload function Business(): winrt.HString;
    static overload function FoodPoint(): winrt.HString;
    static overload function PopulatedPlace(): winrt.HString;
    static overload function Capital(): winrt.HString;
    static overload function AdminDistrictCapital(): winrt.HString;
    static overload function CountryRegionCapital(): winrt.HString;
    static overload function RoadShield(): winrt.HString;
    static overload function RoadExit(): winrt.HString;
    static overload function Transit(): winrt.HString;
    static overload function Political(): winrt.HString;
    static overload function CountryRegion(): winrt.HString;
    static overload function AdminDistrict(): winrt.HString;
    static overload function District(): winrt.HString;
    static overload function Structure(): winrt.HString;
    static overload function Building(): winrt.HString;
    static overload function EducationBuilding(): winrt.HString;
    static overload function MedicalBuilding(): winrt.HString;
    static overload function TransitBuilding(): winrt.HString;
    static overload function Transportation(): winrt.HString;
    static overload function Road(): winrt.HString;
    static overload function ControlledAccessHighway(): winrt.HString;
    static overload function HighSpeedRamp(): winrt.HString;
    static overload function Highway(): winrt.HString;
    static overload function MajorRoad(): winrt.HString;
    static overload function ArterialRoad(): winrt.HString;
    static overload function Street(): winrt.HString;
    static overload function Ramp(): winrt.HString;
    static overload function UnpavedStreet(): winrt.HString;
    static overload function TollRoad(): winrt.HString;
    static overload function Railway(): winrt.HString;
    static overload function Trail(): winrt.HString;
    static overload function WaterRoute(): winrt.HString;
    static overload function Water(): winrt.HString;
    static overload function River(): winrt.HString;
    static overload function RouteLine(): winrt.HString;
    static overload function WalkingRoute(): winrt.HString;
    static overload function DrivingRoute(): winrt.HString;
}
