package winrt.windows.security.authentication.identity.provider;

@:valueType
@:include("winrt/Windows.Security.Authentication.Identity.Provider.h", true)
@:native("winrt::Windows::Security::Authentication::Identity::Provider::SecondaryAuthenticationFactorRegistration")
extern class SecondaryAuthenticationFactorRegistration
    implements winrt.windows.security.authentication.identity.provider.ISecondaryAuthenticationFactorRegistration
{
    function FinishRegisteringDeviceAsync(deviceConfigurationData: cxx.ConstRef<winrt.windows.storage.streams.IBuffer>): winrt.windows.foundation.IAsyncAction;
    function AbortRegisteringDeviceAsync(errorLogMessage: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncAction;
    overload function RegisterDevicePresenceMonitoringAsync(deviceId: cxx.ConstRef<winrt.HString>, deviceInstancePath: cxx.ConstRef<winrt.HString>, monitoringMode: cxx.ConstRef<winrt.windows.security.authentication.identity.provider.SecondaryAuthenticationFactorDevicePresenceMonitoringMode>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.authentication.identity.provider.SecondaryAuthenticationFactorDevicePresenceMonitoringRegistrationStatus> /* GenericTypeInstSig */;
    overload function RegisterDevicePresenceMonitoringAsync(deviceId: cxx.ConstRef<winrt.HString>, deviceInstancePath: cxx.ConstRef<winrt.HString>, monitoringMode: cxx.ConstRef<winrt.windows.security.authentication.identity.provider.SecondaryAuthenticationFactorDevicePresenceMonitoringMode>, deviceFriendlyName: cxx.ConstRef<winrt.HString>, deviceModelNumber: cxx.ConstRef<winrt.HString>, deviceConfigurationData: cxx.ConstRef<winrt.windows.storage.streams.IBuffer>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.authentication.identity.provider.SecondaryAuthenticationFactorDevicePresenceMonitoringRegistrationStatus> /* GenericTypeInstSig */;
    function UnregisterDevicePresenceMonitoringAsync(deviceId: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncAction;
    function IsDevicePresenceMonitoringSupported(): Bool;
    function RequestStartRegisteringDeviceAsync(deviceId: cxx.ConstRef<winrt.HString>, capabilities: cxx.ConstRef<winrt.windows.security.authentication.identity.provider.SecondaryAuthenticationFactorDeviceCapabilities>, deviceFriendlyName: cxx.ConstRef<winrt.HString>, deviceModelNumber: cxx.ConstRef<winrt.HString>, deviceKey: cxx.ConstRef<winrt.windows.storage.streams.IBuffer>, mutualAuthenticationKey: cxx.ConstRef<winrt.windows.storage.streams.IBuffer>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.authentication.identity.provider.SecondaryAuthenticationFactorRegistrationResult> /* GenericTypeInstSig */;
    function FindAllRegisteredDeviceInfoAsync(queryType: cxx.ConstRef<winrt.windows.security.authentication.identity.provider.SecondaryAuthenticationFactorDeviceFindScope>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.security.authentication.identity.provider.SecondaryAuthenticationFactorInfo> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    function UnregisterDeviceAsync(deviceId: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncAction;
    function UpdateDeviceConfigurationDataAsync(deviceId: cxx.ConstRef<winrt.HString>, deviceConfigurationData: cxx.ConstRef<winrt.windows.storage.streams.IBuffer>): winrt.windows.foundation.IAsyncAction;
    static overload function RegisterDevicePresenceMonitoringAsync(deviceId: cxx.ConstRef<winrt.HString>, deviceInstancePath: cxx.ConstRef<winrt.HString>, monitoringMode: cxx.ConstRef<winrt.windows.security.authentication.identity.provider.SecondaryAuthenticationFactorDevicePresenceMonitoringMode>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.authentication.identity.provider.SecondaryAuthenticationFactorDevicePresenceMonitoringRegistrationStatus> /* GenericTypeInstSig */;
    static overload function RegisterDevicePresenceMonitoringAsync(deviceId: cxx.ConstRef<winrt.HString>, deviceInstancePath: cxx.ConstRef<winrt.HString>, monitoringMode: cxx.ConstRef<winrt.windows.security.authentication.identity.provider.SecondaryAuthenticationFactorDevicePresenceMonitoringMode>, deviceFriendlyName: cxx.ConstRef<winrt.HString>, deviceModelNumber: cxx.ConstRef<winrt.HString>, deviceConfigurationData: cxx.ConstRef<winrt.windows.storage.streams.IBuffer>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.authentication.identity.provider.SecondaryAuthenticationFactorDevicePresenceMonitoringRegistrationStatus> /* GenericTypeInstSig */;
    static function UnregisterDevicePresenceMonitoringAsync(deviceId: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncAction;
    static function IsDevicePresenceMonitoringSupported(): Bool;
    static function RequestStartRegisteringDeviceAsync(deviceId: cxx.ConstRef<winrt.HString>, capabilities: cxx.ConstRef<winrt.windows.security.authentication.identity.provider.SecondaryAuthenticationFactorDeviceCapabilities>, deviceFriendlyName: cxx.ConstRef<winrt.HString>, deviceModelNumber: cxx.ConstRef<winrt.HString>, deviceKey: cxx.ConstRef<winrt.windows.storage.streams.IBuffer>, mutualAuthenticationKey: cxx.ConstRef<winrt.windows.storage.streams.IBuffer>): winrt.windows.foundation.IAsyncOperation<winrt.windows.security.authentication.identity.provider.SecondaryAuthenticationFactorRegistrationResult> /* GenericTypeInstSig */;
    static function FindAllRegisteredDeviceInfoAsync(queryType: cxx.ConstRef<winrt.windows.security.authentication.identity.provider.SecondaryAuthenticationFactorDeviceFindScope>): winrt.windows.foundation.IAsyncOperation<winrt.windows.foundation.collections.IVectorView<winrt.windows.security.authentication.identity.provider.SecondaryAuthenticationFactorInfo> /* GenericTypeInstSig */> /* GenericTypeInstSig */;
    static function UnregisterDeviceAsync(deviceId: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncAction;
    static function UpdateDeviceConfigurationDataAsync(deviceId: cxx.ConstRef<winrt.HString>, deviceConfigurationData: cxx.ConstRef<winrt.windows.storage.streams.IBuffer>): winrt.windows.foundation.IAsyncAction;
}
