package winrt.windows.management.deployment;

@:valueType
@:include("winrt/Windows.Management.Deployment.h", true)
@:native("winrt::Windows::Management::Deployment::IPackageManager2")
extern interface IPackageManager2 extends winrt.windows.foundation.IInspectable
{
    function RemovePackageAsync(packageFullName: cxx.ConstRef<winrt.HString>, removalOptions: cxx.ConstRef<winrt.windows.management.deployment.RemovalOptions>): winrt.windows.foundation.IAsyncOperationWithProgress<winrt.windows.management.deployment.DeploymentResult, winrt.windows.management.deployment.DeploymentProgress> /* GenericTypeInstSig */;
    function StagePackageAsync(packageUri: cxx.ConstRef<winrt.windows.foundation.Uri>, dependencyPackageUris: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.windows.foundation.Uri> /* temp_GenericTypeInstSig */>, deploymentOptions: cxx.ConstRef<winrt.windows.management.deployment.DeploymentOptions>): winrt.windows.foundation.IAsyncOperationWithProgress<winrt.windows.management.deployment.DeploymentResult, winrt.windows.management.deployment.DeploymentProgress> /* GenericTypeInstSig */;
    function RegisterPackageByFullNameAsync(mainPackageFullName: cxx.ConstRef<winrt.HString>, dependencyPackageFullNames: cxx.ConstRef<winrt.windows.foundation.collections.IIterable<winrt.HString> /* temp_GenericTypeInstSig */>, deploymentOptions: cxx.ConstRef<winrt.windows.management.deployment.DeploymentOptions>): winrt.windows.foundation.IAsyncOperationWithProgress<winrt.windows.management.deployment.DeploymentResult, winrt.windows.management.deployment.DeploymentProgress> /* GenericTypeInstSig */;
    overload function FindPackagesWithPackageTypes(packageTypes: cxx.ConstRef<winrt.windows.management.deployment.PackageTypes>): winrt.windows.foundation.collections.IIterable<winrt.windows.applicationmodel.Package> /* GenericTypeInstSig */;
    overload function FindPackagesForUserWithPackageTypes(userSecurityId: cxx.ConstRef<winrt.HString>, packageTypes: cxx.ConstRef<winrt.windows.management.deployment.PackageTypes>): winrt.windows.foundation.collections.IIterable<winrt.windows.applicationmodel.Package> /* GenericTypeInstSig */;
    overload function FindPackagesWithPackageTypes(packageName: cxx.ConstRef<winrt.HString>, packagePublisher: cxx.ConstRef<winrt.HString>, packageTypes: cxx.ConstRef<winrt.windows.management.deployment.PackageTypes>): winrt.windows.foundation.collections.IIterable<winrt.windows.applicationmodel.Package> /* GenericTypeInstSig */;
    overload function FindPackagesForUserWithPackageTypes(userSecurityId: cxx.ConstRef<winrt.HString>, packageName: cxx.ConstRef<winrt.HString>, packagePublisher: cxx.ConstRef<winrt.HString>, packageTypes: cxx.ConstRef<winrt.windows.management.deployment.PackageTypes>): winrt.windows.foundation.collections.IIterable<winrt.windows.applicationmodel.Package> /* GenericTypeInstSig */;
    overload function FindPackagesWithPackageTypes(packageFamilyName: cxx.ConstRef<winrt.HString>, packageTypes: cxx.ConstRef<winrt.windows.management.deployment.PackageTypes>): winrt.windows.foundation.collections.IIterable<winrt.windows.applicationmodel.Package> /* GenericTypeInstSig */;
    overload function FindPackagesForUserWithPackageTypes(userSecurityId: cxx.ConstRef<winrt.HString>, packageFamilyName: cxx.ConstRef<winrt.HString>, packageTypes: cxx.ConstRef<winrt.windows.management.deployment.PackageTypes>): winrt.windows.foundation.collections.IIterable<winrt.windows.applicationmodel.Package> /* GenericTypeInstSig */;
    function StageUserDataAsync(packageFullName: cxx.ConstRef<winrt.HString>): winrt.windows.foundation.IAsyncOperationWithProgress<winrt.windows.management.deployment.DeploymentResult, winrt.windows.management.deployment.DeploymentProgress> /* GenericTypeInstSig */;
}
