package winrt.windows.ui.xaml.core.direct;

@:valueType
@:unreflective
@:structAccess
@:semantics(variable)
@:include("winrt/Windows.UI.Xaml.Core.Direct.h", true)
@:native("winrt::Windows::UI::Xaml::Core::Direct::IXamlDirect")
extern interface IXamlDirect extends winrt.windows.foundation.IInspectable
{
    function GetObject(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>): winrt.windows.foundation.IInspectable;
    function GetXamlDirectObject(object: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.foundation.IInspectable>): winrt.windows.ui.xaml.core.direct.IXamlDirectObject;
    function CreateInstance(typeIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlTypeIndex>): winrt.windows.ui.xaml.core.direct.IXamlDirectObject;
    function SetObjectProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>, value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.foundation.IInspectable>): Void;
    function SetXamlDirectObjectProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>, value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>): Void;
    function SetBooleanProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>, value: Bool): Void;
    function SetDoubleProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>, value: #if reflaxe.cpp cxx.num. #else cpp. #end Float64): Void;
    function SetInt32Property(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>, value: #if reflaxe.cpp cxx.num. #else cpp. #end Int32): Void;
    function SetStringProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>, value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.HString>): Void;
    function SetDateTimeProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>, value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.foundation.DateTime>): Void;
    function SetPointProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>, value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.foundation.Point>): Void;
    function SetRectProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>, value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.foundation.Rect>): Void;
    function SetSizeProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>, value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.foundation.Size>): Void;
    function SetTimeSpanProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>, value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.foundation.TimeSpan>): Void;
    function SetColorProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>, value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.Color>): Void;
    function SetCornerRadiusProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>, value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.CornerRadius>): Void;
    function SetDurationProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>, value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.Duration>): Void;
    function SetGridLengthProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>, value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.GridLength>): Void;
    function SetThicknessProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>, value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.Thickness>): Void;
    function SetMatrixProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>, value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.media.Matrix>): Void;
    function SetMatrix3DProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>, value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.media.media3d.Matrix3D>): Void;
    function SetEnumProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>, value: #if reflaxe.cpp cxx.num. #else cpp. #end UInt32): Void;
    function GetObjectProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>): winrt.windows.foundation.IInspectable;
    function GetXamlDirectObjectProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>): winrt.windows.ui.xaml.core.direct.IXamlDirectObject;
    function GetBooleanProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>): Bool;
    function GetDoubleProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>): #if reflaxe.cpp cxx.num. #else cpp. #end Float64;
    function GetInt32Property(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>): #if reflaxe.cpp cxx.num. #else cpp. #end Int32;
    function GetStringProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>): winrt.HString;
    function GetDateTimeProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>): winrt.windows.foundation.DateTime;
    function GetPointProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>): winrt.windows.foundation.Point;
    function GetRectProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>): winrt.windows.foundation.Rect;
    function GetSizeProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>): winrt.windows.foundation.Size;
    function GetTimeSpanProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>): winrt.windows.foundation.TimeSpan;
    function GetColorProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>): winrt.windows.ui.Color;
    function GetCornerRadiusProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>): winrt.windows.ui.xaml.CornerRadius;
    function GetDurationProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>): winrt.windows.ui.xaml.Duration;
    function GetGridLengthProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>): winrt.windows.ui.xaml.GridLength;
    function GetThicknessProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>): winrt.windows.ui.xaml.Thickness;
    function GetMatrixProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>): winrt.windows.ui.xaml.media.Matrix;
    function GetMatrix3DProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>): winrt.windows.ui.xaml.media.media3d.Matrix3D;
    function GetEnumProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>): #if reflaxe.cpp cxx.num. #else cpp. #end UInt32;
    function ClearProperty(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, propertyIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlPropertyIndex>): Void;
    function GetCollectionCount(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>): #if reflaxe.cpp cxx.num. #else cpp. #end UInt32;
    function GetXamlDirectObjectFromCollectionAt(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, index: #if reflaxe.cpp cxx.num. #else cpp. #end UInt32): winrt.windows.ui.xaml.core.direct.IXamlDirectObject;
    function AddToCollection(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>): Void;
    function InsertIntoCollectionAt(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, index: #if reflaxe.cpp cxx.num. #else cpp. #end UInt32, value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>): Void;
    function RemoveFromCollection(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, value: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>): Bool;
    function RemoveFromCollectionAt(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, index: #if reflaxe.cpp cxx.num. #else cpp. #end UInt32): Void;
    function ClearCollection(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>): Void;
    overload function AddEventHandler(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, eventIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlEventIndex>, handler: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.foundation.IInspectable>): Void;
    overload function AddEventHandler(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, eventIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlEventIndex>, handler: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.foundation.IInspectable>, handledEventsToo: Bool): Void;
    function RemoveEventHandler(xamlDirectObject: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.IXamlDirectObject>, eventIndex: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.ui.xaml.core.direct.XamlEventIndex>, handler: #if reflaxe.cpp cxx.ConstRef #else cpp.Reference #end <winrt.windows.foundation.IInspectable>): Void;
}
